import { pgTable, bigint, varchar, integer, smallint, numeric, date, timestamp, index } from 'drizzle-orm/pg-core'

export const flight = pgTable('flight', {
  id: bigint('id', { mode: 'number' }).primaryKey().generatedAlwaysAsIdentity(),
  createdBy: varchar('created_by', { length: 30 }).notNull().default('system'),
  createdAt: timestamp('created_at').notNull().defaultNow(),
  updatedBy: varchar('updated_by', { length: 30 }).notNull().default('system'),
  updatedAt: timestamp('updated_at').notNull().defaultNow(),
  airline: varchar('airline', { length: 3 }).notNull(),
  fltDt: date('flt_dt').notNull(),
  fltNum: varchar('flt_num', { length: 50 }).notNull(),
  depArp: varchar('dep_arp', { length: 3 }).notNull(),
  arvArp: varchar('arv_arp', { length: 3 }).notNull(),
  schDepDtUtc: timestamp('sch_dep_dt_utc').notNull(),
  schArvDtUtc: timestamp('sch_arv_dt_utc').notNull(),
  actDepDtUtc: timestamp('act_dep_dt_utc').notNull(),
  actArvDtUtc: timestamp('act_arv_dt_utc').notNull(),
  estDepDtUtc: timestamp('est_dep_dt_utc'),
  estArvDtUtc: timestamp('est_arv_dt_utc'),
  actTaxiInUtc: timestamp('act_taxi_in_utc'),
  actTaxiOutUtc: timestamp('act_taxi_out_utc'),
  actTakeOffUtc: timestamp('act_take_off_utc'),
  actTouchDownUtc: timestamp('act_touch_down_utc'),
  actDepArp: varchar('act_dep_arp', { length: 3 }).notNull(),
  actArvArp: varchar('act_arv_arp', { length: 3 }).notNull(),
  flightFlag: varchar('flight_flag', { length: 1 }).notNull().default('A'),
  flightAssignment: varchar('flight_assignment', { length: 10 }),
  blkMin: integer('blk_min').notNull(),
  fleet: varchar('fleet', { length: 10 }).notNull(),
  onwardFltNum: varchar('onward_flt_num', { length: 5 }),
  register: varchar('register', { length: 30 }),
  acOwner: varchar('ac_owner', { length: 6 }),
  pilotOwner: varchar('pilot_owner', { length: 6 }),
  cabinOwner: varchar('cabin_owner', { length: 6 }),
  airmarshalOwner: varchar('airmarshal_owner', { length: 6 }),
  commuteId: bigint('commute_id', { mode: 'number' }),
  segType: varchar('seg_type', { length: 1 }),
  fltType: varchar('flt_type', { length: 8 }).notNull(),
  fltSts: varchar('flt_sts', { length: 3 }),
  fltVr: varchar('flt_vr', { length: 1 }),
  voyageStatus: smallint('voyage_status').notNull().default(0),
  isLocked: smallint('is_locked').notNull().default(0),
  schId: bigint('sch_id', { mode: 'number' }).notNull().default(0),
  vrAdd: numeric('vr_add').notNull().default('0'),
  liveId: bigint('live_id', { mode: 'number' }),
  etdChgTm: timestamp('etd_chg_tm'),
  interfaceFltId: varchar('interface_flt_id', { length: 40 }),
  apisStage: smallint('apis_stage'),
  price: numeric('price', { precision: 10, scale: 2 }),
  serviceType: varchar('service_type', { length: 5 }),
  fltLastDelayEtdUtc: timestamp('flt_last_delay_etd_utc'),
  fltDelayNotifyUtc: timestamp('flt_delay_notify_utc'),
  deviceCode: varchar('device_code', { length: 50 }),
  flightKey: varchar('flight_key', { length: 30 }),
  fltDtUtc: date('flt_dt_utc'),
  suffix: varchar('suffix', { length: 20 }),
  payFlyHours: smallint('pay_fly_hours'),
  actDoorClosedUtc: timestamp('act_door_closed_utc'),
  actDoorOpenUtc: timestamp('act_door_open_utc'),
  courseCode: varchar('course_code', { length: 30 }),
  remark: varchar('remark', { length: 512 }),
  subFleet: varchar('sub_fleet', { length: 64 }),
  originFltDtUtc: date('origin_flt_dt_utc'),
  originInterfaceFltId: varchar('origin_interface_flt_id', { length: 40 }),
  isDeleted: smallint('is_deleted').notNull().default(0),
  manualCompFlag: smallint('manual_comp_flag').notNull().default(0),
  legNo: integer('leg_no'),
}, (table) => [
  index('idx_flight_flt_dt').on(table.fltDt, table.fltDtUtc),
  index('idx_flight_flag').on(table.id, table.flightFlag),
  index('idx_flight_interface').on(table.interfaceFltId),
  index('idx_flight_str_end').on(table.schDepDtUtc, table.schArvDtUtc),
])
