
user  root;
worker_processes  auto;
pid /run/nginx.pid;
error_log /home/piercrew/software/web/nginx_logs/error.log;


events {
    worker_connections  10240;
}


http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    server_tokens off;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    log_format access_json '{"@timestamp":"$time_local",'
    '"host":"$server_addr",'
    '"clientip":"$remote_addr",'
    '"size":$body_bytes_sent,'
    '"responsetime":$request_time,'
    '"upstreamtime":"$upstream_response_time",'
    '"upstreamhost":"$upstream_addr",'
    '"http_host":"$host",'
    '"uri":"$uri",'
    '"domain":"$host",'
    '"x_forwarded_for":"$http_x_forwarded_for",'
    '"X-Real-IP":"$remote_addr",'
    '"referer":"$http_referer",'
    '"tcp_xff":"$proxy_protocol_addr",'
    '"http_user_agent":"$http_user_agent",'
    '"status":"$status"}';

    access_log  /home/piercrew/software/web/nginx_logs/access.log  access_json;

    sendfile        on;
    tcp_nopush     on;

    keepalive_timeout  65;

    # gzip on;
    #gzip_min_length 1024;
    #gzip_buffers 4 16k;
    #gzip_comp_level 2;
    #gzip_types *;
    #gzip_vary on;
    types_hash_max_size 4096;
    types_hash_bucket_size 128;
     
    client_header_buffer_size 4096k;
    large_client_header_buffers 6 4096k;
    client_header_timeout 300s;
    client_body_timeout 300s;
    proxy_connect_timeout 300s;
    proxy_send_timeout 300s;
    proxy_read_timeout 300s;
    client_max_body_size 500m;


    include /etc/nginx/conf.d/*.conf;
}

