// Generated by gantt/scripts/generate-dev-skills-data.mjs. Do not edit by hand.

export interface DevSkillResource {
  label: string
}

export interface DevSkillEntry {
  name: string
  folder: string
  number: number | null
  title: string
  description: string
  overview: string
  function: string
  howToUse: string
  resources: string[]
  sourcePath: string
}

export const DEV_SKILLS: DevSkillEntry[] = [
  {
    "name": "001-frontend-design",
    "folder": "001-frontend-design",
    "number": 1,
    "title": "ROIS-AI Gantt 前端设计技能",
    "description": "ROIS-AI Gantt 排班系统前端界面设计与修复。当用户讨论 Gantt 界面布局、样式、Canvas 渲染、Pane 布局、交互效果时自动触发。",
    "overview": "你是一个航空机组排班系统（ROIS-AI）的前端界面设计专家。",
    "function": "你是一个航空机组排班系统（ROIS-AI）的前端界面设计专家。",
    "howToUse": "ROIS-AI Gantt 排班系统前端界面设计与修复。当用户讨论 Gantt 界面布局、样式、Canvas 渲染、Pane 布局、交互效果时自动触发。",
    "resources": [],
    "sourcePath": ".agents/skills/001-frontend-design/SKILL.md"
  },
  {
    "name": "002-ui-ux-pro-max",
    "folder": "002-ui-ux-pro-max",
    "number": 2,
    "title": "ROIS-AI UI/UX 专业设计技能",
    "description": "航空排班系统专业级 UI/UX 设计，包括多主题切换、人性化交互、专业视觉效果。当用户讨论界面美化、主题、样式、用户体验时自动触发。",
    "overview": "你是一个航空行业软件的高级 UI/UX 设计师，专注于复杂数据密集型界面的设计。",
    "function": "你是一个航空行业软件的高级 UI/UX 设计师，专注于复杂数据密集型界面的设计。",
    "howToUse": "航空排班系统专业级 UI/UX 设计，包括多主题切换、人性化交互、专业视觉效果。当用户讨论界面美化、主题、样式、用户体验时自动触发。",
    "resources": [],
    "sourcePath": ".agents/skills/002-ui-ux-pro-max/SKILL.md"
  },
  {
    "name": "003-online-help-writing",
    "folder": "003-online-help-writing",
    "number": 3,
    "title": "Online Help Writing (ROIS-AI gantt)",
    "description": "Write or update the gantt in-app online Help (gantt/src/components/help/), or action test-team Help feedback docs. Triggers when the user mentions Help pages/topics/articles, Help screenshots, a \"Help-XXX Feedback\" doc, or asks to document a UI feature in Help. Enforces verify-against-code, match-UI-wording, screenshot, and test discipline so Help never drifts from the product.",
    "overview": "The in-app Help is a **user-facing operating manual**. Its only job is to be **accurate to the current UI and code**. Every recurring complaint from the test team has the same root cause: the manual drifted from what the app actually does. This skill is the playbook that prevents that. > Hard rule: **never describe Help content from memory or an old build.** Open the component that implements the feature and read it before you write a word.",
    "function": "The in-app Help is a **user-facing operating manual**. Its only job is to be **accurate to the current UI and code**. Every recurring complaint from the test team has the same root cause: the manual drifted from what the app actually does. This skill is the playbook that prevents that. > Hard rule: **never describe Help content from memory or an old build.** Open the component that implements the feature and read it before you write a word.",
    "howToUse": "1. **Read the feedback / requirement fully.** If it's a `Help-XXX Feedback*.docx`, extract it: `unzip -o \"<doc>.docx\" -d /tmp/fb && python3 -c \"import re,html;x=open('/tmp/fb/word/document.xml').read();[print(html.unescape(''.join(re.findall(r'<w:t[^>]*>(.*?)</w:t>',p,re.S)))) for p in re.split(r'</w:p>',x) if ''.join(re.findall(r'<w:t[^>]*>(.*?)</w:t>',p,re.S)).strip()]\"` 2. **Map each item to the component that implements it.** Grep for the dialog/toolbar/field. Read it. The code is the source of truth. 3. **Apply the feedback-handling protocol** (below) per item. 4. **Edit the topic `.tsx`** to match reality. Keep `help-data.ts`...",
    "resources": [],
    "sourcePath": ".agents/skills/003-online-help-writing/SKILL.md"
  },
  {
    "name": "004-scenario-run-debug",
    "folder": "004-scenario-run-debug",
    "number": 4,
    "title": "Core Rule",
    "description": "Use when a ROIS scenario run, scen run, scenario optimization, LegacyRO, engine-server /optimize/start, fetch failed, ro_input, pbs scenario-package, ro_output, task_id, or scenario result callback fails or returns no usable roster.",
    "overview": "Use `superpowers:systematic-debugging` first. Find the first failing boundary before proposing a fix. A top-level `fetch failed` is only a symptom. Treat remote PostgreSQL/CoreServer as authoritative for scenario, PBS, and solver-material debugging unless the user explicitly says local. Never write DB passwords, JWTs, SSH passwords, or production tokens into docs, logs, or skill resources.",
    "function": "Use `superpowers:systematic-debugging` first. Find the first failing boundary before proposing a fix. A top-level `fetch failed` is only a symptom. Treat remote PostgreSQL/CoreServer as authoritative for scenario, PBS, and solver-material debugging unless the user explicitly says local. Never write DB passwords, JWTs, SSH passwords, or production tokens into docs, logs, or skill resources.",
    "howToUse": "A debug answer should identify the failing boundary and cite the evidence: status/task id, log line, HTTP status/body, missing/present artifact, row count, or callback payload. If the root cause is still unknown, state exactly which boundary remains unproven and what evidence is needed next.",
    "resources": [
      "dir:agents",
      "dir:references"
    ],
    "sourcePath": ".agents/skills/004-scenario-run-debug/SKILL.md"
  },
  {
    "name": "005-routing-debug",
    "folder": "005-routing-debug",
    "number": 5,
    "title": "Core Rule",
    "description": "Use when Cloudflare 502/Bad Gateway, flair.rois.cloud, ai.rois.one, /altair, /fpqe/pbs, local Vite origin, cloudflared tunnel, port 5173/3030/5566, or public route-to-local-origin behavior fails or looks misrouted.",
    "overview": "Use `superpowers:systematic-debugging` first. A public 502 is a symptom; find the first failing boundary before changing configs or restarting services. Before routing/port work, read: - Root `CLAUDE.md` - `/Users/kimi/.codex/local-memos/rois-port-usage.md` Do not write secrets into docs or logs. Do not touch `ai.rois.one` / EVACC while fixing `flair.rois.cloud` unless the user explicitly asks.",
    "function": "Use `superpowers:systematic-debugging` first. A public 502 is a symptom; find the first failing boundary before changing configs or restarting services. Before routing/port work, read: - Root `CLAUDE.md` - `/Users/kimi/.codex/local-memos/rois-port-usage.md` Do not write secrets into docs or logs. Do not touch `ai.rois.one` / EVACC while fixing `flair.rois.cloud` unless the user explicitly asks.",
    "howToUse": "A routing debug answer must include: - failing public URL and HTTP status; - active tunnel config path and service target; - local listener status for the target port; - local origin HTTP status; - what restored service, if anything; - remaining root-cause gap if the process exit reason is still unknown.",
    "resources": [
      "dir:agents"
    ],
    "sourcePath": ".agents/skills/005-routing-debug/SKILL.md"
  },
  {
    "name": "006-rbot-feature-development",
    "folder": "006-rbot-feature-development",
    "number": 6,
    "title": "Required Workflow",
    "description": "Use when adding, changing, or debugging RBot chat capabilities in the ROIS Gantt app, including ai-server chat tools, tool_call_to_action mappings, Gantt AiAction types, dispatch-ai-action behavior, filter/sort/date actions, RBot prompts, and RBot E2E tests.",
    "overview": "Use the repository brainstorming/spec workflow before implementation when behavior changes. Use test-driven development for implementation: write a failing backend or frontend test, verify it fails for the expected reason, then implement the minimum change.",
    "function": "Use the repository brainstorming/spec workflow before implementation when behavior changes. Use test-driven development for implementation: write a failing backend or frontend test, verify it fails for the expected reason, then implement the minimum change.",
    "howToUse": "Use the repository brainstorming/spec workflow before implementation when behavior changes. Use test-driven development for implementation: write a failing backend or frontend test, verify it fails for the expected reason, then implement the minimum change.",
    "resources": [
      "dir:agents"
    ],
    "sourcePath": ".agents/skills/006-rbot-feature-development/SKILL.md"
  },
  {
    "name": "100-plane-ops",
    "folder": "100-plane-ops",
    "number": 100,
    "title": "Plane Project Ops (roiscloud)",
    "description": "Use when reading or editing items in the team's Plane project-management portal on roiscloud (workspace \"flair\", e.g. project \"PBS Dev Team\") via Playwright — listing work items, bulk-renaming titles, reading/updating descriptions, or translating Chinese titles/descriptions to \"English + original Chinese\".",
    "overview": "Drive the team's **Plane** PM portal (open-source, Jira/Linear-style) with Playwright + the Plane REST API. Reads via API; writes (rename, description) PATCH the API with the CSRF cookie. Session is cached so you log in once.",
    "function": "Drive the team's **Plane** PM portal (open-source, Jira/Linear-style) with Playwright + the Plane REST API. Reads via API; writes (rename, description) PATCH the API with the CSRF cookie. Session is cached so you log in once.",
    "howToUse": "Use when reading or editing items in the team's Plane project-management portal on roiscloud (workspace \"flair\", e.g. project \"PBS Dev Team\") via Playwright — listing work items, bulk-renaming titles, reading/updating descriptions, or translating Chinese titles/descriptions to \"English + original Chinese\".",
    "resources": [
      "dir:agents",
      "dir:scripts"
    ],
    "sourcePath": ".agents/skills/100-plane-ops/SKILL.md"
  },
  {
    "name": "101-enrich-plane-desc",
    "folder": "101-enrich-plane-desc",
    "number": 101,
    "title": "101-enrich-plane-desc",
    "description": "Use when enriching a Plane work item's description with structured content derived from the codebase and existing docs — goal, to-do, how to test, done acceptance. Triggers when the user asks to \"fill in\", \"enrich\", \"write up\", or \"document\" a Plane item (PBS-xxx) based on what's actually in the code.",
    "overview": "Write a structured, codebase-grounded description for a Plane work item. The result has four sections: **Overall Goal → Things To-Do → How To Test → Done Acceptance**. All content must be derived from reading the actual code, not from assumptions.",
    "function": "Write a structured, codebase-grounded description for a Plane work item. The result has four sections: **Overall Goal → Things To-Do → How To Test → Done Acceptance**. All content must be derived from reading the actual code, not from assumptions.",
    "howToUse": "Use when enriching a Plane work item's description with structured content derived from the codebase and existing docs — goal, to-do, how to test, done acceptance. Triggers when the user asks to \"fill in\", \"enrich\", \"write up\", or \"document\" a Plane item (PBS-xxx) based on what's actually in the code.",
    "resources": [
      "dir:agents"
    ],
    "sourcePath": ".agents/skills/101-enrich-plane-desc/SKILL.md"
  },
  {
    "name": "102-plane-cycle-backdate",
    "folder": "102-plane-cycle-backdate",
    "number": 102,
    "title": "The Problem",
    "description": "Use when you need to add issues to a COMPLETED Plane cycle (the API blocks it). This workaround creates an UPCOMING cycle, adds items while the cycle is open, then patches dates to historical values making it auto-complete.",
    "overview": "Plane's REST API blocks all modifications to completed cycles: - `POST .../cycle-issues/` → 400 \"already completed\" - `PATCH cycle end_date` → 400 \"already completed cannot be edited\" - `PATCH issue { cycle_id }` → 204 but silently ignored - DB is on 10.15.12.4 (separate VM, no SSH access from CoreServer/WebServer)",
    "function": "Plane's REST API blocks all modifications to completed cycles: - `POST .../cycle-issues/` → 400 \"already completed\" - `PATCH cycle end_date` → 400 \"already completed cannot be edited\" - `PATCH issue { cycle_id }` → 204 but silently ignored - DB is on 10.15.12.4 (separate VM, no SSH access from CoreServer/WebServer)",
    "howToUse": "Use when you need to add issues to a COMPLETED Plane cycle (the API blocks it). This workaround creates an UPCOMING cycle, adds items while the cycle is open, then patches dates to historical values making it auto-complete.",
    "resources": [
      "dir:agents"
    ],
    "sourcePath": ".agents/skills/102-plane-cycle-backdate/SKILL.md"
  },
  {
    "name": "103-capture-ro-solver-baseline",
    "folder": "103-capture-ro-solver-baseline",
    "number": 103,
    "title": "Capture an RO solver baseline from CoreServer",
    "description": "Capture a genuine PBS column-gen RO solver run (+ its C++ rule-engine artifacts) from the remote CoreServer as a baseline under ro-engine/baseline/scenario-<N>/, for porting the solver/legality to Rust. Use when the user kicks off a real solver run on CoreServer for a scenario id and wants the input/output/result.json + C++ rule.log/violation codes pulled down as the parity oracle.",
    "overview": "Pulls the **actual files a production column-gen solver run produced** (not a reconstruction) into `ro-engine/baseline/scenario-<N>/`, mirroring `ro-engine/baseline/scenario-6/`. The prize is the **C++ rule-engine evidence** (`logs/rule.log` + `output_rules.txt`) — the oracle the Rust legality port must reproduce. Background: `docs/modules/ro-engine/solver-playbook.md`, plan `docs/superpowers/plans/2026-06-20-python-solver-rust-rule-engine-plan.md`.",
    "function": "Pulls the **actual files a production column-gen solver run produced** (not a reconstruction) into `ro-engine/baseline/scenario-<N>/`, mirroring `ro-engine/baseline/scenario-6/`. The prize is the **C++ rule-engine evidence** (`logs/rule.log` + `output_rules.txt`) — the oracle the Rust legality port must reproduce. Background: `docs/modules/ro-engine/solver-playbook.md`, plan `docs/superpowers/plans/2026-06-20-python-solver-rust-rule-engine-plan.md`.",
    "howToUse": "A run reaches the server one of two ways. Check both: - **Direct `run_pipeline.sh`** → `…/rostering_algorithm/PBS_column_based_algorithm/data/<N>_<ts>/` (this is where `scenario-6` came from). - **engine-server LegacyRO** (the gantt UI / API path) → workspace `…/engine-server/workspace/F8/LegacyRO_<N>_<ts>_<taskid>/`, archived on completion to `…/engine-server/complete/F8/<N>/`. Confirm via `tail engine-server/logs/app.log` (look for `scenarioId=<N> status=DONE` + `归档到 …/complete/F8/<N>`). engine-server lives at `/home/yuan.z/rois/rois-ai/engine-server` (uvicorn :3003). If nothing matches the scenario id, **say so** — don't fabrica...",
    "resources": [
      "dir:agents"
    ],
    "sourcePath": ".agents/skills/103-capture-ro-solver-baseline/SKILL.md"
  },
  {
    "name": "104-run-pbs-solver-local",
    "folder": "104-run-pbs-solver-local",
    "number": 104,
    "title": "Run the PBS solver locally (macOS)",
    "description": "Run the PBS column-gen RO solver locally on macOS (the env that hosts the Python→Rust rule-engine connector). Use when the user wants to kick off a solver run locally, set up / fix the local solver venv, or run a scenario through the pbs-engine submodule without the remote CoreServer.",
    "overview": "pbs-engine submodule: `pbs-engine/`. This is the local env for building/validating the Rust legality connector. Pairs with `103-capture-ro-solver-baseline` (remote baselines) and the scenario-537 parity oracle.",
    "function": "pbs-engine submodule: `pbs-engine/`. This is the local env for building/validating the Rust legality connector. Pairs with `103-capture-ro-solver-baseline` (remote baselines) and the scenario-537 parity oracle.",
    "howToUse": "pbs-engine submodule: `pbs-engine/`. This is the local env for building/validating the Rust legality connector. Pairs with `103-capture-ro-solver-baseline` (remote baselines) and the scenario-537 parity oracle.",
    "resources": [
      "dir:agents"
    ],
    "sourcePath": ".agents/skills/104-run-pbs-solver-local/SKILL.md"
  },
  {
    "name": "105-compare-ruleset-params",
    "folder": "105-compare-ruleset-params",
    "number": 105,
    "title": "Compare legality ruleset params across stores",
    "description": "Compare the 14 F8 legality rule parameters across the three stores — C++/MySQL (rule_parameter rows), Rust/PG (rule.param_json jsonb), and a baked ro_input_rule.txt — to verify the Rust ruleset can faithfully reproduce the C++ ro_input. Use when building/validating the Python→Rust rule-engine connector or when \"send our rules to ro_input\" parity is in question.",
    "overview": "Three representations of the same 14 F8 rules must agree for the Rust connector to reproduce C++ legality. See memories [[mysql-rule-source-to-ro-input]], [[pg-rust-ruleset-103-vs-cpp-parity]].",
    "function": "Three representations of the same 14 F8 rules must agree for the Rust connector to reproduce C++ legality. See memories [[mysql-rule-source-to-ro-input]], [[pg-rust-ruleset-103-vs-cpp-parity]].",
    "howToUse": "Compare the 14 F8 legality rule parameters across the three stores — C++/MySQL (rule_parameter rows), Rust/PG (rule.param_json jsonb), and a baked ro_input_rule.txt — to verify the Rust ruleset can faithfully reproduce the C++ ro_input. Use when building/validating the Python→Rust rule-engine connector or when \"send our rules to ro_input\" parity is in question.",
    "resources": [
      "dir:agents"
    ],
    "sourcePath": ".agents/skills/105-compare-ruleset-params/SKILL.md"
  },
  {
    "name": "106-build-run-rust-solver-connector",
    "folder": "106-build-run-rust-solver-connector",
    "number": 106,
    "title": "Build & run the Rust↔PBS-solver connector (PyO3), locally on macOS",
    "description": "Build and run the PyO3 connector that exposes the Rust rule engine (rule-engine-rs) to the PBS solver in-process, locally on macOS. Use when scaffolding/iterating the rois_rule_engine_rs extension module, running its pytest, or wiring real rule kernels into Engine.check_line as part of the python-solver↔rust-rule-engine plan.",
    "overview": "The connector makes the PBS column-gen solver call the Rust `rois_rule_engine` for legality in-process (replacing the loose Python prefilter / fragile C++ path). Plan: `docs/superpowers/plans/2026-06-20-python-solver-rust-rule-engine-plan.md`. Background: `docs/modules/ro-engine/solver-playbook.md` §5–§9. Memory [[ro-solver-legality-seam]].",
    "function": "The connector makes the PBS column-gen solver call the Rust `rois_rule_engine` for legality in-process (replacing the loose Python prefilter / fragile C++ path). Plan: `docs/superpowers/plans/2026-06-20-python-solver-rust-rule-engine-plan.md`. Background: `docs/modules/ro-engine/solver-playbook.md` §5–§9. Memory [[ro-solver-legality-seam]].",
    "howToUse": "The connector makes the PBS column-gen solver call the Rust `rois_rule_engine` for legality in-process (replacing the loose Python prefilter / fragile C++ path). Plan: `docs/superpowers/plans/2026-06-20-python-solver-rust-rule-engine-plan.md`. Background: `docs/modules/ro-engine/solver-playbook.md` §5–§9. Memory [[ro-solver-legality-seam]].",
    "resources": [
      "dir:agents"
    ],
    "sourcePath": ".agents/skills/106-build-run-rust-solver-connector/SKILL.md"
  },
  {
    "name": "107-pbs-portal-pairing-search-debug",
    "folder": "107-pbs-portal-pairing-search-debug",
    "number": 107,
    "title": "Purpose",
    "description": "Use when debugging PBS portal pairing search issues, pool counts, rank/base/RP filters, or pairing-search E2E failures.",
    "overview": "Debug and fix issues in the PBS portal pairing search feature: pool counts panel errors, wrong pairing counts, rank/base/RP filter issues.",
    "function": "Debug and fix issues in the PBS portal pairing search feature: pool counts panel errors, wrong pairing counts, rank/base/RP filter issues.",
    "howToUse": "- \"Try refresh again\": POST `/api/pairing-search/current-rules/counts` → check status code - 404 = wrong server on 3002 - 422 = unimplemented property code - 500 = check pbs-server logs; may be bad bid value format - Count too high (e.g., 14202 = raw total): rank/base/RP filter not applied → check correct server - Count seems wrong for month: check what `periodCode` the client is sending; verify `roster_period.pbs_*` has an open window if not using current month - Count is 0 with valid properties: `pairing_composition` may not have the user's rank; `pbs_user.rank` may be null",
    "resources": [
      "dir:agents"
    ],
    "sourcePath": ".agents/skills/107-pbs-portal-pairing-search-debug/SKILL.md"
  },
  {
    "name": "108-npbs-bids-portal-simulation",
    "folder": "108-npbs-bids-portal-simulation",
    "number": 108,
    "title": "NPBS-Legend Bids → Portal Crew-Bids Playwright Simulation",
    "description": "Use when mapping legacy NPBS-Legend crew bids (CLASS-BidsReport_*.txt) onto our pbs-portal bid properties, or when running/extending the Playwright simulation that logs in as each crew and replays their bids through the real portal UI. Also covers the R'Bot \"create crew bids\"/\"add bids\" chat trigger that spawns this simulation headed. Triggers on \"NPBS bids\", \"legend bids\", \"crew bids report\", \"replay crew bids\", \"bid simulation\", \"create crew bids\", \"add bids\", or extending the test to more crew/bases/ranks/months.",
    "overview": "Convert a legacy **NPBS-Legend** bids export into our **pbs-portal** bid properties, then drive the real portal UI as each crew (login → open bid page → configure dialog → set tier → ADD BID → assert the row lands). Used to test portal bidding against realistic, production-shaped bid data. **Project rule #7 (hard):** never change product code to make a bid fit. Unmappable predicates and any Playwright/login/UI blocker are *recorded*, not forced. **Project rule #8 (hard — ALWAYS):** after every simulation run (direct or R'Bot-driven), generate the MS Word report. The run is not done until the `.docx` exists: node e2e/utils/npbs/gene...",
    "function": "Convert a legacy **NPBS-Legend** bids export into our **pbs-portal** bid properties, then drive the real portal UI as each crew (login → open bid page → configure dialog → set tier → ADD BID → assert the row lands). Used to test portal bidding against realistic, production-shaped bid data. **Project rule #7 (hard):** never change product code to make a bid fit. Unmappable predicates and any Playwright/login/UI blocker are *recorded*, not forced. **Project rule #8 (hard — ALWAYS):** after every simulation run (direct or R'Bot-driven), generate the MS Word report. The run is not done until the `.docx` exists: node e2e/utils/npbs/gene...",
    "howToUse": "cd e2e && npx playwright test --config=config/playwright.config.ts --project=pbs-portal \\ --no-deps npbs-crew-bids-simulation.spec.ts --workers=1 --reporter=list **Extend to more crew/bases/ranks:** edit `BUCKETS`/`perBucket`/`minProps` in `generate-fixture.mjs`, regenerate, re-run. The spec is data-driven — no test-code change needed. **New month export:** point the generator at the new `.txt`; adjust the `shiftDates` target if the sample month differs from the live target month.",
    "resources": [
      "dir:agents"
    ],
    "sourcePath": ".agents/skills/108-npbs-bids-portal-simulation/SKILL.md"
  },
  {
    "name": "109-ui-kickoff-local-rust-solver",
    "folder": "109-ui-kickoff-local-rust-solver",
    "number": 109,
    "title": "UI kick-off → local Rust solver run (end-to-end)",
    "description": "Kick off a full local RO solver run from the REAL gantt UI (Playwright) that builds ro_input from PG and runs the pbs-engine solver with the in-process Rust rule connector (mode=rust), end-to-end. Use when testing the UI→ro_input→Rust-solver→roster pipeline locally, or e2e-testing a long synchronous optimizer /run.",
    "overview": "Drive the whole pipeline from a real \"Kick off run\" click: gantt UI (scenario-run-btn) → live-server POST /api/scenario/:id/run (type=LegacyRO, inputSource=db) → engine-server LegacyRO task → F8/ro_input_builder builds ro_input.txt/input.gz from REMOTE PG (no MySQL) → F8/ro_rust.sh: input.gz → pbs-engine solver (rule_engine.mode=rust) → Rust connector rois_rule_engine_rs → ro_output.txt → output.gz → scenario status DRAFT→RUNNING→DONE Builds on skills [104] (run solver local), [106] (Rust connector). Pairs with the ro_input_builder under `engine-server/F8/ro_input_builder/`.",
    "function": "Drive the whole pipeline from a real \"Kick off run\" click: gantt UI (scenario-run-btn) → live-server POST /api/scenario/:id/run (type=LegacyRO, inputSource=db) → engine-server LegacyRO task → F8/ro_input_builder builds ro_input.txt/input.gz from REMOTE PG (no MySQL) → F8/ro_rust.sh: input.gz → pbs-engine solver (rule_engine.mode=rust) → Rust connector rois_rule_engine_rs → ro_output.txt → output.gz → scenario status DRAFT→RUNNING→DONE Builds on skills [104] (run solver local), [106] (Rust connector). Pairs with the ro_input_builder under `engine-server/F8/ro_input_builder/`.",
    "howToUse": "Drive the whole pipeline from a real \"Kick off run\" click: gantt UI (scenario-run-btn) → live-server POST /api/scenario/:id/run (type=LegacyRO, inputSource=db) → engine-server LegacyRO task → F8/ro_input_builder builds ro_input.txt/input.gz from REMOTE PG (no MySQL) → F8/ro_rust.sh: input.gz → pbs-engine solver (rule_engine.mode=rust) → Rust connector rois_rule_engine_rs → ro_output.txt → output.gz → scenario status DRAFT→RUNNING→DONE Builds on skills [104] (run solver local), [106] (Rust connector). Pairs with the ro_input_builder under `engine-server/F8/ro_input_builder/`.",
    "resources": [
      "dir:agents"
    ],
    "sourcePath": ".agents/skills/109-ui-kickoff-local-rust-solver/SKILL.md"
  },
  {
    "name": "110-rule-param-recheck-alert-center-count",
    "folder": "110-rule-param-recheck-alert-center-count",
    "number": 110,
    "title": "Rule param change → scoped recheck → Alert Center count (end-to-end)",
    "description": "End-to-end Playwright pattern — change a legality rule's param, fire a scoped live recheck, reopen the gantt, and READ the per-rule violation count off the Alert Center group badge (not the canvas bell). Use to prove \"param change → recompute → reopen → see new violations\" for any wired rule (8002/8056/8030/8004/7501/7503/7504/7505/7506), or as the recipe for any rule-param before/after count comparison.",
    "overview": "Prove the live legality loop through the real UI/stack: PATCH /api/legality/rule/:id/params (change one row's value) → POST /api/legality/recheck {ruleCodes:['8002']} (SCOPED per-rule, the perf fix) → live-legality.mjs recomputes only that rule over the window → rewrites rule_violation → reopen gantt → Alert Center → group by Rule → read the \"<code>/<inst>\" count badge Worked example committed: `e2e/tests/gantt/legality-recheck-8002-count-compare.spec.ts` (**Viol-8011**: 59h cap → 19 msgs vs 100h cap → 0 msgs; tighter cap ⇒ strictly more). Companion: `legality-recheck-8002-user-story.spec.ts` (Viol-8010, message-text assertion).",
    "function": "Prove the live legality loop through the real UI/stack: PATCH /api/legality/rule/:id/params (change one row's value) → POST /api/legality/recheck {ruleCodes:['8002']} (SCOPED per-rule, the perf fix) → live-legality.mjs recomputes only that rule over the window → rewrites rule_violation → reopen gantt → Alert Center → group by Rule → read the \"<code>/<inst>\" count badge Worked example committed: `e2e/tests/gantt/legality-recheck-8002-count-compare.spec.ts` (**Viol-8011**: 59h cap → 19 msgs vs 100h cap → 0 msgs; tighter cap ⇒ strictly more). Companion: `legality-recheck-8002-user-story.spec.ts` (Viol-8010, message-text assertion).",
    "howToUse": "- **Shared redis client can wedge.** The live-server uses ONE `fastify.redis` client. After a long heavy session it can get stuck: every `get`/`set` hangs forever (no command timeout) while Redis itself is healthy. Symptom: `/api/health` + `/api/auth/login` (DB-only) return instantly, but `/api/legality/recheck-status` and POST `/recheck` (redis ops) hang → POST times out at 60s. Fix: **restart live-server** (`touch live-server/src/index.ts` triggers tsx-watch reload), then poll `recheck-status` until HTTP 200. websocket pSubscribe uses a *duplicated* client (`websocket.ts:120`), so that's not the cause — it's just a stale/half-ope...",
    "resources": [
      "dir:agents"
    ],
    "sourcePath": ".agents/skills/110-rule-param-recheck-alert-center-count/SKILL.md"
  },
  {
    "name": "111-pbs-solver-roster-deassign",
    "folder": "111-pbs-solver-roster-deassign",
    "number": 111,
    "title": "PBS Solver Roster De-assignment (PA removal) + Crew Memo",
    "description": "Visualize and execute PBS-solver pre-assignment (PA) removal — the read-only de-assignment analysis that marks each to-be-removed crew duty (flying pairings + days off) with a crew-memo note icon on the live gantt, the planner confirms/corrects, then an explicit order soft-deletes the approved rosters. Use when the user says \"remove pre-assignment (PA) for solver\", \"mark to-be-de-assigned duties\", \"crew memo\", \"memo icon\", or wants to clear crew duties to make room for the PBS solver; or when extending the crew-memo CRUD / classifier / R'Bot prepare_pa_removal tool.",
    "overview": "The 3-stage, human-in-the-loop pipeline to clear crew duties for the PBS solver. Memos are the shared artifact between R'Bot's proposal and the real mutation. 1. **Bot visualizes** — `POST /api/crew-memo/pa-removal` runs the read-only classifier and writes one `type=3` memo per to-be-de-assigned duty. Opening the live gantt shows a yellow sticky-note icon on each affected puck. 2. **Planner confirms/corrects** — edit the memos (right-click a duty → Add/Edit/Delete Memo). Surviving `type=3` `status='Y'` memos ARE the approved plan. 3. **Execute (explicit order)** — `POST /api/crew-memo/pa-removal/execute` soft-deletes (`is_deleted=1...",
    "function": "The 3-stage, human-in-the-loop pipeline to clear crew duties for the PBS solver. Memos are the shared artifact between R'Bot's proposal and the real mutation. 1. **Bot visualizes** — `POST /api/crew-memo/pa-removal` runs the read-only classifier and writes one `type=3` memo per to-be-de-assigned duty. Opening the live gantt shows a yellow sticky-note icon on each affected puck. 2. **Planner confirms/corrects** — edit the memos (right-click a duty → Add/Edit/Delete Memo). Surviving `type=3` `status='Y'` memos ARE the approved plan. 3. **Execute (explicit order)** — `POST /api/crew-memo/pa-removal/execute` soft-deletes (`is_deleted=1...",
    "howToUse": "Visualize and execute PBS-solver pre-assignment (PA) removal — the read-only de-assignment analysis that marks each to-be-removed crew duty (flying pairings + days off) with a crew-memo note icon on the live gantt, the planner confirms/corrects, then an explicit order soft-deletes the approved rosters. Use when the user says \"remove pre-assignment (PA) for solver\", \"mark to-be-de-assigned duties\", \"crew memo\", \"memo icon\", or wants to clear crew duties to make room for the PBS solver; or when extending the crew-memo CRUD / classifier / R'Bot prepare_pa_removal tool.",
    "resources": [
      "dir:agents"
    ],
    "sourcePath": ".agents/skills/111-pbs-solver-roster-deassign/SKILL.md"
  },
  {
    "name": "112-dora-report",
    "folder": "112-dora-report",
    "number": 112,
    "title": "Purpose",
    "description": "Generate a DORA developer performance analysis report for the ROIS-AI Ver4 project. Analyzes git history to compute Deployment Frequency, Lead Time, Change Failure Rate, MTTR proxies, module ownership, Playwright/doc contributions, weekly velocity trend, AI-assisted-development rate, and code hotspots — per developer. Always outputs BOTH a Chinese (CN) AND English (EN) .docx report to docs/dev-context/. Triggered when the user says \"create DORA report\", \"生成 DORA 报告\", \"latest dora\", \"update DORA\", or references a prior dora-developer-analysis .docx file.",
    "overview": "Generate a DORA metrics report that matches the project's existing reports in `docs/dev-context/*-dora-developer-analysis-*-Vx.docx`. The most recent baseline format is **V6** (13 sections). A self-contained generator does all the work: `gen_dora_report.py` (next to this file).",
    "function": "Generate a DORA metrics report that matches the project's existing reports in `docs/dev-context/*-dora-developer-analysis-*-Vx.docx`. The most recent baseline format is **V6** (13 sections). A self-contained generator does all the work: `gen_dora_report.py` (next to this file).",
    "howToUse": "From the **repo root** (so `git log` and `gantt/src/version.ts` resolve): python3 ~/.claude/skills/112-dora-report/gen_dora_report.py This auto-increments the version (scans `docs/dev-context/` for the highest `-Vx`), reads `Ver:B/F/R` from `gantt/src/version.ts`, collects all metrics from git, and writes **both** language files: docs/dev-context/YYYY-MM-DD HHMM-dora-developer-analysis-CN-Vx.docx docs/dev-context/YYYY-MM-DD HHMM-dora-developer-analysis-EN-Vx.docx Options: - `--version V8` — force a version number (otherwise auto = highest existing + 1) - `--since 2026-01-01` — analysis start date (default 2026-01-01) - `--date 2026...",
    "resources": [
      "dir:agents",
      "file:gen_dora_report.py"
    ],
    "sourcePath": ".agents/skills/112-dora-report/SKILL.md"
  },
  {
    "name": "113-scenario-roster-quality-analyzer",
    "folder": "113-scenario-roster-quality-analyzer",
    "number": 113,
    "title": "Scenario Roster Quality Analyzer",
    "description": "Build/extend the SCENARIO-only Roster Quality Analyzer in the gantt — a roster-pane toolbar button that opens a per-crew quality table (lead-in / pre-assignment / solver credit + extensible quality findings such as standalone RES), computed client-side from the loaded optimization result. Use when adding quality criteria, touching the analyzer dialog/button, or wiring a new scenario-only roster-pane action behind an optional source hook.",
    "overview": "A scenario-only roster-pane toolbar button → popup table, one row per loaded crew. Added 2026-06-21 (branch `feat/gantt/crew-memo-pa-removal`, FRONTEND_VERSION 292). Surfaces roster quality after an optimization result returns.",
    "function": "Crew ID (clickable → float to top) · Base/Rank · **Lead-in CRD** · **Awarded credit** (stacked Before opt / After opt) · **Quality** (findings list). A check-standard description block sits above the table (testid `quality-analysis-standards`) explaining the criteria. Credit partition (from `ScenarioGanttData`, by `source`): - **Lead-in CRD** = `groundItems` where `source='PA'` → `actCreditedMinutes`. - **Awarded credit / Before opt** (`quality-preassign`) = pairings assigned `source='PA'` → Σ duty credit (dedupe by dutySeq) = pre-assignment credit. - **Awarded credit / After opt** (`quality-solver`) = pairings with `source='CR'` →...",
    "howToUse": "Build/extend the SCENARIO-only Roster Quality Analyzer in the gantt — a roster-pane toolbar button that opens a per-crew quality table (lead-in / pre-assignment / solver credit + extensible quality findings such as standalone RES), computed client-side from the loaded optimization result. Use when adding quality criteria, touching the analyzer dialog/button, or wiring a new scenario-only roster-pane action behind an optional source hook.",
    "resources": [
      "dir:agents"
    ],
    "sourcePath": ".agents/skills/113-scenario-roster-quality-analyzer/SKILL.md"
  },
  {
    "name": "114-scenario-rust-solver-run-report",
    "folder": "114-scenario-rust-solver-run-report",
    "number": 114,
    "title": "Scenario Rust-solver run + Word report",
    "description": "Drive a full end-to-end PBS Rust-solver optimization run for a scenario through the REAL gantt UI (find scenario → kick off run → wait for DONE → open gantt to view result), monitor backend material generation, then emit a Word (.docx) summary report (scenario basics, crew/pairing scale, flying/standby/DO assignments, Rust + solver run time, coverage). Use when asked to \"kick off a run for scenario N and report it\", validate the scenario→engine→Rust-solver pipeline, or produce a run summary document.",
    "overview": "End-to-end, user-simulated optimization run of a scenario, plus a `.docx` summary. This packages the flow proven on **scenario 539 (\"YYZ RUST Seam Connector\")**. Pipeline exercised: gantt UI *Kick off run* → live-server `POST /api/optimize/start` (LegacyRO, inputSource=db) → engine-server builds `ro_input` from remote PG (`F8.ro_input_builder`) → fetches the **scenario-scoped** bid package from pbs-server (`/api/admin/algorithm-export/scenario-package`, PAIRING_SCORE narrowed by date±7d / base / per-crew rank) → `F8/ro_rust.sh` pbs-engine solver (`rule_engine.mode=rust`) → in-process Rust rule connector (`rois_rule_engine_rs`, para...",
    "function": "End-to-end, user-simulated optimization run of a scenario, plus a `.docx` summary. This packages the flow proven on **scenario 539 (\"YYZ RUST Seam Connector\")**. Pipeline exercised: gantt UI *Kick off run* → live-server `POST /api/optimize/start` (LegacyRO, inputSource=db) → engine-server builds `ro_input` from remote PG (`F8.ro_input_builder`) → fetches the **scenario-scoped** bid package from pbs-server (`/api/admin/algorithm-export/scenario-package`, PAIRING_SCORE narrowed by date±7d / base / per-crew rank) → `F8/ro_rust.sh` pbs-engine solver (`rule_engine.mode=rust`) → in-process Rust rule connector (`rois_rule_engine_rs`, para...",
    "howToUse": "End-to-end, user-simulated optimization run of a scenario, plus a `.docx` summary. This packages the flow proven on **scenario 539 (\"YYZ RUST Seam Connector\")**. Pipeline exercised: gantt UI *Kick off run* → live-server `POST /api/optimize/start` (LegacyRO, inputSource=db) → engine-server builds `ro_input` from remote PG (`F8.ro_input_builder`) → fetches the **scenario-scoped** bid package from pbs-server (`/api/admin/algorithm-export/scenario-package`, PAIRING_SCORE narrowed by date±7d / base / per-crew rank) → `F8/ro_rust.sh` pbs-engine solver (`rule_engine.mode=rust`) → in-process Rust rule connector (`rois_rule_engine_rs`, para...",
    "resources": [
      "dir:agents",
      "dir:scripts"
    ],
    "sourcePath": ".agents/skills/114-scenario-rust-solver-run-report/SKILL.md"
  },
  {
    "name": "115-gantt-playbook",
    "folder": "115-gantt-playbook",
    "number": 115,
    "title": "Gantt Playbook",
    "description": "Use when the user says \"gantt playbook\", or before starting ANY Live/Scenario gantt feature or gantt debugging task. Loads the canonical Live/Scenario Gantt reference (architecture, shared source layer, stores, panes, data model, filters, capabilities, backend endpoints, gotchas) so you work from accumulated knowledge instead of re-deriving it.",
    "overview": "When this skill is invoked (or the user says \"gantt playbook\"): 1. **Read the full playbook first**, before touching any gantt code: `docs/modules/gantt/live-scenario-gantt-playbook.md` (repo: ROIs-Crew-Ver4-PBS). This is the single canonical reference accumulating all Live + Scenario gantt knowledge: the §Gantt-Unify one-code-path principle, the source-abstraction layer (`gantt/src/components/gantt/source/*`), the per-context store registry, shared pane components + column system, the gantt data model + type shapes, Live vs Scenario backend endpoints, filters/sort/ coverage, capabilities, the e2e harness, and hard-won gotchas. 2....",
    "function": "When this skill is invoked (or the user says \"gantt playbook\"): 1. **Read the full playbook first**, before touching any gantt code: `docs/modules/gantt/live-scenario-gantt-playbook.md` (repo: ROIs-Crew-Ver4-PBS). This is the single canonical reference accumulating all Live + Scenario gantt knowledge: the §Gantt-Unify one-code-path principle, the source-abstraction layer (`gantt/src/components/gantt/source/*`), the per-context store registry, shared pane components + column system, the gantt data model + type shapes, Live vs Scenario backend endpoints, filters/sort/ coverage, capabilities, the e2e harness, and hard-won gotchas. 2....",
    "howToUse": "Use when the user says \"gantt playbook\", or before starting ANY Live/Scenario gantt feature or gantt debugging task. Loads the canonical Live/Scenario Gantt reference (architecture, shared source layer, stores, panes, data model, filters, capabilities, backend endpoints, gotchas) so you work from accumulated knowledge instead of re-deriving it.",
    "resources": [
      "dir:agents"
    ],
    "sourcePath": ".agents/skills/115-gantt-playbook/SKILL.md"
  },
  {
    "name": "116-scenario-division-scoping",
    "folder": "116-scenario-division-scoping",
    "number": 116,
    "title": "Scenario division scoping (pilot vs cabin) — debug & fix recipe",
    "description": "Use when a Scenario Gantt shows data from the wrong crew division (e.g. a pilot/FC scenario leaking cabin IFD/FA pairings), or when scoping scenario pairings/crew by division. Maps the THREE backend pairing-sourcing sites and the shared pairing-pane layer.",
    "overview": "A scenario belongs to one division (`P`=pilot/flight-crew, `C`=cabin, `A`=ATC). Crew is division-scoped, but **pairings historically were not** — so a pilot scenario could leak cabin pairings (composition ranks `IFD`/`FA`). Scoping must be applied at **three** backend sites, because a scenario can be served by different paths (`SCENARIO_GANTT_SOURCE` = `db` default | `gz`).",
    "function": "A scenario belongs to one division (`P`=pilot/flight-crew, `C`=cabin, `A`=ATC). Crew is division-scoped, but **pairings historically were not** — so a pilot scenario could leak cabin pairings (composition ranks `IFD`/`FA`). Scoping must be applied at **three** backend sites, because a scenario can be served by different paths (`SCENARIO_GANTT_SOURCE` = `db` default | `gz`).",
    "howToUse": "Use when a Scenario Gantt shows data from the wrong crew division (e.g. a pilot/FC scenario leaking cabin IFD/FA pairings), or when scoping scenario pairings/crew by division. Maps the THREE backend pairing-sourcing sites and the shared pairing-pane layer.",
    "resources": [
      "dir:agents"
    ],
    "sourcePath": ".agents/skills/116-scenario-division-scoping/SKILL.md"
  },
  {
    "name": "117-playwright-live-stream",
    "folder": "117-playwright-live-stream",
    "number": 117,
    "title": "Playwright Live Stream — watch a headed run from another PC",
    "description": "Use when watching a headed Playwright run (e.g. R'Bot's create_crew_bids) live from another PC, or when extending the universal \"Playwright Live Stream\" subsystem (producer fixture → ai-server relay → full-page viewer). Triggers on \"watch the browser\", \"live stream playwright\", \"watch the run\", \"view the headed browser remotely\", or adding a new streamed consumer.",
    "overview": "R'Bot's ai-server runs the **headed browser on the ai-server host**, not on the PC where the user typed into chat. This subsystem streams the browser's frames to a full-page viewer the user opens from the chat reply, so they can watch from anywhere. **Universal:** crew-bids is the first consumer; any Playwright job plugs in with ~3 lines. Key fact (answers the common confusion): a `--headed` run launched by R'Bot/ai-server opens its Chromium window **on the ai-server machine** (verify: `ps -axo pid,ppid,command | grep playwright` — its ppid is the `com.rois.ai-server` LaunchAgent). The user's chat PC only sends an HTTP request. \"he...",
    "function": "PRODUCER (e2e/utils/live-stream) RELAY (ai-server/src/live) VIEWER (served by relay) test.ts = base.extend(context) registry.py StreamHub viewer.py VIEWER_HTML live-stream.ts attachLiveStream() routes.py: full-page <canvas>, frame-sink.ts createFrameSink() POST /ai/live/streams {id,token} derives WS path from • env-gated by PW_STREAM_URL WS {id}/ingest (producer in) its own /watch URL • CDP Page.startScreencast ──► WS {id}/stream?token (viewer out)──► (proxy-prefix safe) • best-effort: drops/never stalls GET {id}/watch?token (HTML) GET /ai/live/streams (list)",
    "howToUse": "R'Bot's ai-server runs the **headed browser on the ai-server host**, not on the PC where the user typed into chat. This subsystem streams the browser's frames to a full-page viewer the user opens from the chat reply, so they can watch from anywhere. **Universal:** crew-bids is the first consumer; any Playwright job plugs in with ~3 lines. Key fact (answers the common confusion): a `--headed` run launched by R'Bot/ai-server opens its Chromium window **on the ai-server machine** (verify: `ps -axo pid,ppid,command | grep playwright` — its ppid is the `com.rois.ai-server` LaunchAgent). The user's chat PC only sends an HTTP request. \"he...",
    "resources": [
      "dir:agents"
    ],
    "sourcePath": ".agents/skills/117-playwright-live-stream/SKILL.md"
  },
  {
    "name": "118-live-server-perf-observability",
    "folder": "118-live-server-perf-observability",
    "number": 118,
    "title": "Live Server Performance & Observability",
    "description": "Add performance + observability to live-server (port 3000) hot Gantt/legality paths without breaking existing behavior — Prometheus route/cache metrics, versioned cache keys (INCR vs SCAN), additive lightweight list modes, recheck status-meta. Use when optimizing live-server latency/DB-load/payload, adding metrics, or executing the live-server performance enhancement plan. Also captures the iCloud-worktree workflow this repo requires.",
    "overview": "Patterns proven implementing `docs/superpowers/plans/2026-06-22-0628-live-server-performance-enhancement-ver1.md` (committed to `main`: 5451e67a, 83e0dc2a, bf1f7915, 3e8b6324, 1b169681). Completion note: `docs/superpowers/completed/2026-06-22-live-server-performance-enhancement-ver1-completion.md`.",
    "function": "Patterns proven implementing `docs/superpowers/plans/2026-06-22-0628-live-server-performance-enhancement-ver1.md` (committed to `main`: 5451e67a, 83e0dc2a, bf1f7915, 3e8b6324, 1b169681). Completion note: `docs/superpowers/completed/2026-06-22-live-server-performance-enhancement-ver1-completion.md`.",
    "howToUse": "Add performance + observability to live-server (port 3000) hot Gantt/legality paths without breaking existing behavior — Prometheus route/cache metrics, versioned cache keys (INCR vs SCAN), additive lightweight list modes, recheck status-meta. Use when optimizing live-server latency/DB-load/payload, adding metrics, or executing the live-server performance enhancement plan. Also captures the iCloud-worktree workflow this repo requires.",
    "resources": [
      "dir:agents"
    ],
    "sourcePath": ".agents/skills/118-live-server-perf-observability/SKILL.md"
  },
  {
    "name": "119-pbs-overseas-speed-latency",
    "folder": "119-pbs-overseas-speed-latency",
    "number": 119,
    "title": "PBS Overseas Speed & Latency",
    "description": "Reduce overseas perceived latency for pbs-server (Fastify, :3002) and pbs-portal (React/Vite/TanStack Query) — response compression, low-cardinality route metrics, private ETags on stable GETs, a combined /portal/bootstrap endpoint, portal-layout prefetch, and a byte-aware perf baseline. Use when optimizing PBS transfer size / round trips / unmeasured backend latency, or when adding/maintaining any of those pieces. Also the canonical reference for how to write+run pbs-server (node:test) and pbs-portal (vitest) tests in THIS repo, including the environment gotchas that block them.",
    "overview": "Implements the plan `docs/superpowers/plans/2026-06-22-0829-pbs-overseas-speed-latency.md`. Goal: fewer round trips + smaller payloads + measured latency for overseas PBS users, without changing the `{ code, data, message }` contract.",
    "function": "1. **Compression** — `@fastify/compress` (gzip, threshold 1024) registered in `pbs-server/src/app.ts` after security headers, before routes. 2. **Route metrics** — `observePbsHttpResponse` in `pbs-server/src/plugins/metrics.ts` (two Histograms: `rois_pbs_server_http_request_duration_seconds`, `rois_pbs_server_http_response_bytes`). Wired from the existing `onResponse` hook in `app.ts`. **Labels = method, matched route template (`request.routeOptions.url`), status_code ONLY.** Never label with raw `request.url` (query strings) / ids / tokens. 3. **Private ETags** — `pbs-server/src/utils/private-etag.ts` `sendPrivateJsonWithEtag(req,...",
    "howToUse": "Reduce overseas perceived latency for pbs-server (Fastify, :3002) and pbs-portal (React/Vite/TanStack Query) — response compression, low-cardinality route metrics, private ETags on stable GETs, a combined /portal/bootstrap endpoint, portal-layout prefetch, and a byte-aware perf baseline. Use when optimizing PBS transfer size / round trips / unmeasured backend latency, or when adding/maintaining any of those pieces. Also the canonical reference for how to write+run pbs-server (node:test) and pbs-portal (vitest) tests in THIS repo, including the environment gotchas that block them.",
    "resources": [
      "dir:agents"
    ],
    "sourcePath": ".agents/skills/119-pbs-overseas-speed-latency/SKILL.md"
  },
  {
    "name": "120-pbs-pairing-search-perf",
    "folder": "120-pbs-pairing-search-perf",
    "number": 120,
    "title": "PBS Pairing-Search Hot-Path Performance",
    "description": "Optimize the pbs-server (:3002) interactive pairing-search hot path against the live pairing/pairing_segment tables — the missing base+period index, the non-sargable period predicate, and the per-row ×3 correlated segment subqueries. Use when the PBS pairing bid page / Pairing-Number autocomplete / SEARCH preview / pool counts / airport-options feels slow, or when adding/validating these query rewrites. Also the canonical recipe for proving a live-SQL rewrite byte-identical against the remote demo DB + EXPLAIN before/after.",
    "overview": "Shipped to `main` @ `7a5bf3ed` (PBS Ver **B10**). Implements `docs/handoff/pbs/pairing-search-perf-improvement-handoff.md` (+ analysis `docs/modules/pbs/pairing-page-slow-load-perf-analysis.md`).",
    "function": "Shipped to `main` @ `7a5bf3ed` (PBS Ver **B10**). Implements `docs/handoff/pbs/pairing-search-perf-improvement-handoff.md` (+ analysis `docs/modules/pbs/pairing-page-slow-load-perf-analysis.md`).",
    "howToUse": "Optimize the pbs-server (:3002) interactive pairing-search hot path against the live pairing/pairing_segment tables — the missing base+period index, the non-sargable period predicate, and the per-row ×3 correlated segment subqueries. Use when the PBS pairing bid page / Pairing-Number autocomplete / SEARCH preview / pool counts / airport-options feels slow, or when adding/validating these query rewrites. Also the canonical recipe for proving a live-SQL rewrite byte-identical against the remote demo DB + EXPLAIN before/after.",
    "resources": [
      "dir:agents"
    ],
    "sourcePath": ".agents/skills/120-pbs-pairing-search-perf/SKILL.md"
  },
  {
    "name": "121-pbs-perf-enhancement",
    "folder": "121-pbs-perf-enhancement",
    "number": 121,
    "title": "PBS Performance Enhancement Playbook",
    "description": "Canonical playbook for PBS performance enhancement — diagnosing and fixing slow pbs-server (:3002) / pbs-portal (:3030) paths (transfer size, round trips, unmeasured backend latency, live-table query cost) without changing the {code,data,message} contract. Use when \"the PBS X page is slow\", when adding indexes/caching/query rewrites to pbs-server, or to pick the right approach + verification discipline for any PBS perf work. Umbrella over skills 119 (overseas size/latency) and 120 (pairing-search hot path).",
    "overview": "The repeatable method behind the shipped PBS perf work. For the two concrete deliverables: - **119-pbs-overseas-speed-latency** — compression, route metrics, private ETags, `/portal/bootstrap`, byte baseline. - **120-pbs-pairing-search-perf** — base+period index, sargable period range, grouped LATERAL rollup. This skill is the *method*; load 119/120 for the *recipes*.",
    "function": "The repeatable method behind the shipped PBS perf work. For the two concrete deliverables: - **119-pbs-overseas-speed-latency** — compression, route metrics, private ETags, `/portal/bootstrap`, byte baseline. - **120-pbs-pairing-search-perf** — base+period index, sargable period range, grouped LATERAL rollup. This skill is the *method*; load 119/120 for the *recipes*.",
    "howToUse": "- Remote demo DB: `pbs-server/.env` `SOURCE_DATABASE_URL` (live schema f8) / `DATABASE_URL` (f8_pbs), `47.253.173.207:55432/rois`, session TZ `Etc/UTC`. Local f8 is empty — always the remote. - **iCloud-revert hazard**: do edits in a git worktree OUTSIDE iCloud (symlink node_modules from the iCloud checkout for build/test + the pre-push UI gate), then `git push HEAD:main`. Worktree off current `origin/main`. - **Version**: bump `PBS_BACKEND_VERSION` (pbs-server) / `PBS_FRONTEND_VERSION` (pbs-portal) in `gantt/src/version.ts` — NOT the global counters. Pure DDL needs no bump; bump once when code ships. - pbs-server test env gotchas...",
    "resources": [
      "dir:agents"
    ],
    "sourcePath": ".agents/skills/121-pbs-perf-enhancement/SKILL.md"
  },
  {
    "name": "122-release-note-maker",
    "folder": "122-release-note-maker",
    "number": 122,
    "title": "Release Note Maker (gantt Release tab)",
    "description": "Generate a new gantt Release tab release note (REL_N) covering only END-USER-FACING UI changes since the last release's commit cursor. Use when the user says \"create a release note\", \"new release notes\", \"write up what changed for users\", or wants the Release tab updated. Curates user-visible changes per nav-tab area (Live/Scenario/Rule/Data/System/ Regression/Global), verifies wording against components, updates the §Stale-Test spec, and runs the proof in an iCloud-safe worktree.",
    "overview": "> **Automation**: since 2026-08, a system cron runs this weekly (Fridays 03:00 UTC = > 11:00 Beijing) via `scripts/weekly-help-release/weekly-help-release.sh` — a headless > `claude -p` that invokes this skill + `online-help-writing`, runs tests, commits, pushes, > and deploys UAT. On-demand runs still use this skill directly. The cron skips the commit > when the window has no user-facing gantt UI changes. The gantt **Release** tab (top-nav, after Help) holds hand-curated, **user-facing UI** release notes. Generation is **manual / on-demand** (unlike Help, which syncs at commit time). This skill produces the next `REL_N` and keeps...",
    "function": "> **Automation**: since 2026-08, a system cron runs this weekly (Fridays 03:00 UTC = > 11:00 Beijing) via `scripts/weekly-help-release/weekly-help-release.sh` — a headless > `claude -p` that invokes this skill + `online-help-writing`, runs tests, commits, pushes, > and deploys UAT. On-demand runs still use this skill directly. The cron skips the commit > when the window has no user-facing gantt UI changes. The gantt **Release** tab (top-nav, after Help) holds hand-curated, **user-facing UI** release notes. Generation is **manual / on-demand** (unlike Help, which syncs at commit time). This skill produces the next `REL_N` and keeps...",
    "howToUse": "- Bump `FRONTEND_VERSION +1` in `gantt/src/version.ts` (release-data.ts is gantt frontend code). - Run UI gate: `node scripts/check-ui-standard.mjs` → must be 0 hard violations. - Run the spec in the worktree against your own vite (use a UNIQUE port — 5273 may be taken by another session; testing the wrong port tests the wrong build): ( cd \"$WT/gantt\" && npx vite --port 5293 --strictPort >/tmp/vite.log 2>&1 & ) ( cd \"$WT/e2e\" && GANTT_BASE_URL=http://localhost:5293 \\ npx playwright test tests/gantt/release-tab.spec.ts --reporter=list --no-deps ) Paste the PASS summary (§No-Illusion). Note: `release-tab.spec.ts` uses absolute `${BAS...",
    "resources": [
      "dir:agents"
    ],
    "sourcePath": ".agents/skills/122-release-note-maker/SKILL.md"
  },
  {
    "name": "123-live-mcred-draft-recompute",
    "folder": "123-live-mcred-draft-recompute",
    "number": 123,
    "title": "What this is",
    "description": "Make the Live gantt roster-pane MCred (monthly credit) update in real time as the planner de-assigns / adds duties before Save (and revert on undo), plus the roadmap for authoritative server reconcile (Phase B) and cross-user live refresh (Phase C). Use when MCred / monthly-credit does not move on de-assign, when extending the optimistic credit delta, or when wiring the preview-stats endpoint or the roster-updated WS handler. Also the reference for the viewportYearMonth-vs-UTC tz trap that breaks MCred e2e.",
    "overview": "In the **Live** gantt, the roster left-panel **MCred** column is a server aggregate, not a roster sum: it's `stats.mcred` from `crew-store.crewStatsMap` (keyed `crewId:yearMonth`), fetched from `crew_manday_{fd|cc_am}_monthly.credit` via `crew-stats-service.ts`. So de-assigning a duty did **not** move MCred (not before Save, and not after — the async manday worker is eventually-consistent and `clearCrewStatsCache()` only refetches on a month-scroll). **Phase A (SHIPPED 2026-06-22, F308, branch `feat/gantt/live-mcred-draft-recompute`)** makes the displayed value `mcred = stats.mcred + draftDelta`, where `draftDelta = credit(virtual...",
    "function": "In the **Live** gantt, the roster left-panel **MCred** column is a server aggregate, not a roster sum: it's `stats.mcred` from `crew-store.crewStatsMap` (keyed `crewId:yearMonth`), fetched from `crew_manday_{fd|cc_am}_monthly.credit` via `crew-stats-service.ts`. So de-assigning a duty did **not** move MCred (not before Save, and not after — the async manday worker is eventually-consistent and `clearCrewStatsCache()` only refetches on a month-scroll). **Phase A (SHIPPED 2026-06-22, F308, branch `feat/gantt/live-mcred-draft-recompute`)** makes the displayed value `mcred = stats.mcred + draftDelta`, where `draftDelta = credit(virtual...",
    "howToUse": "Make the Live gantt roster-pane MCred (monthly credit) update in real time as the planner de-assigns / adds duties before Save (and revert on undo), plus the roadmap for authoritative server reconcile (Phase B) and cross-user live refresh (Phase C). Use when MCred / monthly-credit does not move on de-assign, when extending the optimistic credit delta, or when wiring the preview-stats endpoint or the roster-updated WS handler. Also the reference for the viewportYearMonth-vs-UTC tz trap that breaks MCred e2e.",
    "resources": [
      "dir:agents"
    ],
    "sourcePath": ".agents/skills/123-live-mcred-draft-recompute/SKILL.md"
  },
  {
    "name": "124-crew-manday-rule-tool",
    "folder": "124-crew-manday-rule-tool",
    "number": 124,
    "title": "Crew Manday + Rule Tool (ROIS-AI)",
    "description": ">-",
    "overview": "Repo: current `rois-ai` checkout. Resolve paths from the repo root; this skill may be used from Linux or macOS worktrees. \"Crew manday\" = per-crew, per-period accumulated **credit hours / block hours / day-off / annual-leave** counters, derived from each crew's roster. They feed the gantt roster-panel KPIs. The \"rule tool\" (`ruletool`) is the credit-arithmetic core that computes them. This is a navigational skill — read the canonical files below, don't re-derive. Project enforces §No-Illusion (prove it, don't claim it): verify any number against code/DB before stating.",
    "function": "Repo: current `rois-ai` checkout. Resolve paths from the repo root; this skill may be used from Linux or macOS worktrees. \"Crew manday\" = per-crew, per-period accumulated **credit hours / block hours / day-off / annual-leave** counters, derived from each crew's roster. They feed the gantt roster-panel KPIs. The \"rule tool\" (`ruletool`) is the credit-arithmetic core that computes them. This is a navigational skill — read the canonical files below, don't re-derive. Project enforces §No-Illusion (prove it, don't claim it): verify any number against code/DB before stating.",
    "howToUse": "- **Live repair after direct roster data fixes:** use the unified driver with an explicit `crewIds` scope and date window. This zeroes credit-model columns in the window first, then recomputes credit and BLH from the remaining roster rows. If the deleted rows are already gone and you did not preserve their crew IDs, build the crew scope from current window-active `roster_flight` rows so you do not miss affected crew. cd live-server set -a; source .env >/dev/null 2>&1; set +a npx tsx -e \"import pg from 'pg'; import { recompute } from './src/services/manday/manday-tool.ts'; import { liveSchemaName } from './src/utils/db-schema.ts'; v...",
    "resources": [
      "dir:agents"
    ],
    "sourcePath": ".agents/skills/124-crew-manday-rule-tool/SKILL.md"
  },
  {
    "name": "125-pbs-result-analyzer",
    "folder": "125-pbs-result-analyzer",
    "number": 125,
    "title": "Overview",
    "description": "Use when debugging a PBS / RO solver run result — a crew ended up with no flying and no RES duty (only DO / days off / blank), or any \"why did the optimizer do/not do X for this crew\" question on a finished scenario run. Walks a 5-step diagnostic ladder (scope → bids → eligibility → availability → assignment) over the real ro_input / *_SCORE.csv / result.json artifacts and gives a grounded verdict + suggestion. Triggers on \"why no flying\", \"crew only has DO\", \"crew not assigned\", \"pbs result analyzer\", \"debug solver result\", \"no pairing score\".",
    "overview": "When a planner says *\"crew X got no flying / no RES, only DO\"*, do **not** guess. Every finished RO solver run leaves complete per-crew artifacts on disk. Walk a fixed ladder against them and the cause is unambiguous. **Core principle:** the answer is always in one of five layers — and \"no flying\" is frequently *correct* (the crew is on leave), not a defect. Find which layer first, then advise.",
    "function": "When a planner says *\"crew X got no flying / no RES, only DO\"*, do **not** guess. Every finished RO solver run leaves complete per-crew artifacts on disk. Walk a fixed ladder against them and the cause is unambiguous. **Core principle:** the answer is always in one of five layers — and \"no flying\" is frequently *correct* (the crew is on leave), not a defect. Find which layer first, then advise.",
    "howToUse": "python3 .../diagnose_crew.py engine-server/complete/F8/541_20260622_202057 806 1227 The script runs all five steps per crew and prints a verdict + suggestion. Always include one **control crew that DID get flying** (e.g. `96`) so a confusing result is obvious by contrast.",
    "resources": [
      "dir:agents",
      "file:diagnose_crew.py"
    ],
    "sourcePath": ".agents/skills/125-pbs-result-analyzer/SKILL.md"
  },
  {
    "name": "126-noc-integration",
    "folder": "126-noc-integration",
    "number": 126,
    "title": "NOC Integration (ROIS-AI)",
    "description": "Canonical reference for NOC integration in ROIS-AI — how all crew/pairing/flight/roster/reserve/manday data was imported IN from the external NOC (Legend/F8) crewing source system, and the (not-yet-built) OUTBOUND requirement to export a PBS-solver-placed roster back OUT to NOC. Use when the user mentions \"NOC\", \"NOC integration\", \"NOC import/export\", \"Legend\", \"connector-server\", \"external system integration\", \"roster export to NOC\", \"publish roster to NOC\", \"F8 import\", \"interface_id\", \"F8_IMPORT origin\", or asks where imported data came from / where solver output goes. Living doc — append new NOC learnings here.",
    "overview": "> NOC = the airline's **Network Operations Control / crewing source system** (the legacy \"Legend\"/NOC client). In this repo the live demo source is exposed under the **F8** filiale / connector code. **All current crew, pairing, flight, roster, reserve and manday data was imported IN from the NOC API.** The future requirement: when the PBS solver-placed roster is ready, **export it back OUT to NOC** — that direction is **NOT BUILT yet** (see §3). > > This is a **living doc**: every time we learn something new about NOC integration (new endpoint, payload field, the day outbound export gets built, gotchas), append it here. Repo root:...",
    "function": "> NOC = the airline's **Network Operations Control / crewing source system** (the legacy \"Legend\"/NOC client). In this repo the live demo source is exposed under the **F8** filiale / connector code. **All current crew, pairing, flight, roster, reserve and manday data was imported IN from the NOC API.** The future requirement: when the PBS solver-placed roster is ready, **export it back OUT to NOC** — that direction is **NOT BUILT yet** (see §3). > > This is a **living doc**: every time we learn something new about NOC integration (new endpoint, payload field, the day outbound export gets built, gotchas), append it here. Repo root:...",
    "howToUse": "Canonical reference for NOC integration in ROIS-AI — how all crew/pairing/flight/roster/reserve/manday data was imported IN from the external NOC (Legend/F8) crewing source system, and the (not-yet-built) OUTBOUND requirement to export a PBS-solver-placed roster back OUT to NOC. Use when the user mentions \"NOC\", \"NOC integration\", \"NOC import/export\", \"Legend\", \"connector-server\", \"external system integration\", \"roster export to NOC\", \"publish roster to NOC\", \"F8 import\", \"interface_id\", \"F8_IMPORT origin\", or asks where imported data came from / where solver output goes. Living doc — append new NOC learnings here.",
    "resources": [
      "dir:agents"
    ],
    "sourcePath": ".agents/skills/126-noc-integration/SKILL.md"
  },
  {
    "name": "127-pairing-open-credit-badge",
    "folder": "127-pairing-open-credit-badge",
    "number": 127,
    "title": "Pairing open-credit badge + Main-title removal",
    "description": "Add or maintain the gantt Pairing pane \"open/partial coverage total credit\" badge (HH:MM next to the count badge, shown only when Coverage narrows to Open/Partial) and the pane-title \"Main\"-removal. Use when touching pairing-pane credit aggregates, coverage-gated toolbar badges, the shared pairing-credit util, or when a feature must land in BOTH the Live legacy pairing pane AND the Scenario SharedPairingPane. Also the canonical note that the pairing Coverage DEFAULT is ['open','partial'] (NOT all-states).",
    "overview": "A shipped gantt feature (F316, branch `feat/gantt/res-pairing-creator`). Read `docs/modules/gantt/live-scenario-gantt-playbook.md` §9 first (this skill is the how-to; the playbook is the canonical reference). Always load **115-gantt-playbook** before gantt work.",
    "function": "1. **Open-credit badge** — next to the pairing pane count badge, a `Clock` badge shows the summed credit (HH:MM) of the still-uncovered pairings, **only** when the Coverage filter is a non-empty subset of `{open, partial}`. Credit comes from each pairing's own credit (the \"Cred\" column). 2. **\"Main\" removal** — pane titles dropped the redundant \"Main\": `Roster Main`→`Roster`, `Pairing Main`→`Pairing` (Sub labels unchanged; Flight was already just \"Flight\").",
    "howToUse": "- **Pairing Coverage DEFAULT is `['open','partial']`** (`gantt/src/stores/filter-store.ts:66`, `DEFAULT_PAIRING_FILTER`) — NOT `[...ALL_COVERAGE]`. The pane opens narrowed, so the badge shows out of the box. Older specs/notes claiming an all-states default are STALE (pre-existing red: `pairing-coverage-badge` Live-1111/1112; `scenario-pairing-filter` Scen-2017/2018 — the open+partial hard filter yields 2 rows, not 3). The Filter-dialog coverage *toggle* is also flaky in the e2e demo env — don't drive coverage through the dialog; set it via the `applyPairingFilter` test hook. - **Live pairing is still the LEGACY fork** (`panes/pairi...",
    "resources": [
      "dir:agents"
    ],
    "sourcePath": ".agents/skills/127-pairing-open-credit-badge/SKILL.md"
  },
  {
    "name": "128-res-pairing-management",
    "folder": "128-res-pairing-management",
    "number": 128,
    "title": "RES Pairing Creator — Skill 128",
    "description": "Canonical how-to for the RES Pairing Creator feature (Live Gantt only). Triggers when the user mentions: \"RES pairing\", \"reserve pairing\", \"PRAM\", \"PRPM\", \"CRAM\", \"CRPM\", \"RES Pairing Creator\", \"create reserve duties\", \"manage RES\", \"reserve coverage\".",
    "overview": "> Feature shipped on branch `feat/gantt/res-pairing-creator` (unmerged as of 2026-06-23). > Backend 18/18 vitest PASS · E2E 7/7 Playwright PASS. > Spec: `docs/superpowers/specs/2026-06-23-res-pairing-creator-design.md` > Plan: `docs/superpowers/plans/2026-06-23-res-pairing-creator.md` ---",
    "function": "Reserve pairings are **real `pairing` rows** (not a separate table), stored with: One `pairing_segment` per pairing (`duty_seq=1, seg_seq=1`, `flt_id=NULL`, `duty_assignment='SBY'`, `seg_assignment=<callCode>`). One `pairing_composition` row per rank (`division, acting_rank, plan`). **Call codes and division:** Windows are multi-select assignments (not AM/PM binary). Cell key = `date|base|assignment`. See spec `2026-07-13-res-planner-assignment-multi-select-design.md`. **Ranks in use:** Pilot → `CA`, `FO`; Cabin → `IFD`, `FA` (data-driven, not hard-coded). **Timezone:** AM/PM window times are interpreted as **base-local wall-clock...",
    "howToUse": "cd e2e npx playwright test --config=config/playwright.config.ts --project=gantt --no-deps \\ tests/gantt/res-pairing-button.spec.ts \\ tests/gantt/res-pairing-dialog.spec.ts \\ tests/gantt/res-pairing-yvr-acceptance.spec.ts \\ tests/gantt/res-pairing-yyz-cabin-acceptance.spec.ts \\ --reporter=list",
    "resources": [
      "dir:agents"
    ],
    "sourcePath": ".agents/skills/128-res-pairing-management/SKILL.md"
  },
  {
    "name": "129-bring-crew-to-top-gesture",
    "folder": "129-bring-crew-to-top-gesture",
    "number": 129,
    "title": "Bring-Crew-To-Top Gesture (gantt)",
    "description": "How the gantt \"bring a crew to the top of the roster\" gesture works and how to add a new trigger for it (Alert Center row click, Quality dialog row click, Filter Crew-ID input, Find Crew). Triggers when the user says \"bring crew to top\", \"float crew\", \"click row to show roster\", \"jump to crew\", \"Alert Center row click\", or when wiring any dialog/list to surface a crew's roster in the gantt.",
    "overview": "When a list/dialog should \"click a crew → float that crew to the TOP of the roster pane and scroll it into view\" so the planner can inspect its roster.",
    "function": "When a list/dialog should \"click a crew → float that crew to the TOP of the roster pane and scroll it into view\" so the planner can inspect its roster.",
    "howToUse": "How the gantt \"bring a crew to the top of the roster\" gesture works and how to add a new trigger for it (Alert Center row click, Quality dialog row click, Filter Crew-ID input, Find Crew). Triggers when the user says \"bring crew to top\", \"float crew\", \"click row to show roster\", \"jump to crew\", \"Alert Center row click\", or when wiring any dialog/list to surface a crew's roster in the gantt.",
    "resources": [
      "dir:agents"
    ],
    "sourcePath": ".agents/skills/129-bring-crew-to-top-gesture/SKILL.md"
  },
  {
    "name": "130-crew-bell-click-popup",
    "folder": "130-crew-bell-click-popup",
    "number": 130,
    "title": "Crew Bell Click → Per-Crew Popup",
    "description": "Per-crew bell click in roster pane → ViolationListDialog filtered to that crew's violations (Scen-2045 + Viol-8012). Covers the stale-bell guard (crew 295 bug fix) and E2E recipe.",
    "overview": "**Shipped**: feat/gantt/res-pairing-creator (F323) **Tests**: Scen-2045 (mocked Scenario) + Viol-8012 (Live)",
    "function": "When a crew row in the roster header canvas shows a violation bell (red/amber dot at right edge), clicking that bell opens `ViolationListDialog` filtered to ONLY that crew's violations — distinct from the toolbar bell (Alert Center, all crews). **Stale-bell guard**: if `alertCenter.rows` has no violations for the clicked crew (bell visible in canvas via `violations` map, but `persistedRaw` is out of sync), `handleCrewBellClick` triggers `alertCenter.onScan()` and opens the full Alert Center instead of an empty per-crew dialog. Root cause: `runPreCheck` writes to `violations` without touching `persistedRaw`; the guard prevents the c...",
    "howToUse": "Per-crew bell click in roster pane → ViolationListDialog filtered to that crew's violations (Scen-2045 + Viol-8012). Covers the stale-bell guard (crew 295 bug fix) and E2E recipe.",
    "resources": [
      "dir:agents"
    ],
    "sourcePath": ".agents/skills/130-crew-bell-click-popup/SKILL.md"
  },
  {
    "name": "131-assignment-group-mapping",
    "folder": "131-assignment-group-mapping",
    "number": 131,
    "title": "The three master tables + the fact table",
    "description": "How ROIS models crew assignments → assignment groups, and how to reconcile the master tables (assignment, assignment_group, assignment_group_map) against the codes actually used in roster_flight. KEY FACT — the map is MANY-TO-MANY: one assignment can belong to MULTIPLE groups (e.g. DHD→FLY+GRD; VAC sits under GRD operationally). Triggers when the user mentions: \"assignment group\", \"assignment_group_map\", \"assignment mapping\", \"reconcile assignments\", \"missing assignment\", \"roster_flight assignment values\", or asks to make roster_flight codes resolve to master rows.",
    "overview": "`roster_flight.assignment` / `.assignment_group` store **codes directly** — there is **no normalization layer**. `assignment_group_map` maps master→master (assignment_id→group_id), it does **NOT** translate `FLY→FLT`. So roster data can reference codes absent from either master, and nothing stops it.",
    "function": "`roster_flight.assignment` / `.assignment_group` store **codes directly** — there is **no normalization layer**. `assignment_group_map` maps master→master (assignment_id→group_id), it does **NOT** translate `FLY→FLT`. So roster data can reference codes absent from either master, and nothing stops it.",
    "howToUse": "How ROIS models crew assignments → assignment groups, and how to reconcile the master tables (assignment, assignment_group, assignment_group_map) against the codes actually used in roster_flight. KEY FACT — the map is MANY-TO-MANY: one assignment can belong to MULTIPLE groups (e.g. DHD→FLY+GRD; VAC sits under GRD operationally). Triggers when the user mentions: \"assignment group\", \"assignment_group_map\", \"assignment mapping\", \"reconcile assignments\", \"missing assignment\", \"roster_flight assignment values\", or asks to make roster_flight codes resolve to master rows.",
    "resources": [
      "dir:agents"
    ],
    "sourcePath": ".agents/skills/131-assignment-group-mapping/SKILL.md"
  },
  {
    "name": "132-pairing-id-filter",
    "folder": "132-pairing-id-filter",
    "number": 132,
    "title": "Pairing ID filter (multi-value, hard, unified Live + Scenario)",
    "description": "Add or maintain the gantt Filter dialog › Pairing tab › \"Pairing ID\" multi-value search — a client-side HARD filter on the numeric pairing.id, unified across Live (legacy pairing-pane) and Scenario (SharedPairingPane / pairingMatchesSharedFilter). Use when touching pairing-id filtering, adding a multi-value chip facet to the Pairing tab, or when a pairing filter must behave identically in Live + Scenario. Triggers on \"pairing id search\", \"filter by pairing id\", \"find pairings by id\", \"multiple pairing ids\".",
    "overview": "Shipped gantt feature. Always load **115-gantt-playbook** first; canonical reference is `docs/modules/gantt/live-scenario-gantt-playbook.md` §9. Bump `FRONTEND_VERSION` on change.",
    "function": "Filter dialog › Pairing tab › **\"Pairing ID\"** (`filter-pairing-id`, a `TextChipField`, split on comma/period/space) narrows the pairing pane to the pairings whose **numeric `pairing.id`** is in `PairingFilter.pairingIds`. It is a **HARD filter in BOTH views** (shows only matches — never floats), which is the clean unified behaviour. Distinct from the **Label** field (which matches `pairingLabel`).",
    "howToUse": "Add or maintain the gantt Filter dialog › Pairing tab › \"Pairing ID\" multi-value search — a client-side HARD filter on the numeric pairing.id, unified across Live (legacy pairing-pane) and Scenario (SharedPairingPane / pairingMatchesSharedFilter). Use when touching pairing-id filtering, adding a multi-value chip facet to the Pairing tab, or when a pairing filter must behave identically in Live + Scenario. Triggers on \"pairing id search\", \"filter by pairing id\", \"find pairings by id\", \"multiple pairing ids\".",
    "resources": [
      "dir:agents"
    ],
    "sourcePath": ".agents/skills/132-pairing-id-filter/SKILL.md"
  },
  {
    "name": "133-ro-solver-algorithm",
    "folder": "133-ro-solver-algorithm",
    "number": 133,
    "title": "Overview",
    "description": "Use when understanding legacy RO solver material or current PBS column-generation solver behavior. F8 scope note: ro-engine is retained legacy material; current F8 PBS optimization uses pbs-engine and current legality uses rule-engine-rs.",
    "overview": "> **F8 scope note:** `ro-engine/` is retained legacy material. Current F8 PBS optimization work uses `pbs-engine/`; current legality work uses `rule-engine-rs/`. The legacy RO solver (`ro-engine/src/`) was a **black-box CLI subprocess** — no HTTP, Redis, or DB. Keep this material for historical algorithm reference; implement current F8 optimization changes in `pbs-engine/`. python -m src --input input.gz --output output.gz Exit: 0=DONE 1=INFEASIBLE 2=TIMEOUT 3=INTERNAL_ERROR ---",
    "function": "> **F8 scope note:** `ro-engine/` is retained legacy material. Current F8 PBS optimization work uses `pbs-engine/`; current legality work uses `rule-engine-rs/`. The legacy RO solver (`ro-engine/src/`) was a **black-box CLI subprocess** — no HTTP, Redis, or DB. Keep this material for historical algorithm reference; implement current F8 optimization changes in `pbs-engine/`. python -m src --input input.gz --output output.gz Exit: 0=DONE 1=INFEASIBLE 2=TIMEOUT 3=INTERNAL_ERROR ---",
    "howToUse": "See skill `104-run-pbs-solver-local` for the full local run recipe. Quick test against baseline: git submodule update --init --recursive pbs-engine",
    "resources": [
      "dir:agents"
    ],
    "sourcePath": ".agents/skills/133-ro-solver-algorithm/SKILL.md"
  },
  {
    "name": "139-uat-test-case-builder",
    "folder": "139-uat-test-case-builder",
    "number": 139,
    "title": "Overview",
    "description": "Build a customer-ready UAT (User Acceptance Test) test-case workbook (.xlsx) for ROIS-AI product surfaces, sourced from the product's own online help. Use when the user asks to \"create UAT test cases\", \"make a UAT test case Excel\", \"add a tab/module to the UAT workbook\", \"bump the UAT test cases to ver N\", or wants per-feature acceptance tests for Admin UI (Altair Live/Scenario), Legality, Crew Portal (PBS), or Integration (connector/NOC/S3). Produces a multi-round (UAT 1/2/3) workbook with an auto-computed summary tab, modelled on the customer reference files in docs/UAT/. Triggers on \"UAT test case\", \"acceptance test\", \"UAT workbook\", \"test case excel\".",
    "overview": "Turns ROIS-AI product features into a **customer-facing UAT workbook**: one Summary tab (T1) plus one tab per product surface, every feature rendered as a plain-English, click-by-click test case with **multiple test rounds** (UAT 1 / 2 / 3) so a case that fails round 1 is re-tested in round 2/3 and still rolls up correctly. **Audience is the end user / customer tester** — keep it easy: plain English, no internal jargon (no table names, LSY refs, code identifiers), focus on user-visible features. **Source of truth = the product's own online help.** Do not invent features. Extract them from the help topic source in-repo (far more rel...",
    "function": "Turns ROIS-AI product features into a **customer-facing UAT workbook**: one Summary tab (T1) plus one tab per product surface, every feature rendered as a plain-English, click-by-click test case with **multiple test rounds** (UAT 1 / 2 / 3) so a case that fails round 1 is re-tested in round 2/3 and still rolls up correctly. **Audience is the end user / customer tester** — keep it easy: plain English, no internal jargon (no table names, LSY refs, code identifiers), focus on user-visible features. **Source of truth = the product's own online help.** Do not invent features. Extract them from the help topic source in-repo (far more rel...",
    "howToUse": "1. **Confirm scope & tab→surface mapping.** Which surfaces become tabs, who the audience is, how many rounds (default 3). Note: `/pbs/help` = Crew Portal; Live/Scenario/Legality live in the Altair app (`/altair`), even if the user's URL says otherwise — confirm. 2. **Fan out readers (parallel subagents), one per tab.** Each reads that surface's help topic source and emits a JSON file of cases (schema below). This keeps step-level detail accurate and your context clean. Prompt them for: real UI names, concrete numbered steps, a specific assertable expected result, and correct severity. 3. **Honesty gate (§No-Illusion).** If a featur...",
    "resources": [
      "dir:scripts",
      "file:example-manifest.json"
    ],
    "sourcePath": ".agents/skills/139-uat-test-case-builder/SKILL.md"
  },
  {
    "name": "140-weekly-progress-report-updater",
    "folder": "140-weekly-progress-report-updater",
    "number": 140,
    "title": "Overview",
    "description": "Update the F8 (Flair) weekly project status workbook (F8-CMS-CrewWeeklyReport <DD>Aug<YYYY>.xlsx) — add a new dated tab for the current Tuesday meeting (copied from the most recent week's tab, prior weeks left untouched), roll its Report Date / Report Period forward, and refresh the High-Level Review progress sections (Rule Engine, Data & Integration, AI Core, Crew Portal, Admin Portal) from the week's raw notes. Use when the user says \"update the weekly report\", \"update weekly progress\", \"roll the weekly status to today/this Tuesday\", or pastes a week's dev notes to fold into the report. Preserves existing content, colours this week's new/changed items in blue, keeps section titles bold.",
    "overview": "Maintains the customer-facing weekly status workbook as **one file with one tab per week**. The project holds a status meeting **every Tuesday**; each update **adds a new tab** for this Tuesday — copied from the most recent week's tab so all layout/formatting carries over — and **leaves every prior week's tab untouched** (they are the historical record). Only the new tab's reporting window and narrative progress cells are edited. The new tab is named `<DD><Mon><YY> Rpt` (e.g. `25Aug26 Rpt`) and becomes the active sheet. The workbook file name keeps its own date suffix; do not create a separate file per week. **File location (iCloud...",
    "function": "Maintains the customer-facing weekly status workbook as **one file with one tab per week**. The project holds a status meeting **every Tuesday**; each update **adds a new tab** for this Tuesday — copied from the most recent week's tab so all layout/formatting carries over — and **leaves every prior week's tab untouched** (they are the historical record). Only the new tab's reporting window and narrative progress cells are edited. The new tab is named `<DD><Mon><YY> Rpt` (e.g. `25Aug26 Rpt`) and becomes the active sheet. The workbook file name keeps its own date suffix; do not create a separate file per week. **File location (iCloud...",
    "howToUse": "1. **Locate the file** and confirm the target path (`Project Meeting Notes/`). 2. **Back it up** to the scratchpad before editing (`cp` the .xlsx). 3. **Identify the latest tab** (most recent `<DD><Mon><YY> Rpt`) and **read its `C2/C3/D8/D9`** verbatim so nothing is lost — this tab is the copy source. 4. **Copy that tab** with `wb.copy_worksheet(src)`, rename the copy to `<this-Tue> Rpt`, and make it the active sheet. **Do not touch the source tab.** 5. **Compute dates**: this Tuesday = today (the meeting day); last Tuesday = today − 7. 6. **Classify** each raw note into sections 2–6 per the mapping above; write concise English. 7....",
    "resources": [
      "dir:scripts"
    ],
    "sourcePath": ".agents/skills/140-weekly-progress-report-updater/SKILL.md"
  },
  {
    "name": "141-crew-seed-generator",
    "folder": "141-crew-seed-generator",
    "number": 141,
    "title": "141 Crew Seed Generator",
    "description": "Generate a batch of synthetic F8 crew (pilots: CA/FO) for a new base/fleet/nationality — auto-creates the airport/fleet/rank reference rows if absent, inserts crew + crew_base + crew_fleet + crew_rank, and validates by query. Use when asked to \"add crew for a new country/base\", \"seed test crew\", or \"create N crew members\" with a given id prefix, base, fleet, and nationality.",
    "overview": "Idempotent generator for adding a themed batch of crew (new base + fleet + nationality) to the `crew` data model described in `docs/architecture/data-model.md`. Built for the 2026-08-27 request: 40 UAE crew (`K1001`-`K1040`, DXB, A380) + 40 Ethiopian crew (`T2001`-`T2040`, ADD, B787), on top of the existing Canadian (`YYZ`/`YVR`/... , 737) crew.",
    "function": "Per group, in order: 1. `airport` — inserts the base airport if the code doesn't exist yet (IATA code, ICAO, city, `dir` D/I, IANA `zone_id`, `utc_standard_offset` minutes, ISO-2 `country`). 2. `base` — inserts the crew-home-base reference row if absent (`filiale`, `base`, `name` = the 3-letter code per existing convention, `display_order` auto-appended). This is a **separate table from `airport`** — it's what the Gantt filter dialog's \"Base\" dropdown actually reads (`GET /api/base`, Redis-cached 24h). Skipping this step leaves the new base invisible in the UI dropdown even though the crew data is otherwise correct. 3. `fleet` — in...",
    "howToUse": "node ../.agents/skills/141-crew-seed-generator/scripts/seed-crew.mjs \\ ../.agents/skills/141-crew-seed-generator/fixtures/uae-dxb-a380.json --dry-run",
    "resources": [
      "dir:agents",
      "dir:fixtures",
      "dir:scripts"
    ],
    "sourcePath": ".agents/skills/141-crew-seed-generator/SKILL.md"
  },
  {
    "name": "142-flight-schedule-seed-generator",
    "folder": "142-flight-schedule-seed-generator",
    "number": 142,
    "title": "142 Flight Schedule Seed Generator",
    "description": "Generate a themed batch of synthetic `flight` schedule rows (airline/fleet/route network over a date range), DST-aware local-to-UTC conversion, no real tail number (frontend groups by fleet). Use when asked to \"seed a flight schedule\", \"add EK/ET flights\", or \"populate flight data for a route/date range\" with a given airline, fleet, base, and routes.",
    "overview": "Idempotent generator for adding a themed batch of `flight` rows (new airline/fleet/route network) to the data model described in `docs/architecture/data-model.md`. Built for the 2026-08-27 request: Emirates (`EK`) A380 flights out of DXB, and Ethiopian Airlines (`ET`) B787 + 737 flights out of ADD, for the full calendar range 2026-08-01 to 2026-09-30.",
    "function": "Only the `flight` table. Reuses existing reference data (no new rows needed for this seed): `airport` (all 14 route endpoints already exist with `zone_id` populated), `fleet` (`A380`, `B787`, `737` already exist). Each fixture route generates two rows per date (outbound + inbound leg). Idempotent — the script checks `flight_key` (`{flt_num}-{date}-{dep_arp}`) first and skips rows that already exist, safe to re-run.",
    "howToUse": "node ../.agents/skills/142-flight-schedule-seed-generator/scripts/seed-flights.mjs \\ ../.agents/skills/142-flight-schedule-seed-generator/fixtures/ek-dxb-a380.json --dry-run",
    "resources": [
      "dir:agents",
      "dir:fixtures",
      "dir:scripts"
    ],
    "sourcePath": ".agents/skills/142-flight-schedule-seed-generator/SKILL.md"
  },
  {
    "name": "portal-help-writing",
    "folder": "portal-help-writing",
    "number": null,
    "title": "Overview",
    "description": "Write or update the PBS Portal in-app Help Center in pbs-portal/src/features/help, including Help topics, screenshots, navigation, E2E content tests, and manual QA docs. Use when the user mentions Portal Help pages, Help topics/articles, operation manuals, Help screenshots, or documenting Dashboard, Days Off, Pairing, Line, Reserve, or Tier behavior in pbs-portal.",
    "overview": "PBS Portal Help is a user-facing operating manual. Its content must match the current Portal UI and code, and it must not document unfinished features such as Standing Bid until those pages exist.",
    "function": "PBS Portal Help is a user-facing operating manual. Its content must match the current Portal UI and code, and it must not document unfinished features such as Standing Bid until those pages exist.",
    "howToUse": "1. Read the user request and identify the Portal feature being documented. 2. Open the implementation files for that feature before writing content. The code is the source of truth for UI text, controls, and behavior. 3. Update the Help registry and topic map together: - `pbs-portal/src/features/help/help-data.ts` - `pbs-portal/src/features/help/components/help-view.tsx` - `pbs-portal/src/features/help/topics/<area>/<slug>.tsx` 4. Match exact Portal UI labels such as `ADD DAYS OFF PROPERTIES`, `ADD PAIRING PROPERTIES`, `ADD LINE PROPERTIES`, `ADD RESERVE BID`, `BID SUMMARY`, `T1-T7`, and `Search Current Rules`. 5. Do not use older...",
    "resources": [
      "dir:agents"
    ],
    "sourcePath": ".agents/skills/portal-help-writing/SKILL.md"
  }
]
