include_guard()

include(${CMAKE_CURRENT_LIST_DIR}/framework/CMakeLists.txt)

set(NewRuleEngineImpl_NAME NewRuleImpl)

file(GLOB ${NewRuleEngineImpl_NAME}_SRC
        "${CMAKE_CURRENT_LIST_DIR}/rule0000/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule2001/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule3003/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule6005/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule6006/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule6007/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule6008/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule6009/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule6010/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule6011/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule6018/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule6019/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule6020/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule6021/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule6022/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule6024/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule6025/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule6026/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule6100/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule6101/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule6102/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule6103/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule6104/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule6105/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule6107/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule6109/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule6110/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule6111/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule6115/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule6032/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule6033/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule6034/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule6035/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule6036/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule6037/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule6038/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule6039/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule6041/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule6120/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7000/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7006/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7007/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7008/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7009/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7011/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7013/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7014/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7015/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7016/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7017/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7018/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7019/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7021/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7022/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7023/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7024/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7028/*.cpp"
	"${CMAKE_CURRENT_LIST_DIR}/rule7029/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7115/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7100/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7200/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7202/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7203/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7204/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7205/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7210/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7211/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7212/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7213/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7214/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7215/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7217/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7218/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7219/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7220/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7221/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7222/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7223/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7224/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7225/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7226/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7227/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7228/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7229/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7230/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7231/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7232/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7233/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7234/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7235/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7236/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7237/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7238/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7239/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7240/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7241/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7242/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7243/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7244/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7245/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7246/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7247/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7248/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7249/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7250/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7251/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7252/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7253/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7254/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7255/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7256/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7257/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7258/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7259/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7260/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7261/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7262/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7263/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7264/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7265/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7266/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7267/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7268/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7269/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7270/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7271/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7272/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7273/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7274/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7275/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7276/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7277/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7278/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7279/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7300/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7302/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7303/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7305/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7306/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7307/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7308/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7309/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7310/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7311/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7312/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7313/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7314/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7315/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7320/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7321/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7322/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7323/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7324/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7325/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7326/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7327/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7328/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7361/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7388/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7389/*.cpp"	
        "${CMAKE_CURRENT_LIST_DIR}/rule7400/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7401/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7405/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7414/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7415/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7416/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7417/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7420/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7421/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7422/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7423/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7424/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7434/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7435/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7356/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7357/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7360/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7362/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7410/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7450/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7451/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7452/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7453/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7460/*.cpp"	
        "${CMAKE_CURRENT_LIST_DIR}/rule7412/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7461/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7462/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7463/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7464/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7465/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7466/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7467/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7469/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7317/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7480/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7481/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7482/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule6121/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7358/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7372/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7373/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7374/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7387/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7484/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7485/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7486/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7359/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7487/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7488/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7489/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7490/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7491/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7494/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7495/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7496/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7500/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7501/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7502/*.cpp"	
        "${CMAKE_CURRENT_LIST_DIR}/rule7503/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7504/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7505/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7506/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7363/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7364/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7365/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7492/*.cpp"
	"${CMAKE_CURRENT_LIST_DIR}/rule7493/*.cpp"
        "${CMAKE_CURRENT_LIST_DIR}/rule7366/*.cpp"
)

add_library(${NewRuleEngineImpl_NAME} STATIC
        ${${NewRuleEngineImpl_NAME}_SRC}
)

target_include_directories(${NewRuleEngineImpl_NAME} PUBLIC
        $<BUILD_INTERFACE:${CMAKE_CURRENT_LIST_DIR}/>
)

target_link_libraries(${NewRuleEngineImpl_NAME} PUBLIC ${RuleEngineFramework_NAME})
