import { HelpH2, HelpStep, HelpNote, HelpWarning } from '../../help-article'

export default function RecoveryArticle() {
  return <>
<HelpNote>Availability: these cases require the Assignment Overlap recovery update. If Recovery shows only Roster transfer or exchange, Standby Crew callout and Cross-base positioning for an overlap, your build does not yet include cases 103 and 104. Ask your administrator to update it.</HelpNote>
<HelpH2>One disruption, three different remedies</HelpH2>
<HelpNote>Case numbers 102–104 identify operating examples; they are not rule numbers. All three start from Rule 1001, Assignment Overlap: a ground task overlaps a flying pairing. Rule 8004 uses a different list of recovery methods.</HelpNote>
<HelpStep n={1}>Open <strong>Live</strong>, choose the roster periods and apply crew filters. Include the affected crew and potential replacement crews. Read the Roster duties alongside the Pairing and Flight panes. Recovery searches loaded Live data; a narrow filter can hide a valid replacement.</HelpStep>
<HelpStep n={2}>Open the Roster pane’s <strong>Alert Center</strong> using its bell. Find the affected crew, rule and pairing. Select one recoverable <strong>1001</strong> row and choose <strong>Recovery</strong>. A general overlap without a loaded ground task overlapping that flying pairing does not qualify. A roster right-click Recovery action is another entry when an eligible alert exists.</HelpStep>
<HelpStep n={3}>Choose a method in the left tree: <strong>102 — Standby Crew callout</strong> replaces the crew; <strong>103 — Swap duty</strong> exchanges complete pairings; <strong>104 — Flight Delay</strong> keeps the crew and moves flight actual times. The tree also groups options by cost tier and marks the lowest estimate with a star.</HelpStep>
<HelpStep n={4}>Compare the option’s crew and roster impact, Cancel/Add counts, Stability and Cost. Open <strong>Detail</strong> for before/after changes and exclusion reasons. Click a cost amount for <strong>Cost breakdown</strong>. Read warnings before choosing; the lowest amount does not establish feasibility.</HelpStep>
<HelpStep n={5}>For standby or swap, select an executable option’s checkbox. Row highlighting alone is for browsing. <strong>Preview</strong> shows before/after rosters in Live without saving; return with <strong>Options</strong>. Selecting the Flight Delay method makes its single plan the Apply target without a crew checkbox. <strong>Apply selected option</strong> acquires locks and stages the changes in the unsaved draft.</HelpStep>
<HelpStep n={6}>Inspect the draft, then use <strong>Save</strong> (Ctrl+S) to commit. After refresh and rule recheck, confirm that the original overlap is resolved, the intended crew cover every leg, other duties remain correct, and credit/FDP/rest and follow-on assignments are acceptable. Apply success alone does not prove recovery is complete.</HelpStep>
<HelpH2>Reusable approach for the next case</HelpH2>
<HelpNote>Use the same sequence: identify the disruption → define the affected scope → generate alternatives → check feasibility and warnings → compare priced impact → preview → choose → Apply → Save → verify the operational result. Each new case must state what changes, what stays, why each candidate qualifies, what the estimate includes, and what proves the disruption is resolved.</HelpNote>
<HelpWarning>The current fleet mismatch warning is a soft constraint: an option may remain selectable. Flight Delay does not run the same candidate rule preview as standby and swap. Review these limitations before treating an option as ready for operation.</HelpWarning>

<HelpH2>Define the baseline before comparing alternatives</HelpH2>
<HelpNote>Write down the affected crew, ground-task start/end, pairing identity, report/release times and every flight leg. Use one time basis throughout; the worked examples here use UTC (Z). Include onward duties and the other crews sharing those flights. A pairing is the complete work package assigned to a crew; one delayed leg can affect that package and other linked assignments.</HelpNote>
<p className="text-xs leading-relaxed">The operational objective is to remove the conflict while retaining safe, qualified coverage. Candidate generation answers who or what might fit the loaded data. Rule preview adds evidence about legality; it does not establish transport availability, crew acceptance or a complete network recovery. Treat unavailable options as excluded, inspect soft warnings explicitly, and verify anything outside the loaded period before choosing.</p>
<HelpH2>Choose the intervention that addresses the cause</HelpH2>
<HelpNote><strong>102:</strong> use an available standby replacement when the flight sequence should stay. <strong>103:</strong> consider a two-way exchange when both complete pairings fit their new owners. <strong>104:</strong> consider moving flight actual times when retaining the crew is operationally acceptable. Assess qualification and legality first, then coverage and downstream impact, then comparable incremental cost. The lowest-cost star is a sorting aid, not an approval.</HelpNote>
<HelpH2>Three decision checkpoints</HelpH2>
<p className="text-xs leading-relaxed"><strong>Before Preview:</strong> confirm the source conflict, candidate eligibility and estimate completeness. <strong>Before Apply:</strong> inspect each removal, addition or time edit and confirm the intended target is selected. <strong>Before Save:</strong> inspect the complete unsaved draft, including any earlier edits, and resolve unexpected changes. If the source roster changes while reviewing, refresh and reassess the option against the new baseline.</p>
<HelpH2>Prove closure, including the next disruption</HelpH2>
<HelpNote>After Save and refresh, inspect the original alert, pairing coverage and both affected roster rows. Recheck report/release, FDP, rest, monthly credit and the next assignment; for delayed flights, include every linked crew. If a new conflict remains, treat it as a new recovery problem with the saved result as its baseline. Reusing the workflow does not mean repeatedly applying the original stale option.</HelpNote>
  </>
}
