import { HelpH2, HelpNote, HelpScreenshot, HelpStep, HelpTip, HelpWarning } from '../../help-article'

export default function RecoveryCase001() {
  return <>
    <HelpH2>Incident and operating objective</HelpH2>
    <p className="text-xs leading-relaxed"><strong>Getnet Kifle, crew J4002</strong>, is an ET captain (CA), based at <strong>ADD</strong> and qualified on 7M8. His unavailable period overlaps pairing <strong>152056</strong>: ET805, ET802, ET378, ET377, ET803 and ET804, operating ADD → DAR → ADD → MGQ → ADD → DAR → ADD on 24–25 September 2026. Ryan is Crew Control. The objective is to cover the complete pairing without assigning flying during the crew’s recorded absence.</p>
    <HelpNote>The crew ID is J4002; ET805 is the first flight. The comparison below uses a prepared SL overlap on 24 September, <strong>00:15–12:15 UTC</strong>. Crew App requests use inclusive base-local dates. This is the prepared controller comparison fixture, not the date-only mobile submission window. A whole-day request can leave Swap duty unavailable and changes delay times; regenerate options for the actual absence.</HelpNote>

    <HelpH2>Start with the crew, then hand over to Crew Control</HelpH2>
    <HelpStep n={1}><strong>Crew J4002 · Crew App → Absence.</strong> Open <strong>Absence Request</strong>, choose <strong>Sick leave</strong>, review <strong>From</strong>, <strong>To</strong> and the affected flights, and enter a case note. Press <strong>Submit request</strong> once and confirm the submission result. Submission records full-day ILL duties for the selected dates while retaining the original flying duties; submitting SL is not approval of a replacement.</HelpStep>
    <HelpScreenshot src="/help/screenshots/s1-retain-mobile-success-Ver1.jpg" alt="Crew App confirms Request submitted and original duties remain assigned pending Crew Control recovery" caption="Successful crew submission: sick leave is added without automatically de-assigning the original duties." />
    <HelpStep n={2}><strong>Ryan · Live → Crew Absence and roster.</strong> Find J4002’s saved absence and confirm its dates and base. Verify that the original six legs of pairing 152056 remain on J4002 alongside the absence task. The overlap is the incident to resolve, not permission for J4002 to operate while unavailable. Refresh the roster and legality results before opening Recovery.</HelpStep>
    <HelpStep n={3}><strong>Ryan · Live → Filters.</strong> Load ADD pilots, the affected September dates, J4002 and the replacement crews listed below. Include pairing 152056 and the donor pairings in the loaded scope. Check name, base, rank, fleet, source assignment and coverage before choosing an option. Do not narrow the crew filter to J4002 alone when searching for replacements.</HelpStep>
    <HelpStep n={4}><strong>Ryan · Alert Center → Recovery selected.</strong> Select J4002’s recoverable <strong>1001 Assignment Overlap</strong> row for the sick-leave task and flying pairing. Click <strong>Recovery selected</strong>. The three strategy choices are <strong>Standby Crew callout</strong>, <strong>Swap duty</strong> and <strong>Flight Delay</strong>. Wait for candidate checks to finish, then review Executable and Filtered results.</HelpStep>
    <HelpTip>Recovery uses <strong>Loaded Live data only</strong>. If only two swap candidates appear, close Recovery, refresh with all six candidate crews loaded, and reopen the 1001 alert. Choose All and scroll the candidate pane. Preview shows the two affected crews; it is not the full candidate shortlist.</HelpTip>

    <HelpH2>Option 1 — Standby Crew callout</HelpH2>
    <HelpStep n={5}><strong>Ryan · Recovery → Standby Crew callout.</strong> Compare the three ADD/CA/7M8 crews with ASBY on 24 September, 02:00–10:00 UTC. Select one crew checkbox, click its cost amount to open <strong>Cost breakdown</strong>, inspect the GH inputs and policy, then use <strong>Preview</strong>. Repeat separately for J4011, J4012 and J4013; use <strong>Options</strong> to return between previews.</HelpStep>
    <div className="overflow-x-auto"><table className="w-full text-xs" data-testid="s1-standby-costs"><thead><tr><th className="text-left">Crew</th><th className="text-left">Before → projected after</th><th className="text-right">Additional GH (USD)</th></tr></thead><tbody>
      <tr><td>J4011 · Beniam Yimer</td><td>08:00 → 20:20</td><td className="text-right">0.00</td></tr>
      <tr><td>J4012 · Temesgen Chane</td><td>76:35 → 88:55</td><td className="text-right">470.00</td></tr>
      <tr><td>J4013 · Frehiwot Fantahun</td><td>87:05 → 99:25</td><td className="text-right">1,762.50</td></tr>
    </tbody></table></div>
    <HelpScreenshot src="/help/screenshots/s1-gh-standby-list-Ver1.png" alt="Three executable ADD standby crews with zero, 470 and 1762.50 US dollar GH estimates" caption="Same pairing, different monthly-credit positions: J4011 has the lowest incremental GH estimate." />
    <HelpNote>Before means <strong>saved planned calendar-month credit</strong>, not hours already flown or the roster-period MCred badge. The estimate adds pairing credit 15:15 and payable callout standby 01:05, then subtracts ASBY credit 04:00 already in the baseline: net +12:20. The configured GH floor is 85 hours, at USD 100/hour with a 1.2 multiplier above 85 through 90 hours and 1.5 above 90. These are projected pay-policy credits, not a payroll posting or a promise that Save writes the same credit total.</HelpNote>
    <HelpStep n={6}><strong>Ryan · Standby Preview.</strong> Inspect the before/after rosters: J4002 retains SL but loses the entire pairing; the selected standby captain gains all six legs. The original ASBY remains and is marked as a callout. Check surrounding duties, station, qualifications and rest. Return to Options without applying if comparing another candidate.</HelpStep>

    <HelpH2>Option 2 — Swap duty</HelpH2>
    <HelpStep n={7}><strong>Ryan · Recovery → Swap duty → All.</strong> Compare six candidates. Each receives J4002’s complete pairing 152056; J4002 receives that candidate’s later-reporting donor pairing. Confirm the donor reports after the unavailable period and review both resulting rosters. A recorded SL end is not medical confirmation that J4002 is fit to resume duty.</HelpStep>
    <div className="overflow-x-auto"><table className="w-full text-xs" data-testid="s1-swap-costs"><thead><tr><th className="text-left">Crew / donor pairing</th><th className="text-left">Before → projected after</th><th className="text-right">Additional GH (USD)</th></tr></thead><tbody>
      <tr><td>J4005 / 152097</td><td>15:15 → 22:35</td><td className="text-right">0.00</td></tr>
      <tr><td>J4014 / 152093</td><td>17:25 → 24:15</td><td className="text-right">0.00</td></tr>
      <tr><td>J4015 / 152093</td><td>17:35 → 24:25</td><td className="text-right">0.00</td></tr>
      <tr><td>J4018 / 152106</td><td>78:30 → 86:05</td><td className="text-right">130.00</td></tr>
      <tr><td>J4016 / 152097</td><td>80:40 → 88:00</td><td className="text-right">360.00</td></tr>
      <tr><td>J4017 / 152106</td><td>81:20 → 88:55</td><td className="text-right">470.00</td></tr>
    </tbody></table></div>
    <HelpScreenshot src="/help/screenshots/s1-swap-gh-list-Ver1.png" alt="Six executable swap crews with GH cost comparisons and both-crew credit notes" caption="Six available swaps. The high-credit candidates cross the 85-hour GH floor; the first three add no GH pay." />
    <HelpStep n={8}><strong>Ryan · Swap Cost breakdown → Preview.</strong> Select and inspect each candidate one at a time. The GH estimate includes <strong>both crews</strong>: remove each outgoing pairing’s credit and add the incoming pairing’s credit before comparing pay. J4002 starts at 77:35 and finishes at 70:45, 70:15 or 70:00 for these donors, adding no GH pay. Preview must show two complete pairing exchanges, not a one-leg swap. Apply stages <strong>two removals and two assignments</strong>; for a comparison-only rehearsal, Undo all four draft operations instead of Save.</HelpStep>

    <HelpH2>Option 3 — Flight Delay</HelpH2>
    <HelpStep n={9}><strong>Ryan · Recovery → Flight Delay → Preview.</strong> Inspect every flight’s old and proposed time. This proposal retains J4002 and shifts the affected pairing after the recorded ground-task end plus 61 minutes; it does <strong>not wait for a reserve-pool refresh</strong>. In this timed demo ET805 changes from <strong>05:10Z to 13:16Z</strong>, a delay of 08:06. There is no crew checkbox. Return to Options after reviewing the full sequence.</HelpStep>
    <HelpScreenshot src="/help/screenshots/s1-delay-comparison-Ver1.png" alt="Flight Delay proposal for all six flights, retaining J4002 and moving ET805 to 13:16 UTC" caption="Delay is a timing alternative, not a standby replacement. Unpriced is unknown cost, not free operation." />
    <HelpWarning>Flight Delay was previewed, not saved in this case. Confirm fitness to return, all affected crews, connected pairings, aircraft and passenger consequences before any operational delay. The current delay path does not run the standby/swap rule preview. No passenger re-accommodation amount is established by this example.</HelpWarning>

    <HelpH2>Choose, save and verify</HelpH2>
    <HelpStep n={10}><strong>Ryan · Decision → Standby Crew callout → J4011.</strong> Return to standby and explicitly check J4011. This choice covers the pairing with USD 0.00 incremental GH and avoids exchanging a second crew’s pairing. Some swaps also quote zero GH, so price alone does not determine the decision. Compare the Cancel/Add counts, Stability, rule results and operational readiness. The star identifies the lowest available priced estimate, not a complete composite-cost optimum.</HelpStep>
    <HelpStep n={11}><strong>Ryan · Apply selected option → Live Save.</strong> Click Apply selected option (or Apply in Preview). Verify the three standby draft operations: remove J4002’s pairing, assign it to J4011, and mark ASBY as a callout. <strong>Preview is not Apply; Apply is not Save.</strong> Click Save only after reviewing the draft. Reload and confirm zero unsaved changes, all six legs assigned to J4011, none of those legs left on J4002, retained absence task and the saved ASBY callout marker. Verify coverage and refreshed alerts.</HelpStep>
    <HelpStep n={12}><strong>Ryan / demo operator · Close and replay.</strong> Record the selected crew, quote, changed pairings and verification result. For another demonstration, use the case’s scoped reset procedure to restore the saved starting incident and clear the draft; preserve the prepared standby and donor duties. Verify J4002 again owns the six original legs and the intended 1001 overlap is present. For an end-to-end crew submission replay, restore the pre-submission baseline instead, removing only this run’s owned absence records. Never use Undo as a substitute for restoring a saved recovery.</HelpStep>

    <HelpH2>Demonstrated scope</HelpH2>
    <HelpNote><strong>Crew submission:</strong> J4002 successfully submitted sick leave for 24 September in the Crew App; the full-day ILL task was saved and all six original pairing assignments remained unchanged. <strong>Standby:</strong> all three candidates’ prices and previews were checked; J4011 was applied, saved, reloaded and restored. <strong>Swap:</strong> all six candidates’ prices, previews and Apply → Undo drafts were checked; swap Save was not tested. <strong>Delay:</strong> timing proposal and Preview were checked; Apply and Save were not tested. These controller comparisons started from the prepared timed SL overlap.</HelpNote>
    <HelpNote>Candidate generation uses loaded Live roster data and current legality checks; GH pricing uses the Cost Library and saved month credit. No optimization solver or language model selects the crew here. Executable is the current Recovery gate, not certification of every operational requirement. Quotes exclude other disruption costs. Crew acknowledgement, notifications, hotel/transport cancellation, manifest reissue and APIS updates are outside this demonstrated execution.</HelpNote>
  </>
}
