import { HelpH2, HelpStep, HelpNote, HelpWarning, HelpScreenshot } from '../../help-article'

const types = [
  ['1002', 'Pay above guaranteed hours', 'guarantee', 'Credit hours before/after → incremental guaranteed-pay calculation. Example policy: 85-hour floor, USD 100/hour; 1.2× through 90 hours, then 1.5×.'],
  ['1003', 'Airport standby credit', 'standby', 'Convert eligible standby time into credit, add pairing credit, remove credit already in the baseline, then price through the linked GH policy. No separate unit price. Example: factor 0.5; departure cutoff 60 minutes.'],
  ['1004', 'Home standby activation', 'fixed', 'Qualifying callout (0 or 1) × activation price. Illustrative default: USD 200/callout. This is distinct from airport standby credit.'],
  ['1007', 'Day-off recall', 'fixed', 'Qualifying recall (0 or 1) × recall price. Illustrative default: USD 600/callout. The current Recovery standby bridge uses this type.'],
  ['1009', 'Short-notice roster change', 'fixed', 'Qualifying event (0 or 1) × price. Illustrative default: USD 150/change. A quantity of two is invalid for fixed logic; use an appropriate quantity-based revision when pricing two events.'],
  ['1012', 'Lead cabin position premium', 'quantity', 'Eligible credit hours × configured premium per credit hour. Default price is blank: Unpriced, not zero.'],
  ['1013', 'Language allowance', 'quantity', 'Eligible sectors × configured sector allowance. Default price is blank: Unpriced, not zero.'],
  ['1014', 'Third-pilot augmentation', 'fixed', 'Qualifying event (0 or 1) × augmentation price. Illustrative default: USD 1,200. Sector-based repetition needs the appropriate quantity logic.'],
  ['1015', 'Roster change stability penalty', 'quantity', 'Changed-roster quantity × configured decision penalty. Illustrative default: USD 260/change. A decision weight, not crew cash pay. Added in the newer catalogue.'],
  ['1016', 'Follow-on impact stability penalty', 'quantity', 'Follow-on impact count × configured decision penalty. Illustrative default: USD 1,800/impact. Added in the newer catalogue.'],
  ['2001', 'Hotel accommodation', 'quantity', 'Billable room-nights × room-night price. Illustrative default: USD 140; two room-nights cost USD 280. Count rooms and nights, not flights.'],
  ['2002', 'Day-use room', 'quantity', 'Billable room-blocks × block price. Illustrative default: USD 90/room-block. It is separate from an overnight room-night.'],
  ['2003', 'Per diem', 'quantity', 'Eligible person-days × daily allowance. Illustrative default: USD 60/person-day. The planner supplies the billable quantity.'],
  ['2004', 'Own-airline deadhead', 'quantity', 'Crew seat-sectors × own-airline rate. Illustrative default: USD 120/seat-sector; two crew on two sectors means four seat-sectors.'],
  ['2005', 'Other-airline deadhead', 'quantity', 'Crew seat-sectors × other-airline rate. Illustrative default: USD 600/seat-sector. It is not a live seat-availability or ticket-price search.'],
  ['2006', 'Ground transfer', 'quantity', 'Billable vehicle-trips × trip price. Illustrative default: USD 80/vehicle-trip. Do not multiply by passenger count when several crew share one vehicle.'],
  ['2008', 'Hotel booking replacement', 'booking', 'New booking price − refund + change fee. Illustrative default: USD 160 − USD 140 + USD 0 = USD 20. Original amount limits the allowed refund; it is not charged again.'],
  ['3001', 'Incremental flight delay', 'bands', 'Delay cost(after) − delay cost(before). Illustrative curve: first 120 minutes at USD 60/minute, excess at USD 25/minute. This calculator exists, but case 104 does not yet supply delay inputs to it.'],
  ['3005', 'Aircraft ferry sector', 'quantity', 'Ferry sectors × sector price. Illustrative default: USD 9,000/sector. This represents repositioning the aircraft, not a deadheading crew seat.'],
] as const

export default function RecoveryCostLibrary() {
  return <>
    <HelpWarning>Prices below are illustrative catalogue defaults, not approved airline tariffs. Always use the displayed saved revision and its currency. The reviewed public catalogue contains 17 types; the newer catalogue adds 1015 and 1016. An absent type is not an available zero-cost component.</HelpWarning>
    <HelpH2>Why a cost library exists</HelpH2>
    <p className="text-xs leading-relaxed">Recovery first asks whether a solution can work. Cost then helps compare feasible alternatives on a common basis. The library separates the type of expense, the configured tariff and the quantities caused by a particular solution. A standby replacement may add credit but no incremental pay below a monthly guarantee; a delay may keep the roster stable while creating substantial operational cost. These are different effects and must be measured separately.</p>
    <HelpNote><strong>Incremental cost</strong> means the change from the same baseline operation. Compare before with after, rather than charging the entire monthly salary or a previously paid hotel booking again. A negative result can represent a saving. Unknown, disabled and zero are different states.</HelpNote>
    <HelpH2>Type, instance, revision and Cost Set</HelpH2>
    <p className="text-xs leading-relaxed">A <strong>type</strong> identifies the business expense, such as 1002. A <strong>template instance</strong> is shown as 1002/001; a copied instance can hold an alternative policy. A <strong>revision</strong> records saved parameters, price, currency, dates and references. A <strong>Cost Set</strong> groups instances and pins a specific revision for each member. A set is a policy selection, not a bill: simply belonging to a set does not mean every cost should be charged for every recovery.</p>
    <HelpNote><strong>Save new revision</strong> does not move existing sets to the latest revision. Set membership retains its pinned revision until changed. <strong>Use existing instances</strong> shares configurations when copying a set; <strong>Create independent copies</strong> creates separate configurations. A Calculation Workbench run evaluates a saved revision; it does not save a tariff, assign crew or commit a recovery.</HelpNote>
    <HelpH2>Step-by-step: inspect and calculate</HelpH2>
    <HelpStep n={1}>From <strong>Live</strong>, open <strong>Legality → Cost Templates</strong>. Read the Cost ID / Description, Category / Source, Unit price and Revision / Status columns. Templates provide the standard starting examples. Use <strong>Cost Sets</strong> to inspect a selected operational set and its member revisions.</HelpStep>
    <HelpScreenshot src="/help/screenshots/recovery-cost-catalogue-Ver1.png" alt="Public Cost Templates catalogue showing cost IDs, units, revision status and illustrative prices" caption="Real public Cost Templates view. The inspected environment has the original 17 types." />
    <HelpStep n={2}>Choose <strong>Expand cost</strong> on the required type. Review <strong>Calculation logic</strong>, Currency, Unit, Unit price, Effective from/to and Reference. For guarantee pay, inspect the Guarantee floor and Overtime tiers; for standby, inspect the factor, cutoff and linked GH policy revision. Required inputs depend on the selected calculation logic.</HelpStep>
    <HelpStep n={3}>Scroll to <strong>Calculation Workbench</strong>. Read its <strong>Saved revision</strong>. Template mode loads a <strong>Default case</strong>; replace those illustrative inputs with the case being assessed. Enter credit in decimal <strong>hours</strong>, not HH:MM or block time: 6.75 means 6 hours 45 minutes. Report and departure fields use UTC.</HelpStep>
    <HelpStep n={4}>For guarantee or airport standby, choose <strong>Single crew</strong> or <strong>Compare crews</strong>. In comparison mode, common duty inputs are shared; each crew has its own Monthly credit before, Removed unprotected credit, optional hourly rate and any baseline standby credit. Enter the actual before-state so already credited standby is not counted twice.</HelpStep>
    <HelpStep n={5}>Press <strong>Calculate</strong> or <strong>Compare costs</strong>. Read the before/after credit, incremental cash, formula explanation and breakdown. Check whether the result is Priced, Unpriced or Disabled. A displayed zero is valid only when complete inputs and an enabled, priced policy produce zero.</HelpStep>
    <HelpStep n={6}>For flight delay, enter <strong>Delay before (minutes)</strong> and <strong>Delay after (minutes)</strong>, then Calculate. For quantity or fixed types, enter Billable quantity or Qualifying event (0 or 1). Booking replacement uses the saved price/refund/fee parameters rather than a separate quantity field.</HelpStep>
    <HelpStep n={7}>When authorized to maintain tariffs, edit Parameters and choose <strong>Save new revision</strong>. In <strong>Cost Sets</strong>, use <strong>Manage cost membership</strong>, tick the intended instances and select each <strong>Revision</strong>, then Save. Cancel leaves membership unchanged. This is configuration maintenance; it is separate from Gantt Save.</HelpStep>
    <HelpScreenshot src="/help/screenshots/recovery-cost-membership-Ver1.png" alt="Cost Set membership dialog with instance checkboxes and pinned revision selectors" caption="Manage cost membership selects both the instance and revision. This capture inspected the dialog and cancelled without saving." />
    <HelpStep n={8}>Return to Recovery and inspect the chosen option’s <strong>Cost breakdown</strong>. Check that the method uses the intended cost types and correct quantities. The current recovery bridge does not use the full Cost Set/effective-date selection or automatically provide every workbench input. Use the separate Comparing recovery costs article to understand those integration limits.</HelpStep>
    <HelpH2>All 19 catalogue cost types</HelpH2>
    <p className="mb-3 text-xs leading-relaxed">The table lists the default logic. Most generic expense types also allow quantity, fixed or minimum logic in a configured revision. 1002 uses guarantee only; 1003 uses standby only; 2008 uses booking only; 3001 allows bands or quantity. Inspect the saved revision rather than assuming its calculator still matches the default.</p>
    <div className="overflow-x-auto"><table className="w-full table-fixed border-collapse text-left text-xs" data-testid="help-cost-type-table">
      <thead><tr className="border-b border-border bg-muted"><th className="w-20 p-2">Type</th><th className="w-40 p-2">Name / default logic</th><th className="p-2">Calculation and billable unit</th></tr></thead>
      <tbody>{types.map(([code, name, logic, detail]) => <tr key={code} className="border-b border-border" data-testid={`help-cost-type-${code}`}><td className="p-2 align-top font-mono tabular-nums">{code}</td><td className="p-2 align-top"><strong>{name}</strong><span className="mt-1 block text-muted-foreground">{logic}</span></td><td className="p-2 align-top leading-relaxed">{detail}</td></tr>)}</tbody>
    </table></div>
    <HelpH2>The seven calculation methods</HelpH2>
    <HelpNote><strong>Quantity:</strong> quantity × rate. <strong>Fixed:</strong> qualifying event 0 or 1 × price; two is rejected. <strong>Minimum:</strong> zero quantity costs zero; otherwise max(quantity, minimum billable quantity) × rate. Example: quantity 2, minimum 4 and rate USD 10 gives USD 40. Minimum is an available alternative, not the active seeded default for every generic type.</HelpNote>
    <HelpH2>Guaranteed pay: why the same duty can have different cash cost</HelpH2>
    <p className="text-xs leading-relaxed">Let Pay(c) be the pay at total credit c. The guarantee pays the floor at the base hourly rate; credit above the floor earns the configured tier multipliers. The incremental result is <strong>Pay(before − removed + added) − Pay(before)</strong>. The optional crew hourly rate overrides the policy rate. Removed unprotected credit must not exceed the baseline credit.</p>
    <HelpNote>Worked example using the illustrative 85-hour guarantee and USD 100 rate: Crew A starts at 84 hours and receives 6.75, reaching 90.75. The first added hour remains within the guarantee; five hours earn 1.2× and 0.75 earns 1.5×. Incremental cash = 5 × 120 + 0.75 × 150 = <strong>USD 712.50</strong>. Crew B starts at 70 and reaches 76.75, still below the guarantee: <strong>USD 0</strong> incremental cash. This says nothing about which crew is qualified or operationally available.</HelpNote>
    <HelpScreenshot src="/help/screenshots/recovery-cost-guarantee-Ver3.png" alt="Guarantee Workbench comparing the same added duty for crews with different monthly credit" caption="Real calculator result: the same additional credit produces USD 712.50 for Crew A and USD 0 for Crew B under the illustrative saved policy." />
    <HelpH2>Airport standby: calculate credit before pricing pay</HelpH2>
    <p className="text-xs leading-relaxed"><strong>Standby credit = max(report-to-departure minutes − cutoff, 0) × factor ÷ 60.</strong> After credit = before − removed + standby credit + pairing credit − standby credit already in baseline. Cash = Pay(after) − Pay(before), using the linked enabled GH policy in the same currency. Departure must not precede report. Removed credit plus baseline standby credit cannot exceed the before total.</p>
    <HelpNote>Report 07:00Z, depart 10:00Z, cutoff 60 minutes and factor 0.5 gives (180 − 60) × 0.5 ÷ 60 = <strong>1 hour</strong> standby credit. Add pairing credit 5.75 to obtain 6.75 hours before subtracting any baseline standby credit. With no removal/baseline standby, the 84-hour and 70-hour crews reproduce the guarantee example above. Case 102’s current recovery estimate uses Day-off recall, not this full calculation.</HelpNote>
    <HelpScreenshot src="/help/screenshots/recovery-cost-standby-Ver3.png" alt="Airport standby Workbench showing eligible standby, one hour of standby credit and two crew cash results" caption="The standby workbench separates eligible elapsed time, credited time and incremental pay." />
    <HelpH2>Delay bands: price the change, including the threshold crossing</HelpH2>
    <p className="text-xs leading-relaxed">For the illustrative policy, <strong>C(m) = min(m, 120) × 60 + max(m − 120, 0) × 25</strong>. The result is C(delay after) − C(delay before). Increasing from 120 to 140 minutes costs 20 × 25 = <strong>USD 500</strong>. Increasing from 100 to 150 costs 20 × 60 + 30 × 25 = <strong>USD 1,950</strong>. If the after delay is lower, the formula can return a saving. It does not automatically sum every flight in a pairing or calculate passenger/connection consequences.</p>
    <HelpScreenshot src="/help/screenshots/recovery-cost-delay-Ver1.png" alt="Flight-delay Workbench calculating the incremental cost from 120 to 140 minutes" caption="The standalone delay calculator is available; case 104’s automatic Recovery estimate has not supplied these inputs yet." />
    <HelpH2>Booking replacement, rounding and incomplete prices</HelpH2>
    <HelpNote><strong>Booking:</strong> new booking price − refund + change fee. With original booking USD 140, replacement USD 160, refund USD 140 and no fee, net impact is USD 20. The original amount is a validation limit on the refund, not another charge. Calculations retain fractional quantities until final rounding to two decimal places. Missing price returns Unpriced; disabling the cost or its linked GH policy returns Disabled. Currency conversion is not performed.</HelpNote>
    <HelpWarning>Do not add every catalogue type to every solution. Define the actual additional billable events, avoid charging the same change twice, keep savings and decision penalties distinguishable, and compare alternatives against the same baseline, time scope, currency and policy revisions. A low subtotal with missing inputs is not a complete solution cost.</HelpWarning>
  </>
}
