import { HelpH2, HelpStep, HelpNote, HelpWarning, HelpScreenshot } from '../../help-article'

export default function RecoveryArticle() {
  return <>
<HelpNote>Availability: these cases require the Assignment Overlap recovery update. If Recovery shows only Roster transfer or exchange, Standby Crew callout and Cross-base positioning for an overlap, your build does not yet include cases 103 and 104. Ask your administrator to update it.</HelpNote>
<HelpStep n={1}>In Live Alert Center, select the recoverable <strong>1001</strong> alert for the ground task and flying pairing, then open <strong>Recovery → Standby Crew callout</strong>.</HelpStep>
<HelpStep n={2}>Review replacement crews whose loaded <strong>SBY</strong> window contains the affected pairing’s start. The candidate must satisfy the rank check and have no other loaded overlapping task. Fleet mismatches remain visible warnings. The list is limited to loaded crews and does not prove that a different-base crew can physically reach the departure airport.</HelpStep>
<HelpStep n={3}>Review <strong>Detail</strong>, the rule result, <strong>Cost breakdown</strong>, and <strong>Preview</strong>. This reuses the existing standby method. The selected SBY task is retained, with a yellow <strong>C</strong> indicator and a callout exception; other overlaps are not intentionally permitted.</HelpStep>
<HelpStep n={4}>Check the chosen executable crew and select <strong>Apply selected option</strong>. The draft removes the complete affected pairing from the original crew, assigns it to the standby crew, and marks the retained SBY as a callout. The original crew’s ground task stays. The pairing’s flight sequence is not rebuilt.</HelpStep>
<HelpStep n={5}>Use <strong>Save</strong>, then verify replacement coverage on every leg, the retained callout marker, the original crew’s ground task, and the refreshed alerts and crew totals. An unsaved preview or draft is not the completed roster.</HelpStep>
<HelpWarning>Pricing is partial: saved pilot ASBY at the pairing base uses the airport-standby calculator and its pinned guaranteed-hours (GH) policy. The estimate uses saved calendar-month credit, not the roster-period MCred badge. Missing context or policy is Unpriced, not zero. Other standby contexts are not certified by this path. The quote is incremental planned pay, not total operational cost or proof of payroll posting.</HelpWarning>

<HelpH2>Operational theory: transfer ownership, preserve the flying plan</HelpH2>
<HelpNote>Standby provides an alternative crew resource. This case moves the entire affected pairing to that crew; it does not shorten the original ground task or split the pairing. The retained SBY marker records that standby was called out, so the intentional SBY/flying relationship differs from an unrelated overlapping duty.</HelpNote>
<HelpH2>Worked complex case and review sequence</HelpH2>
<p className="text-xs leading-relaxed">Illustrative baseline: Crew A has a ground task ending 15:00Z and a two-leg pairing starting before that time. Crew B has an SBY window containing the pairing start. Open the 1001 alert for A, choose Standby Crew callout, and inspect B’s complete day and the following duty. Confirm B can report at the required station, holds the required qualification and can complete both legs and the release. A matching SBY window alone does not prove these operational facts.</p>
<p className="text-xs leading-relaxed">Open Detail and compare the complete pairing before/after. Inspect the cost popup: review the saved month, before/after projected credit, already-credited standby deduction and pinned policy revisions. Select B’s checkbox, then Preview. Expect A’s ground task to remain, the whole pairing to move to B and B’s SBY to remain marked as a callout. If any leg appears uncovered or another duty overlaps, stop and reassess the option.</p>
<HelpH2>Acceptance after saving</HelpH2>
<HelpNote>Inspect every leg’s crew coverage, not only the first visible roster bar. Confirm A no longer owns the moved pairing, B owns it once, and the callout marker remains after refresh. Recheck B’s downstream rest and monthly credit and A’s remaining duties. Any actual crew notification or reporting arrangement must follow the operator’s process; the documented Apply action stages a draft and is not proof that a crew has acknowledged a callout.</HelpNote>
<HelpH2>GH comparison — ADD demonstration</HelpH2>
<HelpNote>For J4002’s pairing 152056, three ADD/CA/7M8 candidates have ASBY on 24 September, 02:00–10:00 UTC. Under the configured 85-hour GH policy, the priced shortlist demonstrates how the same callout has different incremental pay. These are prepared demo rosters, not records of paid overtime.</HelpNote>
<ul className="list-disc space-y-1 pl-5 text-xs"><li><strong>J4011:</strong> planned month credit 08:00 → projected payable credit 20:20; <strong>US$0</strong> extra GH pay.</li><li><strong>J4012:</strong> 76:35 → 88:55; <strong>US$470</strong>, crossing the GH floor.</li><li><strong>J4013:</strong> 87:05 → 99:25; <strong>US$1,762.50</strong>, already above GH.</li></ul>
<HelpNote>The example adds pairing credit 15:15 plus callout standby credit 01:05, less the 04:00 standby already included in the baseline: net 12:20. The policy rate is US$100/hour, multiplied by 1.2 for credit above 85 through 90 hours, then 1.5 above 90. Click each candidate’s cost for the inputs and policy revisions. The shortlist can change when saved duties or policy revisions change.</HelpNote>
<HelpWarning>Selection and pricing do not prove legality. These demo rosters have soft legality findings. A sick-crew overlap is still required to open Recovery; merely assigning standby does not create a 1001 alert. Projected payable credit is not a claim that Apply rewrites retained ASBY roster credit. Preview is not Save or crew notification.</HelpWarning>
<HelpScreenshot src="/help/screenshots/s1-gh-standby-list-Ver1.png" alt="Three selectable ADD standby candidates with different guaranteed-hours pay estimates" caption="GH comparison: the same pairing can cost US$0, US$470 or US$1,762.50 depending on the candidate’s saved monthly credit." />
  </>
}
