import { HelpH2, HelpStep, HelpNote, HelpWarning } from '../../help-article'

export default function RecoveryArticle() {
  return <>
<HelpWarning>Partial — recovery uses the cost library, but the current bridge does not provide a complete operational or payroll comparison for cases 102–104. A numeric result, a green status or Best cost is not proof that every relevant cost was priced.</HelpWarning>
<HelpStep n={1}>Compare <strong>Cost</strong> together with crew impact, Cancel/Add counts and <strong>Stability</strong>. Options are reordered by the calculated amount; the tree’s star marks the lowest estimate. Rule status and warnings must be reviewed independently of price.</HelpStep>
<HelpStep n={2}>Click the option’s cost amount to open <strong>Cost breakdown</strong>. Read each cost rule, Qty, Amount and status: <strong>priced</strong>, <strong>unpriced</strong>, <strong>disabled</strong> or <strong>no rev</strong>. An incomplete quote is shown as Unpriced and excluded from the lowest-priced star; missing amounts are unknown costs, not free services. Read the notes as well as the header.</HelpStep>
<HelpStep n={3}>Review the case-specific gaps. <strong>102</strong> uses the airport standby/GH calculator for saved pilot ASBY at the pairing base, with calendar-month credit and a pinned GH revision. Other contexts remain limited. <strong>103</strong> estimates incremental GH pay for both crews in supported saved same-base pilot swaps: each outgoing pairing credit is removed and each incoming pairing credit is added. Missing identities, credit or policy leave the quote Unpriced. <strong>104</strong> supplies no delay duration; it can receive a roster-change penalty even though its roster-change metric is zero.</HelpStep>
<HelpStep n={4}>Before choosing, confirm the applicable tariffs, quantities and currency and account for omitted costs. An <strong>unavailable</strong> breakdown means no complete quote is available, not a zero-price option. Mixed currencies are shown separately in the breakdown; the ranking does not perform currency conversion. Do not rank incomparable amounts as a financial recommendation.</HelpStep>
<HelpH2>What the total measures</HelpH2>
<HelpNote>For the supported standby and swap paths, the displayed quote is incremental planned GH pay, not complete operational cost. Other recovery totals sum priced library components, including configured change and follow-on penalties, less any DHD savings. It is the same value as Direct cost in the current model; it is not a separately computed cash-plus-virtual-cost total. These penalties are decision weights expressed as amounts, so the total is not necessarily an invoice or incremental crew pay.</HelpNote>
<HelpH2>What Stability measures</HelpH2>
<HelpNote>Stability = 100 − 100 × (0.30 × cancelled + 0.20 × added + 0.15 × changed + 0.35 × follow-on impact) ÷ loaded roster groups, bounded to 0–100%. The score depends on the loaded scope. Compare solutions generated from the same scope. Follow-on impact is a limited heuristic, not a full downstream recovery analysis.</HelpNote>
<HelpWarning>Airport ASBY pricing selects default instance 1 and an effective standby revision for the departure date, with its pinned GH policy. Supported swap GH pricing uses the default effective guarantee policy. Other recovery costs still use the first stored instance and latest revision. Recovery does not select a planner’s Cost Set. Configuring a richer calculator elsewhere does not mean Recovery supplies all its required inputs.</HelpWarning>
  </>
}
