/**
 * PBS-33xx — NPBS-Legend crew bids simulation.
 *
 * Replays each crew's legacy NPBS bids through the real portal UI: logs in as the
 * crew (Employee #), opens each bid page, places every mapped, tiered property via
 * full UI clicks, and asserts it lands in the EXISTING list.
 *
 * Data: e2e/fixtures/pbs/npbs-bids-jun2026.json (generated by
 * e2e/utils/npbs/generate-fixture.mjs from docs/test-cases/CLASS-BidsReport_*.txt).
 *
 * Project rule #7: we never change product code to fit. Any login/UI blocker or
 * unmappable control is recorded to e2e/results/npbs-issues/<employeeId>.json and
 * surfaced; product code is untouched.
 *
 * Runs SERIALLY (one login per crew) to avoid bursting the auth lockout.
 */
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
// Live-stream-aware test object: streams the headed browser when PW_STREAM_URL is
// set (R'Bot's create_crew_bids run), a no-op otherwise. Identical to the stock
// @playwright/test object when streaming is off.
import { test, expect } from '../../utils/live-stream/test'
import { PbsLoginPage } from '../../pages/pbs-portal/pbs-login-page'
import { BidWorkbenchPage, type FixtureProperty, type BidPageKind } from '../../pages/pbs-portal/bid-workbench-page'

const here = path.dirname(fileURLToPath(import.meta.url))
const repoRoot = path.resolve(here, '../../..')
// R'Bot's create_crew_bids run points CREWBIDS_FIXTURE at a scoped fixture; the
// default is the committed June fixture for standalone/CI runs.
const fixturePath = process.env.CREWBIDS_FIXTURE
  ? path.resolve(process.env.CREWBIDS_FIXTURE)
  : path.join(repoRoot, 'e2e/fixtures/pbs/npbs-bids-jun2026.json')
const issuesDir = process.env.CREWBIDS_ISSUES_DIR
  ? path.resolve(process.env.CREWBIDS_ISSUES_DIR)
  : path.join(repoRoot, 'e2e/results/npbs-issues')
const cleanupAfterRun = process.env.CREWBIDS_CLEANUP === 'true'

interface FixtureCrew {
  employeeId: string
  category: string
  base: string
  rank: string
  seniority: number | null
  context: string
  properties: FixtureProperty[]
}
interface Fixture {
  period: string
  source: string
  sourceSha256?: string
  dateMode?: 'no-shift' | 'shifted'
  runId?: string
  buckets: string[]
  crew: FixtureCrew[]
}

const fixture: Fixture = JSON.parse(fs.readFileSync(fixturePath, 'utf-8'))
const expectedRunId = process.env.CREWBIDS_RUN_ID
if (expectedRunId && fixture.runId && fixture.runId !== expectedRunId) {
  throw new Error(`CREWBIDS_RUN_ID must match fixture runId (${fixture.runId})`)
}
if (!/^\d{6}$/.test(fixture.period)) {
  throw new Error(`Fixture period must use YYYYMM, received ${fixture.period}`)
}
const runId = expectedRunId ?? fixture.runId ?? `npbs-legacy-${Date.now()}`
const sourceSha256 = fixture.sourceSha256 ?? 'not-recorded'
const dateMode = fixture.dateMode ?? 'shifted'
const PERIOD_ABBR = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
const periodMonth = Number(fixture.period.slice(4, 6))
const expectedPeriodStatus = `Bidding open for ${PERIOD_ABBR[periodMonth - 1]} ${fixture.period.slice(0, 4)}`

// Pages each crew submits on. R'Bot's create_crew_bids run sets CREWBIDS_PAGES to
// 'days-off,pairing,line' (reserve intentionally skipped); unset = all four.
const ALL_PAGES: BidPageKind[] = ['days-off', 'pairing', 'line', 'reserve']
const PAGE_ORDER: BidPageKind[] = process.env.CREWBIDS_PAGES
  ? (process.env.CREWBIDS_PAGES.split(',').map((s) => s.trim()).filter(Boolean) as BidPageKind[])
  : ALL_PAGES

const groupByPage = (props: FixtureProperty[]): Map<BidPageKind, FixtureProperty[]> => {
  const map = new Map<BidPageKind, FixtureProperty[]>()
  for (const kind of PAGE_ORDER) {
    const subset = props.filter((p) => p.page === kind)
    if (subset.length) map.set(kind, subset)
  }
  return map
}

/** UI login with a light retry to tolerate the per-account auth lockout window. */
const loginAsCrew = async (page: import('@playwright/test').Page, employeeId: string): Promise<boolean> => {
  const login = new PbsLoginPage(page)
  for (let attempt = 1; attempt <= 3; attempt++) {
    await login.goto()
    await login.login(employeeId, 'rois')
    try {
      await page.waitForURL(/\/dashboard$/, { timeout: 20_000 })
      return true
    } catch {
      const terminalAuthError = page.getByText(/status code (401|403)|invalid user code or password|cannot access the portal/i)
      if (await terminalAuthError.count()) return false
      if (attempt < 3) await page.waitForTimeout(20_000) // lockout window backoff
    }
  }
  return false
}

const writeIssues = (employeeId: string, payload: unknown): void => {
  fs.mkdirSync(issuesDir, { recursive: true })
  fs.writeFileSync(path.join(issuesDir, `${employeeId}.json`), JSON.stringify(payload, null, 2) + '\n')
}

const removePriorArtifacts = (employeeId: string): void => {
  fs.rmSync(path.join(issuesDir, `${employeeId}.json`), { force: true })
}

// NOTE: run with --workers=1 for serial execution (one login at a time, to avoid
// the per-account auth lockout). We deliberately do NOT use describe.serial mode,
// because that skips all remaining crew after the first failure — each crew must
// run and record its own result independently (project rule #7).

// Group crew by bucket for readable reporting.
const buckets = fixture.buckets
for (const bucket of buckets) {
  const bucketCrew = fixture.crew.filter((c) => `${c.base}-${c.rank}` === bucket)

  test.describe(`NPBS bids — ${bucket}`, () => {
    bucketCrew.forEach((crew, idx) => {
      const globalIndex = fixture.crew.indexOf(crew)
      const testId = `PBS-${3301 + globalIndex}`
      test(`${testId} — ${crew.category} #${crew.employeeId} (${crew.context}) places ${crew.properties.length} bids`, async ({ page }) => {
        test.setTimeout(300_000) // pairing panel is slow on the remote demo DB

        removePriorArtifacts(crew.employeeId)
        const wb = new BidWorkbenchPage(page, { crewId: crew.employeeId, testId })
        const startedAt = new Date().toISOString()
        const startedMs = Date.now()
        const stageDurationsMs: Record<string, number> = {}
        const issues: Array<Record<string, unknown>> = []
        const placedProps: FixtureProperty[] = []
        const touchedKinds = new Set<BidPageKind>()
        const cleanupCompletedKinds: BidPageKind[] = []
        let loggedIn = false
        let fatalError: Error | null = null

        try {
          const loginStarted = Date.now()
          loggedIn = await loginAsCrew(page, crew.employeeId)
          stageDurationsMs.login = Date.now() - loginStarted
          if (!loggedIn) {
            const image = await wb.snapshotFailure('login-failed')
            issues.push({ page: 'login', reason: 'login-failed', image })
            throw new Error(`login failed for crew #${crew.employeeId}`)
          }

          const periodStatus = page.getByTestId('bidding-calendar-current-period-status')
          await expect(periodStatus).toContainText(expectedPeriodStatus, { timeout: 30_000 })

          const byPage = groupByPage(crew.properties)
          for (const [kind, props] of byPage) {
            const pageStarted = Date.now()
            try {
              await wb.goto(kind)
              await page.waitForTimeout(750)
              const existingCount = await wb.existingCountAcrossTiers(kind)
              if (existingCount !== 0) {
                const image = await wb.snapshotFailure(`existing-not-zero-${kind}`)
                issues.push({ page: kind, reason: `preflight-existing-not-zero: ${existingCount}`, image })
                throw new Error(`#${crew.employeeId} ${kind} has ${existingCount} existing bids; refusing to delete`)
              }
            } catch (error) {
              const message = String(error)
              if (message.includes('refusing to delete')) throw error
              const image = await wb.snapshotFailure(`page-load-${kind}`)
              for (const prop of props) {
                issues.push({ tier: prop.tier, name: prop.name, code: prop.propertyCode, page: kind, reason: `page-load-failed: ${message.slice(0, 120)}`, image })
              }
              continue
            } finally {
              stageDurationsMs[`page:${kind}`] = Date.now() - pageStarted
            }

            for (const prop of props) {
              const propertyStarted = Date.now()
              const result = await wb.placeProperty(prop)
              if (!result.placed) {
                issues.push({
                  tier: prop.tier,
                  name: prop.name,
                  code: prop.propertyCode,
                  page: kind,
                  predicate: prop.predicate,
                  reason: result.reason,
                  image: result.image,
                  durationMs: Date.now() - propertyStarted,
                })
                continue
              }
              touchedKinds.add(kind)
              try {
                await wb.assertExisting(prop)
                placedProps.push(prop)
              } catch (error) {
                const image = await wb.snapshotFailure('existing-assertion', prop)
                issues.push({
                  tier: prop.tier,
                  name: prop.name,
                  code: prop.propertyCode,
                  page: kind,
                  predicate: prop.predicate,
                  reason: `existing-assertion-failed: ${String(error).slice(0, 160)}`,
                  image,
                  durationMs: Date.now() - propertyStarted,
                })
              }
            }
          }
        } catch (error) {
          fatalError = error instanceof Error ? error : new Error(String(error))
        } finally {
          if (loggedIn) {
            if (cleanupAfterRun) {
              for (const kind of touchedKinds) {
                try {
                  await wb.goto(kind)
                  await wb.clearExisting(kind)
                  // Each poll reloads the server-backed draft. Row removal is
                  // optimistic and the remote cache can lag the successful
                  // DELETE response, so counting the same page instance is not proof.
                  await expect.poll(
                    async () => {
                      await wb.goto(kind)
                      return wb.existingCountAcrossTiers(kind)
                    },
                    {
                      timeout: 90_000,
                      intervals: [1_000, 2_000, 5_000],
                      message: `Expected #${crew.employeeId} ${kind} to return to Existing=0 after cleanup`,
                    },
                  ).toBe(0)
                  cleanupCompletedKinds.push(kind)
                } catch (error) {
                  const image = await wb.snapshotFailure(`cleanup-failed-${kind}`)
                  issues.push({ page: kind, reason: `cleanup-failed: ${String(error).slice(0, 160)}`, image })
                  fatalError ??= error instanceof Error ? error : new Error(String(error))
                }
              }
            }

            const logoutStarted = Date.now()
            try {
              await new PbsLoginPage(page).logout()
            } catch (error) {
              const image = await wb.snapshotFailure('logout-failed')
              issues.push({ page: 'logout', reason: `logout-failed: ${String(error).slice(0, 160)}`, image })
              fatalError ??= error instanceof Error ? error : new Error(String(error))
            }
            stageDurationsMs.logout = Date.now() - logoutStarted
          }

          const endedAt = new Date().toISOString()
          writeIssues(crew.employeeId, {
            runId,
            source: fixture.source,
            sourceSha256,
            period: fixture.period,
            dateMode,
            employeeId: crew.employeeId,
            category: crew.category,
            context: crew.context,
            startedAt,
            endedAt,
            durationMs: Date.now() - startedMs,
            stageDurationsMs,
            totalProperties: crew.properties.length,
            placed: placedProps.length,
            placedDetail: placedProps.map((prop) => ({ tier: prop.tier, code: prop.propertyCode, name: prop.name })),
            cleanupRequested: cleanupAfterRun,
            cleanupTouchedKinds: Array.from(touchedKinds),
            cleanupCompletedKinds,
            issues,
          })
        }

        if (fatalError) throw fatalError
        expect(placedProps.length, `no bids placed for #${crew.employeeId}; see e2e/results/npbs-issues/${crew.employeeId}.json`).toBeGreaterThan(0)
      })
    })
  })
}
