// ─── Explore: layover place recommendations (doc/Explore Ver1) ───────────────
// Pure, dependency-light logic + curated dataset for the "Explore" feature.
//
// For each upcoming layover we know the destination airport and the crew hotel
// (from the captured roster, see portalCapture.HotelBooking). Crew pick a few
// interests (café, Thai food, shopping, …) and Explore shows the TOP-RATED
// places of each interest within a short walk of the hotel — "15-min walking
// distance top 3 rated attraction per crew definition" (Explore Ver1).
//
// Data model: this mirrors a Google-Maps Places pull, keyed by destination
// airport. The dataset below is a CURATED SAMPLE seeded for the crew hotels we
// have captured (the backend mining job replaces it with a live Places pull,
// same as the landmark-image pipeline). Ratings / walk times are representative
// sample values — the UI footnotes this so it is never mistaken for live data.

// ─── Interest categories (the "pre-defined interested things") ────────────────
// 3–10 options, per Explore Ver1. `key` is what we persist in crew preferences.
export type ExploreCategory =
  | 'cafe'
  | 'food'
  | 'thai'
  | 'shopping'
  | 'sightseeing'
  | 'nature'
  | 'bar'
  | 'spa'
  | 'fitness'
  | 'convenience';

export interface CategoryDef {
  key: ExploreCategory;
  label: string;
  emoji: string;
}

export const EXPLORE_CATEGORIES: CategoryDef[] = [
  { key: 'cafe', label: 'Café', emoji: '☕' },
  { key: 'food', label: 'Local Food', emoji: '🍜' },
  { key: 'thai', label: 'Thai Food', emoji: '🍛' },
  { key: 'shopping', label: 'Shopping', emoji: '🛍️' },
  { key: 'sightseeing', label: 'Sightseeing', emoji: '📸' },
  { key: 'nature', label: 'Nature & Parks', emoji: '🌳' },
  { key: 'bar', label: 'Bar & Nightlife', emoji: '🍸' },
  { key: 'spa', label: 'Spa & Onsen', emoji: '♨️' },
  { key: 'fitness', label: 'Fitness', emoji: '🏋️' },
  { key: 'convenience', label: 'Convenience', emoji: '🏪' },
];

const CATEGORY_BY_KEY: Record<string, CategoryDef> = Object.fromEntries(
  EXPLORE_CATEGORIES.map(c => [c.key, c]),
);

/** Default interests for a crew who has not customised them yet. */
export const DEFAULT_EXPLORE_PREFS: ExploreCategory[] = ['cafe', 'food', 'shopping'];

/** A single place near a crew hotel (a Google-Maps-style result). */
export interface Place {
  name: string;
  category: ExploreCategory;
  rating: number; // 0–5, Google-style
  reviews?: number;
  walkMins: number; // walking minutes from the crew hotel
  note?: string; // short descriptor
  area?: string; // landmark/anchor, e.g. "JR Chitose Station"
}

/** A category's recommendations for one layover (already filtered + ranked). */
export interface ExploreSuggestion {
  category: CategoryDef;
  places: Place[];
}

// Default search constraints from Explore Ver1: "15 mins walking distance top 3".
export const MAX_WALK_MINS = 15;
export const TOP_N = 3;

// ─── Curated place dataset, keyed by destination airport ─────────────────────
// The dataset itself lives in explorePlacesData.ts, AUTO-GENERATED by the
// backend places-mining job (backend/mine/buildPlaces.py) so it can be refreshed
// from Google Maps without touching this logic. It covers every city the crew
// lay over in (keys are uppercase IATA codes). Re-export it so callers keep
// importing { PLACES_BY_AIRPORT } from this module.
import { PLACES_BY_AIRPORT } from './explorePlacesData';
export { PLACES_BY_AIRPORT };

/** A disambiguated map search string for a place: "Name, Area, City". */
export function placeMapsQuery(place: Place, city?: string): string {
  return [place.name, place.area, city].filter(Boolean).join(', ');
}

/**
 * Google Maps "quick navigation" deep link to a recommended place. Uses the
 * universal Maps URL (api=1) so it opens turn-by-turn directions in the Google
 * Maps app when installed and falls back to the browser otherwise. Destination
 * is the disambiguated "Name, Area, City" query (we hold no lat/lng).
 */
export function placeDirectionsUrl(place: Place, city?: string): string {
  const dest = encodeURIComponent(placeMapsQuery(place, city));
  return `https://www.google.com/maps/dir/?api=1&destination=${dest}`;
}

/** Our own URL scheme — lets Google Maps bounce back to R'Bot (see Info.plist). */
export const APP_URL_SCHEME = 'rbot://';

/**
 * Google Maps x-callback deep link. Because layover spots are within a short
 * walk, it opens in walking mode — and crucially passes x-source/x-success so
 * the Google Maps app shows a "‹ R'Bot" back button (top-left) that returns the
 * crew straight to the app instead of leaving them stranded in Maps. Only opens
 * when the Google Maps app is installed; callers fall back to placeDirectionsUrl.
 */
export function placeDirectionsAppUrl(place: Place, city?: string): string {
  const dest = encodeURIComponent(placeMapsQuery(place, city));
  const back = encodeURIComponent(APP_URL_SCHEME);
  const source = encodeURIComponent("R'Bot");
  return (
    `comgooglemaps-x-callback://?daddr=${dest}` +
    `&directionsmode=walking&x-success=${back}&x-source=${source}`
  );
}

/** Do we have curated places for this airport yet? */
export function hasPlaces(airport: string | undefined): boolean {
  if (!airport) return false;
  const list = PLACES_BY_AIRPORT[airport.trim().toUpperCase()];
  return Array.isArray(list) && list.length > 0;
}

/** Resolve a category key to its label/emoji definition (or undefined). */
export function categoryDef(key: string): CategoryDef | undefined {
  return CATEGORY_BY_KEY[key];
}

/**
 * Top-rated places per crew interest for a layover at `airport`.
 *
 * For each preferred category we keep only places within `maxWalkMins` of the
 * hotel, rank by rating (then by review count, then shorter walk), and take the
 * top `topN`. Categories with no nearby places are omitted. Preference order is
 * preserved so the crew sees their interests in the order they picked them.
 */
export function suggestionsFor(
  airport: string | undefined,
  prefs: string[],
  opts: { maxWalkMins?: number; topN?: number } = {},
): ExploreSuggestion[] {
  const maxWalkMins = opts.maxWalkMins ?? MAX_WALK_MINS;
  const topN = opts.topN ?? TOP_N;
  const list = airport ? PLACES_BY_AIRPORT[airport.trim().toUpperCase()] : undefined;
  if (!list || !list.length) return [];

  const out: ExploreSuggestion[] = [];
  for (const key of prefs) {
    const def = CATEGORY_BY_KEY[key];
    if (!def) continue;
    const places = list
      .filter(p => p.category === key && p.walkMins <= maxWalkMins)
      .sort(
        (a, b) =>
          b.rating - a.rating ||
          (b.reviews ?? 0) - (a.reviews ?? 0) ||
          a.walkMins - b.walkMins,
      )
      .slice(0, topN);
    if (places.length) {
      out.push({ category: def, places });
    }
  }
  return out;
}
