-- Test crew batch: 40 pilots (20 CA, 20 FO), base ADD, fleet 7M8, nationality ET.
-- Idempotent (safe to re-run): crew.crew_id has a unique index; crew_base/crew_fleet/crew_rank
-- guarded with `where not exists`. Generated by .agents/skills/141-crew-seed-generator from
-- fixtures/ethiopia-add-7m8.json — J-prefixed crew_id is a deliberate test-data marker
-- (real F8 crew_ids are plain numeric; K1xxx/T2xxx are prior test batches from the same skill).
-- Reference rows (airport ADD, base ADD, fleet 7M8, rank CA/FO) already exist — not touched here.
-- Run against the target schema's DATABASE_URL, e.g.:
--   cd live-server && set -a; source .env >/dev/null 2>&1; set +a
--   node -e "require('pg')" # sanity: pg client available
--   psql "$DATABASE_URL" -f ../sql/seed/2026-09-10-crew-add-j4001-j4040-add-7m8.sql
-- Ethiopia / ADD / 7M8: 40 crew (20 CA, 20 FO), base ADD, fleet 7M8
insert into crew (crew_id, first_name, last_name, gender, division, empl_dt, nationality, filiale, status)
  values ('J4001', 'Meseret', 'Gebremariam', 'F', 'P', '2023-01-09', 'ET', 'F8', 0)
  on conflict (crew_id) do nothing;
insert into crew_base (crew_id, base, eff_dt, is_prime_base)
  select 'J4001', 'ADD', '2023-01-09', 1
  where not exists (select 1 from crew_base where crew_id = 'J4001');
insert into crew_fleet (crew_id, fleet_specific, eff_dt)
  select 'J4001', '7M8', '2023-01-09'
  where not exists (select 1 from crew_fleet where crew_id = 'J4001');
insert into crew_rank (crew_id, rank, eff_dt, position, division)
  select 'J4001', 'CA', '2023-01-09', 'CA', 'P'
  where not exists (select 1 from crew_rank where crew_id = 'J4001');

insert into crew (crew_id, first_name, last_name, gender, division, empl_dt, nationality, filiale, status)
  values ('J4002', 'Getnet', 'Kifle', 'M', 'P', '2023-01-15', 'ET', 'F8', 0)
  on conflict (crew_id) do nothing;
insert into crew_base (crew_id, base, eff_dt, is_prime_base)
  select 'J4002', 'ADD', '2023-01-15', 1
  where not exists (select 1 from crew_base where crew_id = 'J4002');
insert into crew_fleet (crew_id, fleet_specific, eff_dt)
  select 'J4002', '7M8', '2023-01-15'
  where not exists (select 1 from crew_fleet where crew_id = 'J4002');
insert into crew_rank (crew_id, rank, eff_dt, position, division)
  select 'J4002', 'CA', '2023-01-15', 'CA', 'P'
  where not exists (select 1 from crew_rank where crew_id = 'J4002');

insert into crew (crew_id, first_name, last_name, gender, division, empl_dt, nationality, filiale, status)
  values ('J4003', 'Mesfin', 'Ayele', 'M', 'P', '2023-01-21', 'ET', 'F8', 0)
  on conflict (crew_id) do nothing;
insert into crew_base (crew_id, base, eff_dt, is_prime_base)
  select 'J4003', 'ADD', '2023-01-21', 1
  where not exists (select 1 from crew_base where crew_id = 'J4003');
insert into crew_fleet (crew_id, fleet_specific, eff_dt)
  select 'J4003', '7M8', '2023-01-21'
  where not exists (select 1 from crew_fleet where crew_id = 'J4003');
insert into crew_rank (crew_id, rank, eff_dt, position, division)
  select 'J4003', 'CA', '2023-01-21', 'CA', 'P'
  where not exists (select 1 from crew_rank where crew_id = 'J4003');

insert into crew (crew_id, first_name, last_name, gender, division, empl_dt, nationality, filiale, status)
  values ('J4004', 'Almaz', 'Belay', 'F', 'P', '2023-01-27', 'ET', 'F8', 0)
  on conflict (crew_id) do nothing;
insert into crew_base (crew_id, base, eff_dt, is_prime_base)
  select 'J4004', 'ADD', '2023-01-27', 1
  where not exists (select 1 from crew_base where crew_id = 'J4004');
insert into crew_fleet (crew_id, fleet_specific, eff_dt)
  select 'J4004', '7M8', '2023-01-27'
  where not exists (select 1 from crew_fleet where crew_id = 'J4004');
insert into crew_rank (crew_id, rank, eff_dt, position, division)
  select 'J4004', 'CA', '2023-01-27', 'CA', 'P'
  where not exists (select 1 from crew_rank where crew_id = 'J4004');

insert into crew (crew_id, first_name, last_name, gender, division, empl_dt, nationality, filiale, status)
  values ('J4005', 'Tsegaye', 'Wondimu', 'M', 'P', '2023-02-02', 'ET', 'F8', 0)
  on conflict (crew_id) do nothing;
insert into crew_base (crew_id, base, eff_dt, is_prime_base)
  select 'J4005', 'ADD', '2023-02-02', 1
  where not exists (select 1 from crew_base where crew_id = 'J4005');
insert into crew_fleet (crew_id, fleet_specific, eff_dt)
  select 'J4005', '7M8', '2023-02-02'
  where not exists (select 1 from crew_fleet where crew_id = 'J4005');
insert into crew_rank (crew_id, rank, eff_dt, position, division)
  select 'J4005', 'CA', '2023-02-02', 'CA', 'P'
  where not exists (select 1 from crew_rank where crew_id = 'J4005');

insert into crew (crew_id, first_name, last_name, gender, division, empl_dt, nationality, filiale, status)
  values ('J4006', 'Wondwossen', 'Tefera', 'M', 'P', '2023-02-08', 'ET', 'F8', 0)
  on conflict (crew_id) do nothing;
insert into crew_base (crew_id, base, eff_dt, is_prime_base)
  select 'J4006', 'ADD', '2023-02-08', 1
  where not exists (select 1 from crew_base where crew_id = 'J4006');
insert into crew_fleet (crew_id, fleet_specific, eff_dt)
  select 'J4006', '7M8', '2023-02-08'
  where not exists (select 1 from crew_fleet where crew_id = 'J4006');
insert into crew_rank (crew_id, rank, eff_dt, position, division)
  select 'J4006', 'CA', '2023-02-08', 'CA', 'P'
  where not exists (select 1 from crew_rank where crew_id = 'J4006');

insert into crew (crew_id, first_name, last_name, gender, division, empl_dt, nationality, filiale, status)
  values ('J4007', 'Tsehay', 'Sisay', 'F', 'P', '2023-02-14', 'ET', 'F8', 0)
  on conflict (crew_id) do nothing;
insert into crew_base (crew_id, base, eff_dt, is_prime_base)
  select 'J4007', 'ADD', '2023-02-14', 1
  where not exists (select 1 from crew_base where crew_id = 'J4007');
insert into crew_fleet (crew_id, fleet_specific, eff_dt)
  select 'J4007', '7M8', '2023-02-14'
  where not exists (select 1 from crew_fleet where crew_id = 'J4007');
insert into crew_rank (crew_id, rank, eff_dt, position, division)
  select 'J4007', 'CA', '2023-02-14', 'CA', 'P'
  where not exists (select 1 from crew_rank where crew_id = 'J4007');

insert into crew (crew_id, first_name, last_name, gender, division, empl_dt, nationality, filiale, status)
  values ('J4008', 'Endale', 'Aregawi', 'M', 'P', '2023-02-20', 'ET', 'F8', 0)
  on conflict (crew_id) do nothing;
insert into crew_base (crew_id, base, eff_dt, is_prime_base)
  select 'J4008', 'ADD', '2023-02-20', 1
  where not exists (select 1 from crew_base where crew_id = 'J4008');
insert into crew_fleet (crew_id, fleet_specific, eff_dt)
  select 'J4008', '7M8', '2023-02-20'
  where not exists (select 1 from crew_fleet where crew_id = 'J4008');
insert into crew_rank (crew_id, rank, eff_dt, position, division)
  select 'J4008', 'CA', '2023-02-20', 'CA', 'P'
  where not exists (select 1 from crew_rank where crew_id = 'J4008');

insert into crew (crew_id, first_name, last_name, gender, division, empl_dt, nationality, filiale, status)
  values ('J4009', 'Alemayehu', 'Mengistu', 'M', 'P', '2023-02-26', 'ET', 'F8', 0)
  on conflict (crew_id) do nothing;
insert into crew_base (crew_id, base, eff_dt, is_prime_base)
  select 'J4009', 'ADD', '2023-02-26', 1
  where not exists (select 1 from crew_base where crew_id = 'J4009');
insert into crew_fleet (crew_id, fleet_specific, eff_dt)
  select 'J4009', '7M8', '2023-02-26'
  where not exists (select 1 from crew_fleet where crew_id = 'J4009');
insert into crew_rank (crew_id, rank, eff_dt, position, division)
  select 'J4009', 'CA', '2023-02-26', 'CA', 'P'
  where not exists (select 1 from crew_rank where crew_id = 'J4009');

insert into crew (crew_id, first_name, last_name, gender, division, empl_dt, nationality, filiale, status)
  values ('J4010', 'Yeshi', 'Gizaw', 'F', 'P', '2023-03-04', 'ET', 'F8', 0)
  on conflict (crew_id) do nothing;
insert into crew_base (crew_id, base, eff_dt, is_prime_base)
  select 'J4010', 'ADD', '2023-03-04', 1
  where not exists (select 1 from crew_base where crew_id = 'J4010');
insert into crew_fleet (crew_id, fleet_specific, eff_dt)
  select 'J4010', '7M8', '2023-03-04'
  where not exists (select 1 from crew_fleet where crew_id = 'J4010');
insert into crew_rank (crew_id, rank, eff_dt, position, division)
  select 'J4010', 'CA', '2023-03-04', 'CA', 'P'
  where not exists (select 1 from crew_rank where crew_id = 'J4010');

insert into crew (crew_id, first_name, last_name, gender, division, empl_dt, nationality, filiale, status)
  values ('J4011', 'Beniam', 'Yimer', 'M', 'P', '2023-03-10', 'ET', 'F8', 0)
  on conflict (crew_id) do nothing;
insert into crew_base (crew_id, base, eff_dt, is_prime_base)
  select 'J4011', 'ADD', '2023-03-10', 1
  where not exists (select 1 from crew_base where crew_id = 'J4011');
insert into crew_fleet (crew_id, fleet_specific, eff_dt)
  select 'J4011', '7M8', '2023-03-10'
  where not exists (select 1 from crew_fleet where crew_id = 'J4011');
insert into crew_rank (crew_id, rank, eff_dt, position, division)
  select 'J4011', 'CA', '2023-03-10', 'CA', 'P'
  where not exists (select 1 from crew_rank where crew_id = 'J4011');

insert into crew (crew_id, first_name, last_name, gender, division, empl_dt, nationality, filiale, status)
  values ('J4012', 'Temesgen', 'Chane', 'M', 'P', '2023-03-16', 'ET', 'F8', 0)
  on conflict (crew_id) do nothing;
insert into crew_base (crew_id, base, eff_dt, is_prime_base)
  select 'J4012', 'ADD', '2023-03-16', 1
  where not exists (select 1 from crew_base where crew_id = 'J4012');
insert into crew_fleet (crew_id, fleet_specific, eff_dt)
  select 'J4012', '7M8', '2023-03-16'
  where not exists (select 1 from crew_fleet where crew_id = 'J4012');
insert into crew_rank (crew_id, rank, eff_dt, position, division)
  select 'J4012', 'CA', '2023-03-16', 'CA', 'P'
  where not exists (select 1 from crew_rank where crew_id = 'J4012');

insert into crew (crew_id, first_name, last_name, gender, division, empl_dt, nationality, filiale, status)
  values ('J4013', 'Frehiwot', 'Fantahun', 'F', 'P', '2023-03-22', 'ET', 'F8', 0)
  on conflict (crew_id) do nothing;
insert into crew_base (crew_id, base, eff_dt, is_prime_base)
  select 'J4013', 'ADD', '2023-03-22', 1
  where not exists (select 1 from crew_base where crew_id = 'J4013');
insert into crew_fleet (crew_id, fleet_specific, eff_dt)
  select 'J4013', '7M8', '2023-03-22'
  where not exists (select 1 from crew_fleet where crew_id = 'J4013');
insert into crew_rank (crew_id, rank, eff_dt, position, division)
  select 'J4013', 'CA', '2023-03-22', 'CA', 'P'
  where not exists (select 1 from crew_rank where crew_id = 'J4013');

insert into crew (crew_id, first_name, last_name, gender, division, empl_dt, nationality, filiale, status)
  values ('J4014', 'Melaku', 'Mekonnen', 'M', 'P', '2023-03-28', 'ET', 'F8', 0)
  on conflict (crew_id) do nothing;
insert into crew_base (crew_id, base, eff_dt, is_prime_base)
  select 'J4014', 'ADD', '2023-03-28', 1
  where not exists (select 1 from crew_base where crew_id = 'J4014');
insert into crew_fleet (crew_id, fleet_specific, eff_dt)
  select 'J4014', '7M8', '2023-03-28'
  where not exists (select 1 from crew_fleet where crew_id = 'J4014');
insert into crew_rank (crew_id, rank, eff_dt, position, division)
  select 'J4014', 'CA', '2023-03-28', 'CA', 'P'
  where not exists (select 1 from crew_rank where crew_id = 'J4014');

insert into crew (crew_id, first_name, last_name, gender, division, empl_dt, nationality, filiale, status)
  values ('J4015', 'Dereje', 'Wolde', 'M', 'P', '2023-04-03', 'ET', 'F8', 0)
  on conflict (crew_id) do nothing;
insert into crew_base (crew_id, base, eff_dt, is_prime_base)
  select 'J4015', 'ADD', '2023-04-03', 1
  where not exists (select 1 from crew_base where crew_id = 'J4015');
insert into crew_fleet (crew_id, fleet_specific, eff_dt)
  select 'J4015', '7M8', '2023-04-03'
  where not exists (select 1 from crew_fleet where crew_id = 'J4015');
insert into crew_rank (crew_id, rank, eff_dt, position, division)
  select 'J4015', 'CA', '2023-04-03', 'CA', 'P'
  where not exists (select 1 from crew_rank where crew_id = 'J4015');

insert into crew (crew_id, first_name, last_name, gender, division, empl_dt, nationality, filiale, status)
  values ('J4016', 'Aster', 'Zewde', 'F', 'P', '2023-04-09', 'ET', 'F8', 0)
  on conflict (crew_id) do nothing;
insert into crew_base (crew_id, base, eff_dt, is_prime_base)
  select 'J4016', 'ADD', '2023-04-09', 1
  where not exists (select 1 from crew_base where crew_id = 'J4016');
insert into crew_fleet (crew_id, fleet_specific, eff_dt)
  select 'J4016', '7M8', '2023-04-09'
  where not exists (select 1 from crew_fleet where crew_id = 'J4016');
insert into crew_rank (crew_id, rank, eff_dt, position, division)
  select 'J4016', 'CA', '2023-04-09', 'CA', 'P'
  where not exists (select 1 from crew_rank where crew_id = 'J4016');

insert into crew (crew_id, first_name, last_name, gender, division, empl_dt, nationality, filiale, status)
  values ('J4017', 'Shimelis', 'Beyene', 'M', 'P', '2023-04-15', 'ET', 'F8', 0)
  on conflict (crew_id) do nothing;
insert into crew_base (crew_id, base, eff_dt, is_prime_base)
  select 'J4017', 'ADD', '2023-04-15', 1
  where not exists (select 1 from crew_base where crew_id = 'J4017');
insert into crew_fleet (crew_id, fleet_specific, eff_dt)
  select 'J4017', '7M8', '2023-04-15'
  where not exists (select 1 from crew_fleet where crew_id = 'J4017');
insert into crew_rank (crew_id, rank, eff_dt, position, division)
  select 'J4017', 'CA', '2023-04-15', 'CA', 'P'
  where not exists (select 1 from crew_rank where crew_id = 'J4017');

insert into crew (crew_id, first_name, last_name, gender, division, empl_dt, nationality, filiale, status)
  values ('J4018', 'Berhanu', 'Mamo', 'M', 'P', '2023-04-21', 'ET', 'F8', 0)
  on conflict (crew_id) do nothing;
insert into crew_base (crew_id, base, eff_dt, is_prime_base)
  select 'J4018', 'ADD', '2023-04-21', 1
  where not exists (select 1 from crew_base where crew_id = 'J4018');
insert into crew_fleet (crew_id, fleet_specific, eff_dt)
  select 'J4018', '7M8', '2023-04-21'
  where not exists (select 1 from crew_fleet where crew_id = 'J4018');
insert into crew_rank (crew_id, rank, eff_dt, position, division)
  select 'J4018', 'CA', '2023-04-21', 'CA', 'P'
  where not exists (select 1 from crew_rank where crew_id = 'J4018');

insert into crew (crew_id, first_name, last_name, gender, division, empl_dt, nationality, filiale, status)
  values ('J4019', 'Birtukan', 'Shiferaw', 'F', 'P', '2023-04-27', 'ET', 'F8', 0)
  on conflict (crew_id) do nothing;
insert into crew_base (crew_id, base, eff_dt, is_prime_base)
  select 'J4019', 'ADD', '2023-04-27', 1
  where not exists (select 1 from crew_base where crew_id = 'J4019');
insert into crew_fleet (crew_id, fleet_specific, eff_dt)
  select 'J4019', '7M8', '2023-04-27'
  where not exists (select 1 from crew_fleet where crew_id = 'J4019');
insert into crew_rank (crew_id, rank, eff_dt, position, division)
  select 'J4019', 'CA', '2023-04-27', 'CA', 'P'
  where not exists (select 1 from crew_rank where crew_id = 'J4019');

insert into crew (crew_id, first_name, last_name, gender, division, empl_dt, nationality, filiale, status)
  values ('J4020', 'Tamrat', 'Demissie', 'M', 'P', '2023-05-03', 'ET', 'F8', 0)
  on conflict (crew_id) do nothing;
insert into crew_base (crew_id, base, eff_dt, is_prime_base)
  select 'J4020', 'ADD', '2023-05-03', 1
  where not exists (select 1 from crew_base where crew_id = 'J4020');
insert into crew_fleet (crew_id, fleet_specific, eff_dt)
  select 'J4020', '7M8', '2023-05-03'
  where not exists (select 1 from crew_fleet where crew_id = 'J4020');
insert into crew_rank (crew_id, rank, eff_dt, position, division)
  select 'J4020', 'CA', '2023-05-03', 'CA', 'P'
  where not exists (select 1 from crew_rank where crew_id = 'J4020');

insert into crew (crew_id, first_name, last_name, gender, division, empl_dt, nationality, filiale, status)
  values ('J4021', 'Tewodros', 'Gebremariam', 'M', 'P', '2023-05-09', 'ET', 'F8', 0)
  on conflict (crew_id) do nothing;
insert into crew_base (crew_id, base, eff_dt, is_prime_base)
  select 'J4021', 'ADD', '2023-05-09', 1
  where not exists (select 1 from crew_base where crew_id = 'J4021');
insert into crew_fleet (crew_id, fleet_specific, eff_dt)
  select 'J4021', '7M8', '2023-05-09'
  where not exists (select 1 from crew_fleet where crew_id = 'J4021');
insert into crew_rank (crew_id, rank, eff_dt, position, division)
  select 'J4021', 'FO', '2023-05-09', 'FO', 'P'
  where not exists (select 1 from crew_rank where crew_id = 'J4021');

insert into crew (crew_id, first_name, last_name, gender, division, empl_dt, nationality, filiale, status)
  values ('J4022', 'Marta', 'Kifle', 'F', 'P', '2023-05-15', 'ET', 'F8', 0)
  on conflict (crew_id) do nothing;
insert into crew_base (crew_id, base, eff_dt, is_prime_base)
  select 'J4022', 'ADD', '2023-05-15', 1
  where not exists (select 1 from crew_base where crew_id = 'J4022');
insert into crew_fleet (crew_id, fleet_specific, eff_dt)
  select 'J4022', '7M8', '2023-05-15'
  where not exists (select 1 from crew_fleet where crew_id = 'J4022');
insert into crew_rank (crew_id, rank, eff_dt, position, division)
  select 'J4022', 'FO', '2023-05-15', 'FO', 'P'
  where not exists (select 1 from crew_rank where crew_id = 'J4022');

insert into crew (crew_id, first_name, last_name, gender, division, empl_dt, nationality, filiale, status)
  values ('J4023', 'Mesfin', 'Ayele', 'M', 'P', '2023-05-21', 'ET', 'F8', 0)
  on conflict (crew_id) do nothing;
insert into crew_base (crew_id, base, eff_dt, is_prime_base)
  select 'J4023', 'ADD', '2023-05-21', 1
  where not exists (select 1 from crew_base where crew_id = 'J4023');
insert into crew_fleet (crew_id, fleet_specific, eff_dt)
  select 'J4023', '7M8', '2023-05-21'
  where not exists (select 1 from crew_fleet where crew_id = 'J4023');
insert into crew_rank (crew_id, rank, eff_dt, position, division)
  select 'J4023', 'FO', '2023-05-21', 'FO', 'P'
  where not exists (select 1 from crew_rank where crew_id = 'J4023');

insert into crew (crew_id, first_name, last_name, gender, division, empl_dt, nationality, filiale, status)
  values ('J4024', 'Yosef', 'Belay', 'M', 'P', '2023-05-27', 'ET', 'F8', 0)
  on conflict (crew_id) do nothing;
insert into crew_base (crew_id, base, eff_dt, is_prime_base)
  select 'J4024', 'ADD', '2023-05-27', 1
  where not exists (select 1 from crew_base where crew_id = 'J4024');
insert into crew_fleet (crew_id, fleet_specific, eff_dt)
  select 'J4024', '7M8', '2023-05-27'
  where not exists (select 1 from crew_fleet where crew_id = 'J4024');
insert into crew_rank (crew_id, rank, eff_dt, position, division)
  select 'J4024', 'FO', '2023-05-27', 'FO', 'P'
  where not exists (select 1 from crew_rank where crew_id = 'J4024');

insert into crew (crew_id, first_name, last_name, gender, division, empl_dt, nationality, filiale, status)
  values ('J4025', 'Roman', 'Wondimu', 'F', 'P', '2023-06-02', 'ET', 'F8', 0)
  on conflict (crew_id) do nothing;
insert into crew_base (crew_id, base, eff_dt, is_prime_base)
  select 'J4025', 'ADD', '2023-06-02', 1
  where not exists (select 1 from crew_base where crew_id = 'J4025');
insert into crew_fleet (crew_id, fleet_specific, eff_dt)
  select 'J4025', '7M8', '2023-06-02'
  where not exists (select 1 from crew_fleet where crew_id = 'J4025');
insert into crew_rank (crew_id, rank, eff_dt, position, division)
  select 'J4025', 'FO', '2023-06-02', 'FO', 'P'
  where not exists (select 1 from crew_rank where crew_id = 'J4025');

insert into crew (crew_id, first_name, last_name, gender, division, empl_dt, nationality, filiale, status)
  values ('J4026', 'Wondwossen', 'Tefera', 'M', 'P', '2023-06-08', 'ET', 'F8', 0)
  on conflict (crew_id) do nothing;
insert into crew_base (crew_id, base, eff_dt, is_prime_base)
  select 'J4026', 'ADD', '2023-06-08', 1
  where not exists (select 1 from crew_base where crew_id = 'J4026');
insert into crew_fleet (crew_id, fleet_specific, eff_dt)
  select 'J4026', '7M8', '2023-06-08'
  where not exists (select 1 from crew_fleet where crew_id = 'J4026');
insert into crew_rank (crew_id, rank, eff_dt, position, division)
  select 'J4026', 'FO', '2023-06-08', 'FO', 'P'
  where not exists (select 1 from crew_rank where crew_id = 'J4026');

insert into crew (crew_id, first_name, last_name, gender, division, empl_dt, nationality, filiale, status)
  values ('J4027', 'Zerihun', 'Sisay', 'M', 'P', '2023-06-14', 'ET', 'F8', 0)
  on conflict (crew_id) do nothing;
insert into crew_base (crew_id, base, eff_dt, is_prime_base)
  select 'J4027', 'ADD', '2023-06-14', 1
  where not exists (select 1 from crew_base where crew_id = 'J4027');
insert into crew_fleet (crew_id, fleet_specific, eff_dt)
  select 'J4027', '7M8', '2023-06-14'
  where not exists (select 1 from crew_fleet where crew_id = 'J4027');
insert into crew_rank (crew_id, rank, eff_dt, position, division)
  select 'J4027', 'FO', '2023-06-14', 'FO', 'P'
  where not exists (select 1 from crew_rank where crew_id = 'J4027');

insert into crew (crew_id, first_name, last_name, gender, division, empl_dt, nationality, filiale, status)
  values ('J4028', 'Selamawit', 'Aregawi', 'F', 'P', '2023-06-20', 'ET', 'F8', 0)
  on conflict (crew_id) do nothing;
insert into crew_base (crew_id, base, eff_dt, is_prime_base)
  select 'J4028', 'ADD', '2023-06-20', 1
  where not exists (select 1 from crew_base where crew_id = 'J4028');
insert into crew_fleet (crew_id, fleet_specific, eff_dt)
  select 'J4028', '7M8', '2023-06-20'
  where not exists (select 1 from crew_fleet where crew_id = 'J4028');
insert into crew_rank (crew_id, rank, eff_dt, position, division)
  select 'J4028', 'FO', '2023-06-20', 'FO', 'P'
  where not exists (select 1 from crew_rank where crew_id = 'J4028');

insert into crew (crew_id, first_name, last_name, gender, division, empl_dt, nationality, filiale, status)
  values ('J4029', 'Alemayehu', 'Mengistu', 'M', 'P', '2023-06-26', 'ET', 'F8', 0)
  on conflict (crew_id) do nothing;
insert into crew_base (crew_id, base, eff_dt, is_prime_base)
  select 'J4029', 'ADD', '2023-06-26', 1
  where not exists (select 1 from crew_base where crew_id = 'J4029');
insert into crew_fleet (crew_id, fleet_specific, eff_dt)
  select 'J4029', '7M8', '2023-06-26'
  where not exists (select 1 from crew_fleet where crew_id = 'J4029');
insert into crew_rank (crew_id, rank, eff_dt, position, division)
  select 'J4029', 'FO', '2023-06-26', 'FO', 'P'
  where not exists (select 1 from crew_rank where crew_id = 'J4029');

insert into crew (crew_id, first_name, last_name, gender, division, empl_dt, nationality, filiale, status)
  values ('J4030', 'Fasil', 'Gizaw', 'M', 'P', '2023-07-02', 'ET', 'F8', 0)
  on conflict (crew_id) do nothing;
insert into crew_base (crew_id, base, eff_dt, is_prime_base)
  select 'J4030', 'ADD', '2023-07-02', 1
  where not exists (select 1 from crew_base where crew_id = 'J4030');
insert into crew_fleet (crew_id, fleet_specific, eff_dt)
  select 'J4030', '7M8', '2023-07-02'
  where not exists (select 1 from crew_fleet where crew_id = 'J4030');
insert into crew_rank (crew_id, rank, eff_dt, position, division)
  select 'J4030', 'FO', '2023-07-02', 'FO', 'P'
  where not exists (select 1 from crew_rank where crew_id = 'J4030');

insert into crew (crew_id, first_name, last_name, gender, division, empl_dt, nationality, filiale, status)
  values ('J4031', 'Genet', 'Yimer', 'F', 'P', '2023-07-08', 'ET', 'F8', 0)
  on conflict (crew_id) do nothing;
insert into crew_base (crew_id, base, eff_dt, is_prime_base)
  select 'J4031', 'ADD', '2023-07-08', 1
  where not exists (select 1 from crew_base where crew_id = 'J4031');
insert into crew_fleet (crew_id, fleet_specific, eff_dt)
  select 'J4031', '7M8', '2023-07-08'
  where not exists (select 1 from crew_fleet where crew_id = 'J4031');
insert into crew_rank (crew_id, rank, eff_dt, position, division)
  select 'J4031', 'FO', '2023-07-08', 'FO', 'P'
  where not exists (select 1 from crew_rank where crew_id = 'J4031');

insert into crew (crew_id, first_name, last_name, gender, division, empl_dt, nationality, filiale, status)
  values ('J4032', 'Temesgen', 'Chane', 'M', 'P', '2023-07-14', 'ET', 'F8', 0)
  on conflict (crew_id) do nothing;
insert into crew_base (crew_id, base, eff_dt, is_prime_base)
  select 'J4032', 'ADD', '2023-07-14', 1
  where not exists (select 1 from crew_base where crew_id = 'J4032');
insert into crew_fleet (crew_id, fleet_specific, eff_dt)
  select 'J4032', '7M8', '2023-07-14'
  where not exists (select 1 from crew_fleet where crew_id = 'J4032');
insert into crew_rank (crew_id, rank, eff_dt, position, division)
  select 'J4032', 'FO', '2023-07-14', 'FO', 'P'
  where not exists (select 1 from crew_rank where crew_id = 'J4032');

insert into crew (crew_id, first_name, last_name, gender, division, empl_dt, nationality, filiale, status)
  values ('J4033', 'Habtamu', 'Fantahun', 'M', 'P', '2023-07-20', 'ET', 'F8', 0)
  on conflict (crew_id) do nothing;
insert into crew_base (crew_id, base, eff_dt, is_prime_base)
  select 'J4033', 'ADD', '2023-07-20', 1
  where not exists (select 1 from crew_base where crew_id = 'J4033');
insert into crew_fleet (crew_id, fleet_specific, eff_dt)
  select 'J4033', '7M8', '2023-07-20'
  where not exists (select 1 from crew_fleet where crew_id = 'J4033');
insert into crew_rank (crew_id, rank, eff_dt, position, division)
  select 'J4033', 'FO', '2023-07-20', 'FO', 'P'
  where not exists (select 1 from crew_rank where crew_id = 'J4033');

insert into crew (crew_id, first_name, last_name, gender, division, empl_dt, nationality, filiale, status)
  values ('J4034', 'Wubalem', 'Mekonnen', 'F', 'P', '2023-07-26', 'ET', 'F8', 0)
  on conflict (crew_id) do nothing;
insert into crew_base (crew_id, base, eff_dt, is_prime_base)
  select 'J4034', 'ADD', '2023-07-26', 1
  where not exists (select 1 from crew_base where crew_id = 'J4034');
insert into crew_fleet (crew_id, fleet_specific, eff_dt)
  select 'J4034', '7M8', '2023-07-26'
  where not exists (select 1 from crew_fleet where crew_id = 'J4034');
insert into crew_rank (crew_id, rank, eff_dt, position, division)
  select 'J4034', 'FO', '2023-07-26', 'FO', 'P'
  where not exists (select 1 from crew_rank where crew_id = 'J4034');

insert into crew (crew_id, first_name, last_name, gender, division, empl_dt, nationality, filiale, status)
  values ('J4035', 'Dereje', 'Wolde', 'M', 'P', '2023-08-01', 'ET', 'F8', 0)
  on conflict (crew_id) do nothing;
insert into crew_base (crew_id, base, eff_dt, is_prime_base)
  select 'J4035', 'ADD', '2023-08-01', 1
  where not exists (select 1 from crew_base where crew_id = 'J4035');
insert into crew_fleet (crew_id, fleet_specific, eff_dt)
  select 'J4035', '7M8', '2023-08-01'
  where not exists (select 1 from crew_fleet where crew_id = 'J4035');
insert into crew_rank (crew_id, rank, eff_dt, position, division)
  select 'J4035', 'FO', '2023-08-01', 'FO', 'P'
  where not exists (select 1 from crew_rank where crew_id = 'J4035');

insert into crew (crew_id, first_name, last_name, gender, division, empl_dt, nationality, filiale, status)
  values ('J4036', 'Adane', 'Zewde', 'M', 'P', '2023-08-07', 'ET', 'F8', 0)
  on conflict (crew_id) do nothing;
insert into crew_base (crew_id, base, eff_dt, is_prime_base)
  select 'J4036', 'ADD', '2023-08-07', 1
  where not exists (select 1 from crew_base where crew_id = 'J4036');
insert into crew_fleet (crew_id, fleet_specific, eff_dt)
  select 'J4036', '7M8', '2023-08-07'
  where not exists (select 1 from crew_fleet where crew_id = 'J4036');
insert into crew_rank (crew_id, rank, eff_dt, position, division)
  select 'J4036', 'FO', '2023-08-07', 'FO', 'P'
  where not exists (select 1 from crew_rank where crew_id = 'J4036');

insert into crew (crew_id, first_name, last_name, gender, division, empl_dt, nationality, filiale, status)
  values ('J4037', 'Zewditu', 'Beyene', 'F', 'P', '2023-08-13', 'ET', 'F8', 0)
  on conflict (crew_id) do nothing;
insert into crew_base (crew_id, base, eff_dt, is_prime_base)
  select 'J4037', 'ADD', '2023-08-13', 1
  where not exists (select 1 from crew_base where crew_id = 'J4037');
insert into crew_fleet (crew_id, fleet_specific, eff_dt)
  select 'J4037', '7M8', '2023-08-13'
  where not exists (select 1 from crew_fleet where crew_id = 'J4037');
insert into crew_rank (crew_id, rank, eff_dt, position, division)
  select 'J4037', 'FO', '2023-08-13', 'FO', 'P'
  where not exists (select 1 from crew_rank where crew_id = 'J4037');

insert into crew (crew_id, first_name, last_name, gender, division, empl_dt, nationality, filiale, status)
  values ('J4038', 'Berhanu', 'Mamo', 'M', 'P', '2023-08-19', 'ET', 'F8', 0)
  on conflict (crew_id) do nothing;
insert into crew_base (crew_id, base, eff_dt, is_prime_base)
  select 'J4038', 'ADD', '2023-08-19', 1
  where not exists (select 1 from crew_base where crew_id = 'J4038');
insert into crew_fleet (crew_id, fleet_specific, eff_dt)
  select 'J4038', '7M8', '2023-08-19'
  where not exists (select 1 from crew_fleet where crew_id = 'J4038');
insert into crew_rank (crew_id, rank, eff_dt, position, division)
  select 'J4038', 'FO', '2023-08-19', 'FO', 'P'
  where not exists (select 1 from crew_rank where crew_id = 'J4038');

insert into crew (crew_id, first_name, last_name, gender, division, empl_dt, nationality, filiale, status)
  values ('J4039', 'Kassahun', 'Shiferaw', 'M', 'P', '2023-08-25', 'ET', 'F8', 0)
  on conflict (crew_id) do nothing;
insert into crew_base (crew_id, base, eff_dt, is_prime_base)
  select 'J4039', 'ADD', '2023-08-25', 1
  where not exists (select 1 from crew_base where crew_id = 'J4039');
insert into crew_fleet (crew_id, fleet_specific, eff_dt)
  select 'J4039', '7M8', '2023-08-25'
  where not exists (select 1 from crew_fleet where crew_id = 'J4039');
insert into crew_rank (crew_id, rank, eff_dt, position, division)
  select 'J4039', 'FO', '2023-08-25', 'FO', 'P'
  where not exists (select 1 from crew_rank where crew_id = 'J4039');

insert into crew (crew_id, first_name, last_name, gender, division, empl_dt, nationality, filiale, status)
  values ('J4040', 'Bethlehem', 'Demissie', 'F', 'P', '2023-08-31', 'ET', 'F8', 0)
  on conflict (crew_id) do nothing;
insert into crew_base (crew_id, base, eff_dt, is_prime_base)
  select 'J4040', 'ADD', '2023-08-31', 1
  where not exists (select 1 from crew_base where crew_id = 'J4040');
insert into crew_fleet (crew_id, fleet_specific, eff_dt)
  select 'J4040', '7M8', '2023-08-31'
  where not exists (select 1 from crew_fleet where crew_id = 'J4040');
insert into crew_rank (crew_id, rank, eff_dt, position, division)
  select 'J4040', 'FO', '2023-08-31', 'FO', 'P'
  where not exists (select 1 from crew_rank where crew_id = 'J4040');

