import { sql } from 'drizzle-orm'
import { pgTable, bigint, varchar, integer, smallint, numeric, timestamp, uniqueIndex, index } from 'drizzle-orm/pg-core'

export const rosterPublish = pgTable('roster_publish', {
  id: bigint('id', { mode: 'number' }).primaryKey().generatedAlwaysAsIdentity(),
  createdBy: varchar('created_by', { length: 30 }).notNull().default('system'),
  createdAt: timestamp('created_at').notNull().defaultNow(),
  updatedBy: varchar('updated_by', { length: 30 }).notNull().default('system'),
  updatedAt: timestamp('updated_at').notNull().defaultNow(),
  filiale: varchar('filiale', { length: 6 }),
  division: varchar('division', { length: 1 }).notNull(),
  fltId: bigint('flt_id', { mode: 'number' }),
  fltDt: varchar('flt_dt', { length: 10 }).notNull(),
  pairingId: bigint('pairing_id', { mode: 'number' }),
  rosterFlightId: bigint('roster_flight_id', { mode: 'number' }),
  ver: integer('ver').notNull().default(1),
  base: varchar('base', { length: 3 }),
  source: varchar('source', { length: 12 }),
  isRequested: smallint('is_requested').notNull().default(0),
  isDeleted: smallint('is_deleted').notNull().default(0),
  isSwapped: smallint('is_swapped').notNull().default(0),
  preference: varchar('preference', { length: 1 }),
  comments: varchar('comments', { length: 180 }),
  score: integer('score'),
  workingHour: numeric('working_hour', { precision: 8, scale: 2 }),
  schCreditedMinutes: numeric('sch_credited_minutes', { precision: 8, scale: 2 }),
  schFmCreditedMinutes: numeric('sch_fm_credited_minutes', { precision: 8, scale: 2 }),
  schPerDiemMins: numeric('sch_per_diem_mins', { precision: 8, scale: 2 }),
  schLhPerDiemMins: numeric('sch_lh_per_diem_mins', { precision: 8, scale: 2 }),
  schFmPerDiemMins: numeric('sch_fm_per_diem_mins', { precision: 8, scale: 2 }),
  schFmLhPerDiemMins: numeric('sch_fm_lh_per_diem_mins', { precision: 8, scale: 2 }),
  actCreditedMinutes: numeric('act_credited_minutes', { precision: 8, scale: 2 }),
  actFmCreditedMinutes: numeric('act_fm_credited_minutes', { precision: 8, scale: 2 }),
  actPerDiemMins: numeric('act_per_diem_mins', { precision: 8, scale: 2 }),
  actLhPerDiemMins: numeric('act_lh_per_diem_mins', { precision: 8, scale: 2 }),
  actFmPerDiemMins: numeric('act_fm_per_diem_mins', { precision: 8, scale: 2 }),
  actFmLhPerDiemMins: numeric('act_fm_lh_per_diem_mins', { precision: 8, scale: 2 }),
  dpMin: integer('dp_min'),
  dutySeq: smallint('duty_seq'),
  segSeq: smallint('seg_seq'),
  crewId: varchar('crew_id', { length: 30 }).notNull(),
  flightActingRank: varchar('flight_acting_rank', { length: 10 }),
  activeRank: varchar('active_rank', { length: 20 }),
  rosterActingRank: varchar('roster_acting_rank', { length: 10 }),
  position: varchar('position', { length: 20 }),
  assignmentGroup: varchar('assignment_group', { length: 20 }),
  assignment: varchar('assignment', { length: 20 }).notNull(),
  label: varchar('label', { length: 200 }),
  seqOrder: smallint('seq_order').notNull().default(0),
  checkType: varchar('check_type', { length: 40 }),
  tsFlag: varchar('ts_flag', { length: 50 }),
  schStrDtUtc: timestamp('sch_str_dt_utc'),
  schEndDtUtc: timestamp('sch_end_dt_utc'),
  actStrDtUtc: timestamp('act_str_dt_utc'),
  actEndDtUtc: timestamp('act_end_dt_utc'),
  depArp: varchar('dep_arp', { length: 3 }),
  arvArp: varchar('arv_arp', { length: 3 }),
  tagSet: varchar('tag_set', { length: 50 }),
  isExtraCourse: smallint('is_extra_course').notNull().default(0),
  seqOrderSource: varchar('seq_order_source', { length: 20 }),
  exceptionCode: varchar('exception_code', { length: 50 }),
  actRestMin: integer('act_rest_min'),
  pairingLabel: varchar('pairing_label', { length: 50 }),
  pairingBase: varchar('pairing_base', { length: 3 }),
  pairingFleet: varchar('pairing_fleet', { length: 20 }),
  fleetSeg: varchar('fleet_seg', { length: 10 }),
  tafb: integer('tafb'),
  checkingType: varchar('checking_type', { length: 10 }),
  checkingStrTm: timestamp('checking_str_tm'),
  checkingRadius: integer('checking_radius').notNull().default(0),
  checkingTm: timestamp('checking_tm'),
  actCheckingTm: timestamp('act_checking_tm'),
  checkingUser: varchar('checking_user', { length: 20 }),
  pickUpTime: timestamp('pick_up_time'),
  briefTime: timestamp('brief_time'),
  debriefTime: timestamp('debrief_time'),
  dropOffTime: timestamp('drop_off_time'),
  resourceCode: varchar('resource_code', { length: 100 }),
  role: varchar('role', { length: 100 }),
  tmProgramCourseId: bigint('tm_program_course_id', { mode: 'number' }),
  groupId: varchar('group_id', { length: 200 }),
  sendFlag: integer('send_flag'),
  locationValidation: smallint('location_validation'),
  deletedBy: varchar('deleted_by', { length: 30 }),
  browserIdentifyId: varchar('browser_identify_id', { length: 100 }),
  onlyValidationBrowser: smallint('only_validation_browser'),
  pickUpStartUtc: timestamp('pick_up_start_utc'),
  pickUpEndUtc: timestamp('pick_up_end_utc'),
  briefStartUtc: timestamp('brief_start_utc'),
  briefEndUtc: timestamp('brief_end_utc'),
  debriefStartUtc: timestamp('debrief_start_utc'),
  debriefEndUtc: timestamp('debrief_end_utc'),
  dropOffStartUtc: timestamp('drop_off_start_utc'),
  dropOffEndUtc: timestamp('drop_off_end_utc'),
  parentTmProgramCourseId: bigint('parent_tm_program_course_id', { mode: 'number' }),
  remark: varchar('remark', { length: 512 }),
  checkingDefineId: bigint('checking_define_id', { mode: 'number' }),
  inFltDuty: varchar('in_flt_duty', { length: 20 }),
  onlyValidationIp: smallint('only_validation_ip'),
  checkInIp: varchar('check_in_ip', { length: 200 }),
  emQuiz: varchar('em_quiz', { length: 64 }),
  courseCode: varchar('course_code', { length: 30 }),
  pairingStartUtc: timestamp('pairing_start_utc'),
  dutyCodeFlag: smallint('duty_code_flag'),
  schBriefStartUtc: timestamp('sch_brief_start_utc'),
  checkingEndTm: timestamp('checking_end_tm'),
  latenessType: smallint('lateness_type'),
  checkInLocationForRadius: varchar('check_in_location_for_radius', { length: 500 }),
  requestSource: varchar('request_source', { length: 20 }),
  requestId: bigint('request_id', { mode: 'number' }),
  isPublish: smallint('is_publish'),
  subTmProgramCourseId: bigint('sub_tm_program_course_id', { mode: 'number' }),
  subParentTmProgramId: bigint('sub_parent_tm_program_id', { mode: 'number' }),
  subCourseCode: varchar('sub_course_code', { length: 30 }),
  subRole: varchar('sub_role', { length: 100 }),
  subGroupId: varchar('sub_group_id', { length: 200 }),
}, (table) => [
  uniqueIndex('uq_roster_publish').on(table.fltId, table.crewId).where(sql`${table.fltId} is not null`),
  uniqueIndex('uq_roster_publish_roster_flight_id').on(table.rosterFlightId).where(sql`${table.rosterFlightId} is not null`),
  index('idx_roster_pub_crew_pair').on(table.crewId, table.pairingId, table.dutySeq, table.fltId),
  index('idx_roster_pub_flt_dt').on(table.fltId, table.fltDt),
  index('idx_roster_pub_crew_start').on(table.crewId, table.schStrDtUtc),
])
