import { pgTable, bigint, varchar, integer, smallint, numeric, timestamp } from 'drizzle-orm/pg-core'
import { pairing } from '../pairing/pairing.js'

export const rosterFlight = pgTable('roster_flight', {
  id: bigint('id', { mode: 'number' }).primaryKey().generatedAlwaysAsIdentity(),
  createdBy: varchar('created_by', { length: 30 }).notNull().default('system'),
  createdAt: timestamp('created_at').notNull().defaultNow(),
  updatedBy: varchar('updated_by', { length: 30 }).notNull().default('system'),
  updatedAt: timestamp('updated_at').notNull().defaultNow(),

  // 公共字段
  crewId: varchar('crew_id', { length: 30 }).notNull(),
  pairingId: bigint('pairing_id', { mode: 'number' }).references(() => pairing.id, { onDelete: 'restrict' }),
  liveId: bigint('live_id', { mode: 'number' }),
  ver: integer('ver').notNull().default(1),
  base: varchar('base', { length: 3 }).notNull(),
  label: varchar('label', { length: 200 }),
  assignmentGroup: varchar('assignment_group', { length: 20 }).notNull(),
  assignment: varchar('assignment', { length: 20 }),
  role: varchar('role', { length: 20 }),
  subRole: varchar('sub_role', { length: 100 }),
  source: varchar('source', { length: 12 }),
  isRequested: smallint('is_requested').notNull().default(0),
  isDeleted: smallint('is_deleted').notNull().default(0),
  isSwapped: smallint('is_swapped').notNull().default(0),
  preference: varchar('preference', { length: 1 }),
  comments: varchar('comments', { length: 180 }),
  score: integer('score'),
  workingHour: numeric('working_hour', { precision: 8, scale: 2 }),

  schCreditedMinutes: numeric('sch_credited_minutes', { precision: 8, scale: 2 }),
  schFmCreditedMinutes: numeric('sch_fm_credited_minutes', { precision: 8, scale: 2 }),
  schPerDiemMins: numeric('sch_per_diem_mins', { precision: 8, scale: 2 }),
  schLhPerDiemMins: numeric('sch_lh_per_diem_mins', { precision: 8, scale: 2 }),
  schFmPerDiemMins: numeric('sch_fm_per_diem_mins', { precision: 8, scale: 2 }),
  schFmLhPerDiemMins: numeric('sch_fm_lh_per_diem_mins', { precision: 8, scale: 2 }),

  actCreditedMinutes: numeric('act_credited_minutes', { precision: 8, scale: 2 }),
  actFmCreditedMinutes: numeric('act_fm_credited_minutes', { precision: 8, scale: 2 }),
  actPerDiemMins: numeric('act_per_diem_mins', { precision: 8, scale: 2 }),
  actLhPerDiemMins: numeric('act_lh_per_diem_mins', { precision: 8, scale: 2 }),
  actFmPerDiemMins: numeric('act_fm_per_diem_mins', { precision: 8, scale: 2 }),
  actFmLhPerDiemMins: numeric('act_fm_lh_per_diem_mins', { precision: 8, scale: 2 }),
  dpMin: integer('dp_min'),

  // 飞行任务字段
  fltId: bigint('flt_id', { mode: 'number' }),
  dutySeq: smallint('duty_seq'),
  segSeq: smallint('seg_seq'),
  /** Crew-specific 7500 acclimatisation reference timezone, minutes east of UTC. */
  dutyRefTz: integer('duty_ref_tz'),
  /** Crew-specific 7500 reference timezone at duty end / rest start, minutes east of UTC. */
  dutyEndRefTz: integer('duty_end_ref_tz'),
  fltDt: varchar('flt_dt', { length: 10 }),
  schStrDtUtc: timestamp('sch_str_dt_utc'),
  schEndDtUtc: timestamp('sch_end_dt_utc'),
  actStrDtUtc: timestamp('act_str_dt_utc'),
  actEndDtUtc: timestamp('act_end_dt_utc'),
  division: varchar('division', { length: 2 }),
  flightActingRank: varchar('flight_acting_rank', { length: 10 }).notNull(),
  rosterActingRank: varchar('roster_acting_rank', { length: 10 }),
  activeRank: varchar('active_rank', { length: 20 }),
  position: varchar('position', { length: 10 }),
  seqOrder: smallint('seq_order'),
  checkType: varchar('check_type', { length: 40 }),
  tsFlag: varchar('ts_flag', { length: 50 }),
  sendFlag: smallint('send_flag'),
  resourceCode: varchar('resource_code', { length: 100 }),
  tmProgramCourseId: bigint('tm_program_course_id', { mode: 'number' }),
  groupId: varchar('group_id', { length: 200 }),
  tagSet: varchar('tag_set', { length: 50 }),
  parentTmProgramCourseId: bigint('parent_tm_program_course_id', { mode: 'number' }),
  courseCode: varchar('course_code', { length: 30 }),
  isExtraCourse: smallint('is_extra_course').notNull().default(0),
  subTmProgramCourseId: bigint('sub_tm_program_course_id', { mode: 'number' }),
  subParentTmProgramId: bigint('sub_parent_tm_program_id', { mode: 'number' }),
  subCourseCode: varchar('sub_course_code', { length: 30 }),
  seqOrderSource: varchar('seq_order_source', { length: 20 }),
  subGroupId: varchar('sub_group_id', { length: 200 }),
  requestSource: varchar('request_source', { length: 20 }),
  requestId: bigint('request_id', { mode: 'number' }),
  isPublish: smallint('is_publish'),
  exceptionCode: varchar('exception_code', { length: 50 }),
  actRestMin: integer('act_rest_min'),
  depArp: varchar('dep_arp', { length: 3 }),
  arvArp: varchar('arv_arp', { length: 3 }),
})
