import { pgTable, bigint, varchar, smallint, timestamp, index } from 'drizzle-orm/pg-core'

export const rosterPublishAdjust = pgTable('roster_publish_adjust', {
  id: bigint('id', { mode: 'number' }).primaryKey().generatedAlwaysAsIdentity(),
  createdBy: varchar('created_by', { length: 30 }).notNull().default('system'),
  createdAt: timestamp('created_at').notNull().defaultNow(),
  updatedBy: varchar('updated_by', { length: 30 }).notNull().default('system'),
  updatedAt: timestamp('updated_at').notNull().defaultNow(),
  batchId: bigint('batch_id', { mode: 'number' }).notNull(),
  rpStart: timestamp('rp_start'),
  rpEnd: timestamp('rp_end'),
  publishedDt: timestamp('published_dt'),
  filiale: varchar('filiale', { length: 20 }),
  division: varchar('division', { length: 20 }),
  actionType: varchar('action_type', { length: 20 }),
  crewId: varchar('crew_id', { length: 30 }),

  oldRosterFlightId: bigint('old_roster_flight_id', { mode: 'number' }),
  oldPairingId: bigint('old_pairing_id', { mode: 'number' }),
  oldPairInterfaceId: varchar('old_pair_interface_id', { length: 100 }),
  oldFltId: bigint('old_flt_id', { mode: 'number' }),
  oldBase: varchar('old_base', { length: 3 }),
  oldSchStrDtUtc: timestamp('old_sch_str_dt_utc'),
  oldSchEndDtUtc: timestamp('old_sch_end_dt_utc'),
  oldActStrDtUtc: timestamp('old_act_str_dt_utc'),
  oldActEndDtUtc: timestamp('old_act_end_dt_utc'),
  oldDepArp: varchar('old_dep_arp', { length: 3 }),
  oldArvArp: varchar('old_arv_arp', { length: 3 }),
  oldAssignmentGroup: varchar('old_assignment_group', { length: 20 }),
  oldAssignment: varchar('old_assignment', { length: 20 }),
  oldRosterActingRank: varchar('old_roster_acting_rank', { length: 10 }),
  oldFlightActingRank: varchar('old_flight_acting_rank', { length: 10 }),
  oldActiveRank: varchar('old_active_rank', { length: 10 }),
  oldPosition: varchar('old_position', { length: 10 }),
  oldRole: varchar('old_role', { length: 30 }),
  oldCourseCode: varchar('old_course_code', { length: 30 }),
  oldResourceCode: varchar('old_resource_code', { length: 30 }),
  oldSeqOrder: smallint('old_seq_order'),
  oldBriefStartUtc: timestamp('old_brief_start_utc'),
  oldBriefEndUtc: timestamp('old_brief_end_utc'),
  oldSource: varchar('old_source', { length: 12 }),

  newRosterFlightId: bigint('new_roster_flight_id', { mode: 'number' }),
  newPairingId: bigint('new_pairing_id', { mode: 'number' }),
  newPairInterfaceId: varchar('new_pair_interface_id', { length: 100 }),
  newFltId: bigint('new_flt_id', { mode: 'number' }),
  newBase: varchar('new_base', { length: 3 }),
  newSchStrDtUtc: timestamp('new_sch_str_dt_utc'),
  newSchEndDtUtc: timestamp('new_sch_end_dt_utc'),
  newActStrDtUtc: timestamp('new_act_str_dt_utc'),
  newActEndDtUtc: timestamp('new_act_end_dt_utc'),
  newDepArp: varchar('new_dep_arp', { length: 3 }),
  newArvArp: varchar('new_arv_arp', { length: 3 }),
  newAssignmentGroup: varchar('new_assignment_group', { length: 20 }),
  newAssignment: varchar('new_assignment', { length: 20 }),
  newRosterActingRank: varchar('new_roster_acting_rank', { length: 10 }),
  newFlightActingRank: varchar('new_flight_acting_rank', { length: 10 }),
  newActiveRank: varchar('new_active_rank', { length: 10 }),
  newPosition: varchar('new_position', { length: 10 }),
  newRole: varchar('new_role', { length: 30 }),
  newCourseCode: varchar('new_course_code', { length: 30 }),
  newResourceCode: varchar('new_resource_code', { length: 30 }),
  newSeqOrder: smallint('new_seq_order'),
  newBriefStartUtc: timestamp('new_brief_start_utc'),
  newBriefEndUtc: timestamp('new_brief_end_utc'),
  newSource: varchar('new_source', { length: 12 }),

  published: smallint('published').notNull().default(0),
}, (table) => [
  index('idx_roster_pub_adj_published').on(table.published),
  index('idx_roster_pub_adj_batch').on(table.batchId),
  index('idx_roster_pub_adj_crew_created').on(table.crewId, table.createdAt),
])
