import { pgTable, bigint, varchar, integer, smallint, numeric, timestamp, date, index } from 'drizzle-orm/pg-core'

export const pairing = pgTable('pairing', {
  id: bigint('id', { mode: 'number' }).primaryKey().generatedAlwaysAsIdentity(),
  createdBy: varchar('created_by', { length: 30 }).notNull().default('system'),
  createdAt: timestamp('created_at').notNull().defaultNow(),
  updatedBy: varchar('updated_by', { length: 30 }).notNull().default('system'),
  updatedAt: timestamp('updated_at').notNull().defaultNow(),
  pairingLabel: varchar('pairing_label', { length: 200 }),
  filiale: varchar('filiale', { length: 6 }),
  division: varchar('division', { length: 2 }).notNull(),
  base: varchar('base', { length: 3 }).notNull(),
  fleet: varchar('fleet', { length: 10 }).notNull(),
  assignmentGroup: varchar('assignment_group', { length: 20 }).notNull(),
  assignment: varchar('assignment', { length: 20 }).notNull(),
  schStrDtUtc: timestamp('sch_str_dt_utc').notNull(),
  schEndDtUtc: timestamp('sch_end_dt_utc').notNull(),
  actStrDtUtc: timestamp('act_str_dt_utc').notNull(),
  actEndDtUtc: timestamp('act_end_dt_utc').notNull(),
  durationDays: smallint('duration_days').notNull(),
  // PBS 口径日历日（Base 当地时区 Brief→Debrief 覆盖日历日数），单位天，最小值 1
  tafb: smallint('tafb').notNull(),
  dutyCount: smallint('duty_count').notNull().default(1),
  segCount: smallint('seg_count').notNull().default(1),
  perDiemMins: numeric('per_diem_mins', { precision: 10, scale: 2 }),
  perDiemMinsAdjustment: numeric('per_diem_mins_adjustment', { precision: 10, scale: 2 }),
  wpMins: numeric('wp_mins', { precision: 10, scale: 2 }),
  wpMinsAdjustment: numeric('wp_mins_adjustment', { precision: 10, scale: 2 }),
  schPerDiemMins: numeric('sch_per_diem_mins', { precision: 8, scale: 2 }),
  schLhPerDiemMins: numeric('sch_lh_per_diem_mins', { precision: 8, scale: 2 }),
  schWpMins: numeric('sch_wp_mins', { precision: 8, scale: 2 }),
  lhPerDiemMins: numeric('lh_per_diem_mins', { precision: 8, scale: 2 }),
  fmPerDiemMins: numeric('fm_per_diem_mins', { precision: 8, scale: 2 }),
  fmLhPerDiemMins: numeric('fm_lh_per_diem_mins', { precision: 8, scale: 2 }),
  schFmPerDiemMins: numeric('sch_fm_per_diem_mins', { precision: 8, scale: 2 }),
  schFmLhPerDiemMins: numeric('sch_fm_lh_per_diem_mins', { precision: 8, scale: 2 }),
  ggyBlh: integer('ggy_blh'),
  ver: integer('ver').notNull().default(1),
  preference: varchar('preference', { length: 1 }),
  isDeleted: smallint('is_deleted').notNull().default(0),
  liveId: bigint('live_id', { mode: 'number' }),
  interfaceId: varchar('interface_id', { length: 100 }),
  source: varchar('source', { length: 12 }),
  tags: varchar('tags', { length: 100 }),
  comments: varchar('comments', { length: 120 }),
  pairingDt: date('pairing_dt'),
}, (table) => [
  index('idx_pairing_deleted').on(table.isDeleted),
])
