import { pgTable, bigint, varchar, integer, smallint, timestamp, index, uniqueIndex } from 'drizzle-orm/pg-core'
import { jsonb, text } from 'drizzle-orm/pg-core'

// --- 新标签体系: tag_opt_filter ---
export const tagOptFilter = pgTable('tag_opt_filter', {
  id: bigint('id', { mode: 'number' }).primaryKey().generatedAlwaysAsIdentity(),
  createdBy: varchar('created_by', { length: 30 }).notNull().default('system'),
  createdAt: timestamp('created_at').notNull().defaultNow(),
  updatedBy: varchar('updated_by', { length: 30 }).notNull().default('system'),
  updatedAt: timestamp('updated_at').notNull().defaultNow(),
  filterCode: varchar('filter_code', { length: 50 }).notNull(),
  name: varchar('name', { length: 100 }).notNull(),
  description: text('description'),
  usage: varchar('usage', { length: 20 }).notNull(),
  filterLogic: jsonb('filter_logic').notNull(),
  filiale: varchar('filiale', { length: 6 }).notNull(),
  isDeleted: smallint('is_deleted').notNull().default(0),
})

// --- 旧标签体系（待废弃）---
export const tagCategory = pgTable('tag_category', {
  id: bigint('id', { mode: 'number' }).primaryKey().generatedAlwaysAsIdentity(),
  createdBy: varchar('created_by', { length: 30 }).notNull().default('system'),
  createdAt: timestamp('created_at').notNull().defaultNow(),
  updatedBy: varchar('updated_by', { length: 30 }).notNull().default('system'),
  updatedAt: timestamp('updated_at').notNull().defaultNow(),
  code: varchar('code', { length: 50 }).notNull(),
  name: varchar('name', { length: 50 }).notNull(),
  ratio: integer('ratio').notNull().default(0),
  idx: integer('idx').notNull().default(0),
  source: varchar('source', { length: 10 }),
  exceptTag: varchar('except_tag', { length: 100 }),
  filiale: varchar('filiale', { length: 6 }),
  division: varchar('division', { length: 1 }),
  requestable: smallint('requestable'),
  divisions: varchar('divisions', { length: 5 }),
  isDisplay: smallint('is_display'),
  colorHex: varchar('color_hex', { length: 6 }),
  isWarning: smallint('is_warning'),
})

export const tagGroup = pgTable('tag_group', {
  id: bigint('id', { mode: 'number' }).primaryKey().generatedAlwaysAsIdentity(),
  createdBy: varchar('created_by', { length: 30 }).notNull().default('system'),
  createdAt: timestamp('created_at').notNull().defaultNow(),
  updatedBy: varchar('updated_by', { length: 30 }).notNull().default('system'),
  updatedAt: timestamp('updated_at').notNull().defaultNow(),
  tagCategoryId: bigint('tag_category_id', { mode: 'number' }).notNull(),
  tableType: varchar('table_type', { length: 20 }),
  parentId: bigint('parent_id', { mode: 'number' }).notNull().default(0),
  condition: varchar('condition', { length: 5 }).notNull(),
  type: varchar('type', { length: 9 }).notNull(),
  level: integer('level').notNull().default(0),
  idx: integer('idx').notNull().default(0),
})

export const tagFlight = pgTable('tag_flight', {
  id: bigint('id', { mode: 'number' }).primaryKey().generatedAlwaysAsIdentity(),
  createdBy: varchar('created_by', { length: 30 }).notNull().default('system'),
  createdAt: timestamp('created_at').notNull().defaultNow(),
  updatedBy: varchar('updated_by', { length: 30 }).notNull().default('system'),
  updatedAt: timestamp('updated_at').notNull().defaultNow(),
  tagGroupId: bigint('tag_group_id', { mode: 'number' }).notNull(),
  fltDtStart: timestamp('flt_dt_start'),
  fltDtEnd: timestamp('flt_dt_end'),
  fltNum: varchar('flt_num', { length: 100 }),
  fleet: varchar('fleet', { length: 100 }),
  dir: varchar('dir', { length: 10 }),
  depArp: varchar('dep_arp', { length: 3 }),
  arvArp: varchar('arv_arp', { length: 3 }),
  stdStart: varchar('std_start', { length: 5 }),
  stdEnd: varchar('std_end', { length: 5 }),
  staStart: varchar('sta_start', { length: 5 }),
  staEnd: varchar('sta_end', { length: 5 }),
  country: varchar('country', { length: 2 }),
  assignments: varchar('assignments', { length: 30 }),
  schBlhStart: varchar('sch_blh_start', { length: 20 }),
  schBlhEnd: varchar('sch_blh_end', { length: 20 }),
  actBlhStart: varchar('act_blh_start', { length: 20 }),
  actBlhEnd: varchar('act_blh_end', { length: 20 }),
  flightType: varchar('flight_type', { length: 20 }),
})

export const tagDuty = pgTable('tag_duty', {
  id: bigint('id', { mode: 'number' }).primaryKey().generatedAlwaysAsIdentity(),
  createdBy: varchar('created_by', { length: 30 }).notNull().default('system'),
  createdAt: timestamp('created_at').notNull().defaultNow(),
  updatedBy: varchar('updated_by', { length: 30 }).notNull().default('system'),
  updatedAt: timestamp('updated_at').notNull().defaultNow(),
  tagGroupId: bigint('tag_group_id', { mode: 'number' }).notNull(),
  checkInStart: varchar('check_in_start', { length: 5 }),
  checkInEnd: varchar('check_in_end', { length: 5 }),
  checkOutStart: varchar('check_out_start', { length: 5 }),
  checkOutEnd: varchar('check_out_end', { length: 5 }),
  blhStart: varchar('blh_start', { length: 8 }),
  blhEnd: varchar('blh_end', { length: 8 }),
  fdpStart: varchar('fdp_start', { length: 8 }),
  fdpEnd: varchar('fdp_end', { length: 8 }),
  segNum: varchar('seg_num', { length: 20 }),
  dutySeq: integer('duty_seq'),
  dutyDurationStart: varchar('duty_duration_start', { length: 5 }),
  dutyDurationEnd: varchar('duty_duration_end', { length: 5 }),
  firstStdStart: varchar('first_std_start', { length: 20 }),
  firstStdEnd: varchar('first_std_end', { length: 20 }),
  fdpTouchStart: varchar('fdp_touch_start', { length: 20 }),
  fdpTouchEnd: varchar('fdp_touch_end', { length: 20 }),
  transitDurationStart: varchar('transit_duration_start', { length: 20 }),
  transitDurationEnd: varchar('transit_duration_end', { length: 20 }),
  transitAirports: varchar('transit_airports', { length: 100 }),
  dutyDaysStart: varchar('duty_days_start', { length: 3 }),
  dutyDaysEnd: varchar('duty_days_end', { length: 3 }),
  dpStart: varchar('dp_start', { length: 8 }),
  dpEnd: varchar('dp_end', { length: 8 }),
  overlapPeriodStart: varchar('overlap_period_start', { length: 8 }),
  overlapPeriodEnd: varchar('overlap_period_end', { length: 8 }),
})

export const tagPairing = pgTable('tag_pairing', {
  id: bigint('id', { mode: 'number' }).primaryKey().generatedAlwaysAsIdentity(),
  createdBy: varchar('created_by', { length: 30 }).notNull().default('system'),
  createdAt: timestamp('created_at').notNull().defaultNow(),
  updatedBy: varchar('updated_by', { length: 30 }).notNull().default('system'),
  updatedAt: timestamp('updated_at').notNull().defaultNow(),
  tagGroupId: bigint('tag_group_id', { mode: 'number' }).notNull(),
  base: varchar('base', { length: 20 }),
  pairingLength: varchar('pairing_length', { length: 20 }),
  avgBlhLow: varchar('avg_blh_low', { length: 10 }),
  avgBlhHigh: varchar('avg_blh_high', { length: 10 }),
  layover: varchar('layover', { length: 100 }),
  assignmentGroup: varchar('assignment_group', { length: 100 }),
  transitDurationStart: varchar('transit_duration_start', { length: 10 }),
  transitDurationEnd: varchar('transit_duration_end', { length: 10 }),
  transitAirports: varchar('transit_airports', { length: 10 }),
  overNightDayStart: varchar('over_night_day_start', { length: 10 }),
  overNightDayEnd: varchar('over_night_day_end', { length: 10 }),
  pairingDayStart: varchar('pairing_day_start', { length: 20 }),
  pairingDayEnd: varchar('pairing_day_end', { length: 20 }),
  layoverDurationStart: varchar('layover_duration_start', { length: 20 }),
  layoverDurationEnd: varchar('layover_duration_end', { length: 20 }),
  layoverCountry: varchar('layover_country', { length: 200 }),
  avgBlockPerSegLow: varchar('avg_block_per_seg_low', { length: 20 }),
  avgBlockPerSegHigh: varchar('avg_block_per_seg_high', { length: 20 }),
})

export const tagRosterGround = pgTable('tag_roster_ground', {
  id: bigint('id', { mode: 'number' }).primaryKey().generatedAlwaysAsIdentity(),
  createdBy: varchar('created_by', { length: 30 }).notNull().default('system'),
  createdAt: timestamp('created_at').notNull().defaultNow(),
  updatedBy: varchar('updated_by', { length: 30 }).notNull().default('system'),
  updatedAt: timestamp('updated_at').notNull().defaultNow(),
  tagGroupId: bigint('tag_group_id', { mode: 'number' }).notNull(),
  strDtLow: varchar('str_dt_low', { length: 10 }),
  strDtHigh: varchar('str_dt_high', { length: 10 }),
  endDtLow: varchar('end_dt_low', { length: 10 }),
  endDtHigh: varchar('end_dt_high', { length: 10 }),
  location: varchar('location', { length: 200 }),
  assignment: varchar('assignment', { length: 200 }),
  isSwap: varchar('is_swap', { length: 1 }),
  isRequest: varchar('is_request', { length: 1 }),
  isTraining: varchar('is_training', { length: 1 }),
  trainingRole: varchar('training_role', { length: 1 }),
  dutyPeriodLow: varchar('duty_period_low', { length: 10 }),
  dutyPeriodHigh: varchar('duty_period_high', { length: 10 }),
  overlapPeriodLow: varchar('overlap_period_low', { length: 10 }),
  overlapPeriodHigh: varchar('overlap_period_high', { length: 10 }),
}, (table) => [
  index('idx_tag_roster_ground_group').on(table.tagGroupId),
])

export const tagFlightComposition = pgTable('tag_flight_composition', {
  id: bigint('id', { mode: 'number' }).primaryKey().generatedAlwaysAsIdentity(),
  createdBy: varchar('created_by', { length: 30 }).notNull().default('system'),
  createdAt: timestamp('created_at').notNull().defaultNow(),
  updatedBy: varchar('updated_by', { length: 30 }).notNull().default('system'),
  updatedAt: timestamp('updated_at').notNull().defaultNow(),
  tagGroupId: bigint('tag_group_id', { mode: 'number' }).notNull(),
  division: varchar('division', { length: 5 }),
  actingRank: varchar('acting_rank', { length: 255 }),
  minValue: bigint('min_value', { mode: 'number' }),
  maxValue: bigint('max_value', { mode: 'number' }),
})
