import { pgTable, bigint, varchar, smallint, numeric, timestamp, uniqueIndex } from 'drizzle-orm/pg-core'

export const crew = pgTable('crew', {
  id: bigint('id', { mode: 'number' }).primaryKey().generatedAlwaysAsIdentity(),
  createdBy: varchar('created_by', { length: 30 }).notNull().default('system'),
  createdAt: timestamp('created_at').notNull().defaultNow(),
  updatedBy: varchar('updated_by', { length: 30 }).notNull().default('system'),
  updatedAt: timestamp('updated_at').notNull().defaultNow(),
  crewId: varchar('crew_id', { length: 30 }).notNull(),
  firstName: varchar('first_name', { length: 100 }).notNull(),
  middleName: varchar('middle_name', { length: 100 }),
  lastName: varchar('last_name', { length: 100 }).notNull(),
  preferredName: varchar('preferred_name', { length: 100 }),
  birthday: timestamp('birthday'),
  gender: varchar('gender', { length: 1 }).notNull(),
  division: varchar('division', { length: 1 }).notNull(),
  emplDt: timestamp('empl_dt').notNull(),
  retireDt: timestamp('retire_dt'),
  termDt: timestamp('term_dt'),
  seniorityNum: numeric('seniority_num', { precision: 10, scale: 2 }),
  nationality: varchar('nationality', { length: 2 }),
  nationalId: varchar('national_id', { length: 20 }),
  spouseCrewId: varchar('spouse_crew_id', { length: 12 }),
  passportFirstName: varchar('passport_first_name', { length: 100 }),
  passportMiddleName: varchar('passport_middle_name', { length: 100 }),
  passportLastName: varchar('passport_last_name', { length: 100 }),
  remarks: varchar('remarks', { length: 50 }),
  filiale: varchar('filiale', { length: 6 }).notNull(),
  grade: varchar('grade', { length: 20 }),
  status: smallint('status').notNull().default(0),
  branchCode: varchar('branch_code', { length: 20 }),
  visaType: varchar('visa_type', { length: 40 }),
  birthCountry: varchar('birth_country', { length: 12 }),
  birthPlace: varchar('birth_place', { length: 255 }),
  birthPlaceEn: varchar('birth_place_en', { length: 50 }),
  nation: varchar('nation', { length: 20 }),
  politics: varchar('politics', { length: 10 }),
  contractType: varchar('contract_type', { length: 40 }),
  avatar: varchar('avatar', { length: 100 }),
  tel: varchar('tel', { length: 100 }),
  idCard: varchar('id_card', { length: 100 }),
  interfaceCrewId: varchar('interface_crew_id', { length: 40 }),
  employeeNo: varchar('employee_no', { length: 20 }),
  emailAddr: varchar('email_addr', { length: 100 }),
  interfaceId: varchar('interface_id', { length: 40 }),
  homeAddress: varchar('home_address', { length: 500 }),
}, (table) => [
  uniqueIndex('uq_crew_id').on(table.crewId),
])
