import { pgTable, bigint, varchar, integer, smallint, numeric, boolean, date, char, timestamp, uniqueIndex, index } from 'drizzle-orm/pg-core'

// --- 飞行员每日累计工时 ---
export const crewMandayFdDaily = pgTable('crew_manday_fd_daily', {
  id: bigint('id', { mode: 'number' }).primaryKey().generatedAlwaysAsIdentity(),
  createdBy: varchar('created_by', { length: 30 }).notNull().default('system'),
  createdAt: timestamp('created_at').notNull().defaultNow(),
  updatedBy: varchar('updated_by', { length: 30 }).notNull().default('system'),
  updatedAt: timestamp('updated_at').notNull().defaultNow(),
  crewId: varchar('crew_id', { length: 30 }).notNull(),
  crewBaseDt: date('crew_base_dt').notNull(),
  ft: integer('ft').notNull().default(0),
  augumentFt: integer('augument_ft').notNull().default(0),
  doubleFt: integer('double_ft').notNull().default(0),
  blh: integer('blh').notNull().default(0),
  augumentBlh: integer('augument_blh').notNull().default(0),
  doubleBlh: integer('double_blh').notNull().default(0),
  fdp: integer('fdp').notNull().default(0),
  dp: integer('dp').notNull().default(0),
  nightDp: integer('night_dp').notNull().default(0),
  travel: integer('travel').notNull().default(0),
  credit: numeric('credit', { precision: 6, scale: 2 }).notNull().default('0'),
  fatigue: integer('fatigue').notNull().default(0),
  isLeave: integer('is_leave').notNull().default(0),
  isDayOff: integer('is_day_off').notNull().default(0),
  standby: integer('standby').notNull().default(0),
  actTakeOffs: smallint('act_take_offs').notNull().default(0),
  actLandings: smallint('act_landings').notNull().default(0),
  ground: smallint('ground').notNull().default(0),
  actingRank: varchar('acting_rank', { length: 10 }),
  fleet: varchar('fleet', { length: 4 }),
  perDiem: integer('per_diem').notNull().default(0),
  normalWp: integer('normal_wp').notNull().default(0),
  extendWp: integer('extend_wp').notNull().default(0),
  csb: smallint('csb').notNull().default(0),
  hsb: smallint('hsb').notNull().default(0),
  asb: smallint('asb').notNull().default(0),
  isAl: smallint('is_al').notNull().default(0),
  updowns: integer('updowns').notNull().default(0),
  cat2Updowns: integer('cat2_updowns').notNull().default(0),
  expBlh: integer('exp_blh').notNull().default(0),
  quarantine: smallint('quarantine').notNull().default(0),
  custData1: numeric('cust_data1', { precision: 6, scale: 2 }),
  custData2: numeric('cust_data2', { precision: 6, scale: 2 }),
  highPlateau: integer('high_plateau').notNull().default(0),
  operatingFleets: varchar('operating_fleets', { length: 100 }),
  operatingAirports: varchar('operating_airports', { length: 100 }),
  takeoff: integer('takeoff').notNull().default(0),
  landing: integer('landing').notNull().default(0),
  isPosition: smallint('is_position').notNull().default(0),
  workingHour: numeric('working_hour', { precision: 8, scale: 2 }),
  pncCredit: numeric('pnc_credit', { precision: 8, scale: 2 }),
  simCredit: numeric('sim_credit', { precision: 8, scale: 2 }),
  alCredit: numeric('al_credit', { precision: 8, scale: 2 }),
  olCredit: numeric('ol_credit', { precision: 8, scale: 2 }),
  freighterCredit: numeric('freighter_credit', { precision: 8, scale: 2 }),
  layoverDay: integer('layover_day'),
  lhPerDiem: numeric('lh_per_diem', { precision: 8, scale: 2 }),
  sbyDp: numeric('sby_dp', { precision: 8, scale: 2 }).notNull().default('0'),
  dhdDp: numeric('dhd_dp', { precision: 8, scale: 2 }).notNull().default('0'),
  fleetTakeoff: varchar('fleet_takeoff', { length: 32 }),
  fleetLanding: varchar('fleet_landing', { length: 32 }),
  nightTakeoff: varchar('night_takeoff', { length: 32 }),
  nightLanding: varchar('night_landing', { length: 32 }),
  schCredit: numeric('sch_credit', { precision: 8, scale: 2 }),
  schPerDiem: numeric('sch_per_diem', { precision: 8, scale: 2 }),
  schLhPerDiem: numeric('sch_lh_per_diem', { precision: 8, scale: 2 }),
  schPncCredit: numeric('sch_pnc_credit', { precision: 8, scale: 2 }),
  schSimCredit: numeric('sch_sim_credit', { precision: 8, scale: 2 }),
  schAlCredit: numeric('sch_al_credit', { precision: 8, scale: 2 }),
  schOlCredit: numeric('sch_ol_credit', { precision: 8, scale: 2 }),
  schFreighterCredit: numeric('sch_freighter_credit', { precision: 8, scale: 2 }),
  attributes: varchar('attributes', { length: 100 }),
  intBlh: integer('int_blh'),
  fltNum: integer('flt_num'),
  crossTzDutyCount: integer('cross_tz_duty_count'),
  layoverTimes: integer('layover_times'),
  layoverDuration: integer('layover_duration'),
}, (table) => [
  uniqueIndex('uq_manday_fd_daily').on(table.crewId, table.crewBaseDt),
  index('idx_manday_fd_daily_dt').on(table.crewBaseDt),
])

// --- 飞行员排班周期工时汇总 ---
export const crewMandayFdPeriod = pgTable('crew_manday_fd_period', {
  id: bigint('id', { mode: 'number' }).primaryKey().generatedAlwaysAsIdentity(),
  createdBy: varchar('created_by', { length: 30 }).notNull().default('system'),
  createdAt: timestamp('created_at').notNull().defaultNow(),
  updatedBy: varchar('updated_by', { length: 30 }).notNull().default('system'),
  updatedAt: timestamp('updated_at').notNull().defaultNow(),
  crewId: varchar('crew_id', { length: 30 }).notNull(),
  rosterPeriod: varchar('roster_period', { length: 100 }).notNull(),
  rpStart: timestamp('rp_start', { withTimezone: true }).notNull(),
  rpEnd: timestamp('rp_end', { withTimezone: true }).notNull(),
  ft: integer('ft').notNull().default(0),
  augumentFt: integer('augument_ft').notNull().default(0),
  doubleFt: integer('double_ft').notNull().default(0),
  blh: integer('blh').notNull().default(0),
  augumentBlh: integer('augument_blh').notNull().default(0),
  doubleBlh: integer('double_blh').notNull().default(0),
  fdp: integer('fdp').notNull().default(0),
  dp: integer('dp').notNull().default(0),
  nightDp: integer('night_dp').notNull().default(0),
  travel: integer('travel').notNull().default(0),
  credit: numeric('credit', { precision: 8, scale: 2 }).notNull().default('0'),
  fatigue: integer('fatigue').notNull().default(0),
  isLeave: integer('is_leave').notNull().default(0),
  isDayOff: integer('is_day_off').notNull().default(0),
  standby: integer('standby').notNull().default(0),
  actTakeOffs: integer('act_take_offs').notNull().default(0),
  actLandings: integer('act_landings').notNull().default(0),
  ground: integer('ground').notNull().default(0),
  perDiem: integer('per_diem').notNull().default(0),
  normalWp: integer('normal_wp').notNull().default(0),
  extendWp: integer('extend_wp').notNull().default(0),
  csb: integer('csb').notNull().default(0),
  hsb: integer('hsb').notNull().default(0),
  asb: integer('asb').notNull().default(0),
  isAl: integer('is_al').notNull().default(0),
  updowns: integer('updowns').notNull().default(0),
  cat2Updowns: integer('cat2_updowns').notNull().default(0),
  expBlh: integer('exp_blh').notNull().default(0),
  quarantine: integer('quarantine').notNull().default(0),
  highPlateau: integer('high_plateau').notNull().default(0),
  takeoff: integer('takeoff').notNull().default(0),
  landing: integer('landing').notNull().default(0),
  workingHour: numeric('working_hour', { precision: 10, scale: 2 }),
  pncCredit: numeric('pnc_credit', { precision: 10, scale: 2 }),
  simCredit: numeric('sim_credit', { precision: 10, scale: 2 }),
  alCredit: numeric('al_credit', { precision: 10, scale: 2 }),
  olCredit: numeric('ol_credit', { precision: 10, scale: 2 }),
  freighterCredit: numeric('freighter_credit', { precision: 10, scale: 2 }),
  layoverDay: integer('layover_day'),
  lhPerDiem: numeric('lh_per_diem', { precision: 10, scale: 2 }),
  sbyDp: numeric('sby_dp', { precision: 10, scale: 2 }).notNull().default('0'),
  dhdDp: numeric('dhd_dp', { precision: 10, scale: 2 }).notNull().default('0'),
  schCredit: numeric('sch_credit', { precision: 10, scale: 2 }),
  intBlh: integer('int_blh'),
  fltNum: integer('flt_num'),
  crossTzDutyCount: integer('cross_tz_duty_count'),
  layoverTimes: integer('layover_times'),
  layoverDuration: integer('layover_duration'),
  archivedFromDaily: boolean('archived_from_daily').notNull().default(true),
}, (table) => [
  uniqueIndex('uq_manday_fd_period').on(table.crewId, table.rosterPeriod),
])

// --- 飞行员年度工时汇总 ---
export const crewMandayFdYearly = pgTable('crew_manday_fd_yearly', {
  id: bigint('id', { mode: 'number' }).primaryKey().generatedAlwaysAsIdentity(),
  createdBy: varchar('created_by', { length: 30 }).notNull().default('system'),
  createdAt: timestamp('created_at').notNull().defaultNow(),
  updatedBy: varchar('updated_by', { length: 30 }).notNull().default('system'),
  updatedAt: timestamp('updated_at').notNull().defaultNow(),
  crewId: varchar('crew_id', { length: 30 }).notNull(),
  year: char('year', { length: 4 }).notNull(),
  ft: integer('ft').notNull().default(0),
  augumentFt: integer('augument_ft').notNull().default(0),
  doubleFt: integer('double_ft').notNull().default(0),
  blh: integer('blh').notNull().default(0),
  augumentBlh: integer('augument_blh').notNull().default(0),
  doubleBlh: integer('double_blh').notNull().default(0),
  fdp: integer('fdp').notNull().default(0),
  dp: integer('dp').notNull().default(0),
  nightDp: integer('night_dp').notNull().default(0),
  travel: integer('travel').notNull().default(0),
  credit: numeric('credit', { precision: 10, scale: 2 }).notNull().default('0'),
  isLeave: integer('is_leave').notNull().default(0),
  isDayOff: integer('is_day_off').notNull().default(0),
  standby: integer('standby').notNull().default(0),
  actTakeOffs: integer('act_take_offs').notNull().default(0),
  actLandings: integer('act_landings').notNull().default(0),
  perDiem: integer('per_diem').notNull().default(0),
  updowns: integer('updowns').notNull().default(0),
  cat2Updowns: integer('cat2_updowns').notNull().default(0),
  expBlh: integer('exp_blh').notNull().default(0),
  highPlateau: integer('high_plateau').notNull().default(0),
  takeoff: integer('takeoff').notNull().default(0),
  landing: integer('landing').notNull().default(0),
  workingHour: numeric('working_hour', { precision: 12, scale: 2 }),
  pncCredit: numeric('pnc_credit', { precision: 12, scale: 2 }),
  lhPerDiem: numeric('lh_per_diem', { precision: 12, scale: 2 }),
  layoverDay: integer('layover_day'),
  intBlh: integer('int_blh'),
  fltNum: integer('flt_num'),
  archivedFromMonthly: boolean('archived_from_monthly').notNull().default(true),
}, (table) => [
  uniqueIndex('uq_manday_fd_yearly').on(table.crewId, table.year),
])

// --- 客舱/乘务员每日累计工时 ---
export const crewMandayCcAmDaily = pgTable('crew_manday_cc_am_daily', {
  id: bigint('id', { mode: 'number' }).primaryKey().generatedAlwaysAsIdentity(),
  createdBy: varchar('created_by', { length: 30 }).notNull().default('system'),
  createdAt: timestamp('created_at').notNull().defaultNow(),
  updatedBy: varchar('updated_by', { length: 30 }).notNull().default('system'),
  updatedAt: timestamp('updated_at').notNull().defaultNow(),
  crewId: varchar('crew_id', { length: 30 }).notNull(),
  crewBaseDt: date('crew_base_dt').notNull(),
  ft: integer('ft').notNull().default(0),
  blh: integer('blh').notNull().default(0),
  fdp: integer('fdp').notNull().default(0),
  dp: integer('dp').notNull().default(0),
  custDp: integer('cust_dp').notNull().default(0),
  nightDp: integer('night_dp').notNull().default(0),
  travel: integer('travel').notNull().default(0),
  credit: numeric('credit', { precision: 6, scale: 2 }).notNull().default('0'),
  fatigue: integer('fatigue').notNull().default(0),
  isLeave: smallint('is_leave').notNull().default(0),
  isDayOff: smallint('is_day_off').notNull().default(0),
  standby: smallint('standby').notNull().default(0),
  ground: smallint('ground').notNull().default(0),
  perDiem: integer('per_diem').notNull().default(0),
  normalWp: integer('normal_wp').notNull().default(0),
  extendWp: integer('extend_wp').notNull().default(0),
  csb: smallint('csb').notNull().default(0),
  hsb: smallint('hsb').notNull().default(0),
  asb: smallint('asb').notNull().default(0),
  isAl: smallint('is_al').notNull().default(0),
  quarantine: smallint('quarantine').notNull().default(0),
  custData1: numeric('cust_data1', { precision: 6, scale: 2 }),
  custData2: numeric('cust_data2', { precision: 6, scale: 2 }),
  highPlateau: integer('high_plateau').notNull().default(0),
  operatingFleets: varchar('operating_fleets', { length: 100 }),
  operatingAirports: varchar('operating_airports', { length: 100 }),
  workingHour: integer('working_hour').notNull().default(0),
  pncCredit: numeric('pnc_credit', { precision: 8, scale: 2 }),
  simCredit: numeric('sim_credit', { precision: 8, scale: 2 }),
  alCredit: numeric('al_credit', { precision: 8, scale: 2 }),
  olCredit: numeric('ol_credit', { precision: 8, scale: 2 }),
  freighterCredit: numeric('freighter_credit', { precision: 8, scale: 2 }),
  layoverDay: integer('layover_day'),
  lhPerDiem: numeric('lh_per_diem', { precision: 8, scale: 2 }),
  sbyDp: numeric('sby_dp', { precision: 5, scale: 2 }).notNull().default('0'),
  dhdDp: numeric('dhd_dp', { precision: 5, scale: 2 }).notNull().default('0'),
  attributes: varchar('attributes', { length: 100 }),
  intBlh: integer('int_blh'),
  fltNum: integer('flt_num'),
  crossTzDutyCount: integer('cross_tz_duty_count'),
  layoverTimes: integer('layover_times'),
  layoverDuration: integer('layover_duration'),
}, (table) => [
  uniqueIndex('uq_manday_cc_daily').on(table.crewId, table.crewBaseDt),
  index('idx_manday_cc_daily_dt').on(table.crewBaseDt),
])

// --- 客舱月度工时汇总 ---
export const crewMandayCcAmPeriod = pgTable('crew_manday_cc_am_period', {
  id: bigint('id', { mode: 'number' }).primaryKey().generatedAlwaysAsIdentity(),
  createdBy: varchar('created_by', { length: 30 }).notNull().default('system'),
  createdAt: timestamp('created_at').notNull().defaultNow(),
  updatedBy: varchar('updated_by', { length: 30 }).notNull().default('system'),
  updatedAt: timestamp('updated_at').notNull().defaultNow(),
  crewId: varchar('crew_id', { length: 30 }).notNull(),
  rosterPeriod: varchar('roster_period', { length: 100 }).notNull(),
  rpStart: timestamp('rp_start', { withTimezone: true }).notNull(),
  rpEnd: timestamp('rp_end', { withTimezone: true }).notNull(),
  ft: integer('ft').notNull().default(0),
  blh: integer('blh').notNull().default(0),
  fdp: integer('fdp').notNull().default(0),
  dp: integer('dp').notNull().default(0),
  custDp: integer('cust_dp').notNull().default(0),
  nightDp: integer('night_dp').notNull().default(0),
  travel: integer('travel').notNull().default(0),
  credit: numeric('credit', { precision: 8, scale: 2 }).notNull().default('0'),
  isLeave: integer('is_leave').notNull().default(0),
  isDayOff: integer('is_day_off').notNull().default(0),
  standby: integer('standby').notNull().default(0),
  ground: integer('ground').notNull().default(0),
  perDiem: integer('per_diem').notNull().default(0),
  normalWp: integer('normal_wp').notNull().default(0),
  extendWp: integer('extend_wp').notNull().default(0),
  workingHour: integer('working_hour').notNull().default(0),
  pncCredit: numeric('pnc_credit', { precision: 10, scale: 2 }),
  lhPerDiem: numeric('lh_per_diem', { precision: 10, scale: 2 }),
  layoverDay: integer('layover_day'),
  intBlh: integer('int_blh'),
  fltNum: integer('flt_num'),
  crossTzDutyCount: integer('cross_tz_duty_count'),
  archivedFromDaily: boolean('archived_from_daily').notNull().default(true),
}, (table) => [
  uniqueIndex('uq_manday_cc_am_period').on(table.crewId, table.rosterPeriod),
])

// --- 客舱年度工时汇总 ---
export const crewMandayCcAmYearly = pgTable('crew_manday_cc_am_yearly', {
  id: bigint('id', { mode: 'number' }).primaryKey().generatedAlwaysAsIdentity(),
  createdBy: varchar('created_by', { length: 30 }).notNull().default('system'),
  createdAt: timestamp('created_at').notNull().defaultNow(),
  updatedBy: varchar('updated_by', { length: 30 }).notNull().default('system'),
  updatedAt: timestamp('updated_at').notNull().defaultNow(),
  crewId: varchar('crew_id', { length: 30 }).notNull(),
  year: char('year', { length: 4 }).notNull(),
  ft: integer('ft').notNull().default(0),
  blh: integer('blh').notNull().default(0),
  fdp: integer('fdp').notNull().default(0),
  dp: integer('dp').notNull().default(0),
  credit: numeric('credit', { precision: 10, scale: 2 }).notNull().default('0'),
  isLeave: integer('is_leave').notNull().default(0),
  isDayOff: integer('is_day_off').notNull().default(0),
  perDiem: integer('per_diem').notNull().default(0),
  workingHour: integer('working_hour').notNull().default(0),
  pncCredit: numeric('pnc_credit', { precision: 12, scale: 2 }),
  lhPerDiem: numeric('lh_per_diem', { precision: 12, scale: 2 }),
  layoverDay: integer('layover_day'),
  intBlh: integer('int_blh'),
  fltNum: integer('flt_num'),
  archivedFromMonthly: boolean('archived_from_monthly').notNull().default(true),
}, (table) => [
  uniqueIndex('uq_manday_cc_yearly').on(table.crewId, table.year),
])

// --- 工时归档任务执行日志 ---
export const mandayArchiveLog = pgTable('manday_archive_log', {
  id: bigint('id', { mode: 'number' }).primaryKey().generatedAlwaysAsIdentity(),
  createdBy: varchar('created_by', { length: 30 }).notNull().default('system'),
  createdAt: timestamp('created_at').notNull().defaultNow(),
  updatedBy: varchar('updated_by', { length: 30 }).notNull().default('system'),
  updatedAt: timestamp('updated_at').notNull().defaultNow(),
  tableType: varchar('table_type', { length: 10 }).notNull(),
  archiveType: varchar('archive_type', { length: 10 }).notNull(),
  periodStart: date('period_start').notNull(),
  periodEnd: date('period_end').notNull(),
  rowsArchived: integer('rows_archived').notNull().default(0),
  rowsDeleted: integer('rows_deleted').notNull().default(0),
  status: varchar('status', { length: 20 }).notNull().default('success'),
  errorMessage: varchar('error_message', { length: 500 }),
  executedAt: timestamp('executed_at').notNull().defaultNow(),
})
