import { pgTable, bigint, varchar, smallint, timestamp, index } from 'drizzle-orm/pg-core'

export const crewQualification = pgTable('crew_qualification', {
  id: bigint('id', { mode: 'number' }).primaryKey().generatedAlwaysAsIdentity(),
  createdBy: varchar('created_by', { length: 30 }).notNull().default('system'),
  createdAt: timestamp('created_at').notNull().defaultNow(),
  updatedBy: varchar('updated_by', { length: 30 }).notNull().default('system'),
  updatedAt: timestamp('updated_at').notNull().defaultNow(),
  crewId: varchar('crew_id', { length: 30 }).notNull(),
  qualification: varchar('qualification', { length: 20 }).notNull(),
  effDt: timestamp('eff_dt').notNull(),
  renewedDt: timestamp('renewed_dt'),
  expDt: timestamp('exp_dt'),
  fleetSpecific: varchar('fleet_specific', { length: 20 }),
  acType: varchar('ac_type', { length: 10 }),
  rank: varchar('rank', { length: 10 }),
  position: varchar('position', { length: 20 }),
  isValid: smallint('is_valid').notNull().default(0),
  remarks: varchar('remarks', { length: 255 }),
  interfaceCrewQualId: varchar('interface_crew_qual_id', { length: 40 }),
  airport: varchar('airport', { length: 20 }),
  interfaceQualificationId: varchar('interface_qualification_id', { length: 40 }),
  remarkDetails: varchar('remark_details', { length: 255 }),
  bases: varchar('bases', { length: 200 }),
  ranks: varchar('ranks', { length: 200 }),
  fleets: varchar('fleets', { length: 200 }),
  teams: varchar('teams', { length: 200 }),
  nextPlannedDate: timestamp('next_planned_date'),
  displayFlag: smallint('display_flag').notNull().default(1),
  status: varchar('status', { length: 16 }),
  interfaceCrewRecurrentId: varchar('interface_crew_recurrent_id', { length: 50 }),
  projectDate: timestamp('project_date'),
  recordStatus: varchar('record_status', { length: 20 }),
  baseMonth: timestamp('base_month'),
}, (table) => [
  index('idx_crew_qual_crew_id').on(table.crewId),
])
