import { pgTable, bigint, varchar, integer, numeric, timestamp, index } from 'drizzle-orm/pg-core'

export const crewEntitlement = pgTable('crew_entitlement', {
  id: bigint('id', { mode: 'number' }).primaryKey().generatedAlwaysAsIdentity(),
  createdBy: varchar('created_by', { length: 30 }).notNull().default('system'),
  createdAt: timestamp('created_at').notNull().defaultNow(),
  updatedBy: varchar('updated_by', { length: 30 }).notNull().default('system'),
  updatedAt: timestamp('updated_at').notNull().defaultNow(),
  filiale: varchar('filiale', { length: 6 }),
  crewId: varchar('crew_id', { length: 30 }).notNull(),
  entitlementType: varchar('entitlement_type', { length: 10 }).notNull(),
  entitlementYear: varchar('entitlement_year', { length: 4 }),
  entitlement: numeric('entitlement', { precision: 10, scale: 2 }),
  used: numeric('used', { precision: 10, scale: 2 }),
  effDt: timestamp('eff_dt'),
  expDt: timestamp('exp_dt'),
  carryOver: numeric('carry_over', { precision: 6, scale: 4 }),
  carryOverDt: timestamp('carry_over_dt'),
  crewTeam: varchar('crew_team', { length: 50 }),
  crewBase: varchar('crew_base', { length: 50 }),
  crewRank: varchar('crew_rank', { length: 50 }),
  crewFleet: varchar('crew_fleet', { length: 50 }),
  balance: numeric('balance', { precision: 5, scale: 2 }),
  freezed: integer('freezed'),
  unfrozen: numeric('unfrozen', { precision: 5, scale: 2 }),
  groupId: bigint('group_id', { mode: 'number' }),
  operator: varchar('operator', { length: 30 }),
  requestCode: varchar('request_code', { length: 50 }),
  requestName: varchar('request_name', { length: 50 }),
  requestType: varchar('request_type', { length: 50 }),
  seqOrder: numeric('seq_order'),
}, (table) => [
  index('idx_crew_entitlement').on(table.crewId, table.entitlementType),
])
