import { pgTable, bigint, varchar, integer, smallint, numeric, timestamp, uniqueIndex } from 'drizzle-orm/pg-core'

export const airport = pgTable('airport', {
  id: bigint('id', { mode: 'number' }).primaryKey().generatedAlwaysAsIdentity(),
  createdBy: varchar('created_by', { length: 30 }).notNull().default('system'),
  createdAt: timestamp('created_at').notNull().defaultNow(),
  updatedBy: varchar('updated_by', { length: 30 }).notNull().default('system'),
  updatedAt: timestamp('updated_at').notNull().defaultNow(),
  airport: varchar('airport', { length: 3 }).notNull(),
  airportName: varchar('airport_name', { length: 100 }),
  airportNativeName: varchar('airport_native_name', { length: 100 }),
  airportIcao: varchar('airport_icao', { length: 4 }),
  airportAbbr: varchar('airport_abbr', { length: 30 }),
  city: varchar('city', { length: 3 }).notNull(),
  category: varchar('category', { length: 3 }),
  dir: varchar('dir', { length: 1 }).notNull(),
  zoneId: varchar('zone_id', { length: 50 }).notNull(),
  utcStandardOffset: integer('utc_standard_offset').notNull(),
  dstGrp: varchar('dst_grp', { length: 4 }),
  plateauType: varchar('plateau_type', { length: 5 }),
  cats: varchar('cats', { length: 5 }),
  rnp: varchar('rnp', { length: 5 }),
  latitude: numeric('latitude'),
  longitude: numeric('longitude'),
  suitableAccommodation: smallint('suitable_accommodation'),
  inPhone: varchar('in_phone', { length: 200 }),
  outPhone: varchar('out_phone', { length: 200 }),
  country: varchar('country', { length: 2 }),
  state: smallint('state'),
  email: varchar('email', { length: 256 }),
  icRoute: varchar('ic_route', { length: 5 }),
}, (table) => [
  uniqueIndex('uq_airport_code').on(table.airport),
])
