import { pgTable, bigint, varchar, integer, smallint, numeric, timestamp } from 'drizzle-orm/pg-core'

export const composition = pgTable('composition', {
  id: bigint('id', { mode: 'number' }).primaryKey().generatedAlwaysAsIdentity(),
  createdBy: varchar('created_by', { length: 30 }).notNull().default('system'),
  createdAt: timestamp('created_at').notNull().defaultNow(),
  updatedBy: varchar('updated_by', { length: 30 }).notNull().default('system'),
  updatedAt: timestamp('updated_at').notNull().defaultNow(),
  filiale: varchar('filiale', { length: 6 }),
  division: varchar('division', { length: 2 }).notNull(),
  name: varchar('name', { length: 30 }).notNull(),
  nameDesc: varchar('name_desc', { length: 50 }),
  displayOrder: integer('display_order').notNull(),
  hierarchy: smallint('hierarchy'),
})

export const compositionLoad = pgTable('composition_load', {
  id: bigint('id', { mode: 'number' }).primaryKey().generatedAlwaysAsIdentity(),
  createdBy: varchar('created_by', { length: 30 }).notNull().default('system'),
  createdAt: timestamp('created_at').notNull().defaultNow(),
  updatedBy: varchar('updated_by', { length: 30 }).notNull().default('system'),
  updatedAt: timestamp('updated_at').notNull().defaultNow(),
  filiale: varchar('filiale', { length: 20 }).notNull(),
  division: varchar('division', { length: 20 }).notNull(),
  sequence: smallint('sequence').notNull(),
  fltNum: varchar('flt_num', { length: 500 }),
  fleet: varchar('fleet', { length: 30 }),
  flightFlag: varchar('flight_flag', { length: 20 }),
  fltType: varchar('flt_type', { length: 1 }),
  segType: varchar('seg_type', { length: 5 }),
  routeId: bigint('route_id', { mode: 'number' }),
  loadFactor: varchar('load_factor', { length: 15 }),
  effDt: timestamp('eff_dt').notNull(),
  expDt: timestamp('exp_dt'),
  dow: varchar('dow', { length: 7 }).notNull().default('1234567'),
  description: varchar('description', { length: 255 }),
  compId: bigint('comp_id', { mode: 'number' }),
  subFleet: varchar('sub_fleet', { length: 30 }),
  flightAssignment: varchar('flight_assignment', { length: 20 }),
  serviceType: varchar('service_type', { length: 20 }),
  paxNum: varchar('pax_num', { length: 20 }),
  restFacility: integer('rest_facility'),
  departureTime: varchar('departure_time', { length: 200 }),
  arrivalTime: varchar('arrival_time', { length: 200 }),
  optionId: bigint('option_id', { mode: 'number' }),
  blhLow: varchar('blh_low', { length: 200 }),
  blhUpper: varchar('blh_upper', { length: 200 }),
})

export const compositionRank = pgTable('composition_rank', {
  id: bigint('id', { mode: 'number' }).primaryKey().generatedAlwaysAsIdentity(),
  createdBy: varchar('created_by', { length: 30 }).notNull().default('system'),
  createdAt: timestamp('created_at').notNull().defaultNow(),
  updatedBy: varchar('updated_by', { length: 30 }).notNull().default('system'),
  updatedAt: timestamp('updated_at').notNull().defaultNow(),
  compId: bigint('comp_id', { mode: 'number' }).notNull(),
  rank: varchar('rank', { length: 30 }).notNull(),
  planValue: integer('plan_value').notNull(),
  planValueExtra: integer('plan_value_extra').notNull(),
  options: smallint('options').notNull().default(1),
})
