import { pgTable, bigint, varchar, integer, smallint, timestamp, uniqueIndex } from 'drizzle-orm/pg-core'

export const qualification = pgTable('qualification', {
  id: bigint('id', { mode: 'number' }).primaryKey().generatedAlwaysAsIdentity(),
  createdBy: varchar('created_by', { length: 30 }).notNull().default('system'),
  createdAt: timestamp('created_at').notNull().defaultNow(),
  updatedBy: varchar('updated_by', { length: 30 }).notNull().default('system'),
  updatedAt: timestamp('updated_at').notNull().defaultNow(),
  qualification: varchar('qualification', { length: 20 }).notNull(),
  description: varchar('description', { length: 100 }),
  filiale: varchar('filiale', { length: 6 }).notNull(),
  division: varchar('division', { length: 10 }).notNull(),
  qualificationGroup: varchar('qualification_group', { length: 40 }),
  displayIndicator: smallint('display_indicator').notNull().default(0),
  crewFilterIndicator: smallint('crew_filter_indicator').notNull().default(0),
  editorFilterLabel: varchar('editor_filter_label', { length: 40 }),
  isDisplayInHeaderpane: smallint('is_display_in_headerpane').notNull().default(0),
  headerpaneText: varchar('headerpane_text', { length: 10 }),
  headerpaneTextColor: varchar('headerpane_text_color', { length: 10 }),
  displayOrder: integer('display_order'),
  qualificationType: varchar('qualification_type', { length: 40 }),
  dayInAdvance: integer('day_in_advance').notNull().default(0),
  airport: varchar('airport', { length: 3 }),
  fleetSpecific: varchar('fleet_specific', { length: 20 }),
  subFleet: varchar('sub_fleet', { length: 20 }),
  negativeSlippage: integer('negative_slippage'),
  positiveSlippage: integer('positive_slippage'),
  baseMonthFlag: integer('base_month_flag').notNull().default(0),
}, (table) => [
  uniqueIndex('uq_qualification').on(table.qualification),
])

export const qualificationProjection = pgTable('qualification_projection', {
  id: bigint('id', { mode: 'number' }).primaryKey().generatedAlwaysAsIdentity(),
  createdBy: varchar('created_by', { length: 30 }).notNull().default('system'),
  createdAt: timestamp('created_at').notNull().defaultNow(),
  updatedBy: varchar('updated_by', { length: 30 }).notNull().default('system'),
  updatedAt: timestamp('updated_at').notNull().defaultNow(),
  assignment: varchar('assignment', { length: 20 }),
  airport: varchar('airport', { length: 100 }),
  projectionType: varchar('projection_type', { length: 10 }).notNull().default('QUAL'),
  qualification: varchar('qualification', { length: 20 }),
  renewalPeriod: varchar('renewal_period', { length: 6 }),
  renewalUnit: varchar('renewal_unit', { length: 6 }),
  actualization: varchar('actualization', { length: 20 }),
  grace: varchar('grace', { length: 20 }),
  displayOrder: integer('display_order'),
  period: integer('period'),
  unit: varchar('unit', { length: 6 }),
  negativeSlippage: integer('negative_slippage'),
  positiveSlippage: integer('positive_slippage'),
})
