import { pgTable, bigint, varchar, integer, smallint, timestamp, uniqueIndex } from 'drizzle-orm/pg-core'

export const queryCriteria = pgTable('query_criteria', {
  id: bigint('id', { mode: 'number' }).primaryKey().generatedAlwaysAsIdentity(),
  createdBy: varchar('created_by', { length: 30 }).notNull().default('system'),
  createdAt: timestamp('created_at').notNull().defaultNow(),
  updatedBy: varchar('updated_by', { length: 30 }).notNull().default('system'),
  updatedAt: timestamp('updated_at').notNull().defaultNow(),
  criteriaCodeName: varchar('criteria_code_name', { length: 30 }).notNull(),
  criteriaUiName: varchar('criteria_ui_name', { length: 30 }).notNull(),
  refTable: varchar('ref_table', { length: 50 }),
  refColumn: varchar('ref_column', { length: 50 }),
  refCondition: varchar('ref_condition', { length: 100 }),
  dataType: varchar('data_type', { length: 20 }),
  allowableValue: varchar('allowable_value', { length: 250 }),
  dataLength: integer('data_length'),
  lowValue: varchar('low_value', { length: 10 }),
  highValue: varchar('high_value', { length: 20 }),
  flightApplicable: smallint('flight_applicable').notNull(),
  pairingApplicable: smallint('pairing_applicable').notNull(),
  rosterApplicable: smallint('roster_applicable').notNull(),
  remark: varchar('remark', { length: 100 }),
  defaultValue: varchar('default_value', { length: 100 }),
})

export const userQuery = pgTable('user_query', {
  id: bigint('id', { mode: 'number' }).primaryKey().generatedAlwaysAsIdentity(),
  createdBy: varchar('created_by', { length: 30 }).notNull().default('system'),
  createdAt: timestamp('created_at').notNull().defaultNow(),
  updatedBy: varchar('updated_by', { length: 30 }).notNull().default('system'),
  updatedAt: timestamp('updated_at').notNull().defaultNow(),
  name: varchar('name', { length: 100 }).notNull(),
  category: varchar('category', { length: 1 }).notNull(),
  refreshAppend: varchar('refresh_append', { length: 1 }).notNull(),
  grayHide: varchar('gray_hide', { length: 1 }).notNull(),
  isPublic: smallint('is_public').notNull(),
  isEditable: smallint('is_editable').notNull(),
})

export const query = pgTable('query', {
  id: bigint('id', { mode: 'number' }).primaryKey().generatedAlwaysAsIdentity(),
  createdBy: varchar('created_by', { length: 30 }).notNull().default('system'),
  createdAt: timestamp('created_at').notNull().defaultNow(),
  updatedBy: varchar('updated_by', { length: 30 }).notNull().default('system'),
  updatedAt: timestamp('updated_at').notNull().defaultNow(),
  userQueryId: bigint('user_query_id', { mode: 'number' }).notNull(),
  groupCondition: varchar('group_condition', { length: 10 }).notNull(),
  subGroupId: bigint('sub_group_id', { mode: 'number' }),
  subGroupCondition: varchar('sub_group_condition', { length: 10 }),
  criteriaId: bigint('criteria_id', { mode: 'number' }).notNull(),
  criteriaSeq: smallint('criteria_seq').notNull(),
  includeExclude: varchar('include_exclude', { length: 1 }).notNull(),
  operator: varchar('operator', { length: 15 }),
  value1: varchar('value1', { length: 50 }),
  value2: varchar('value2', { length: 50 }),
  value3: varchar('value3', { length: 50 }),
  isBidirectional: smallint('is_bidirectional').notNull().default(0),
  timezone: varchar('timezone', { length: 1 }),
  extCriteria: varchar('ext_criteria', { length: 50 }),
  extOperator: varchar('ext_operator', { length: 15 }),
}, (table) => [
  uniqueIndex('uq_query').on(table.userQueryId, table.criteriaId, table.criteriaSeq),
])

export const sortCriteria = pgTable('sort_criteria', {
  id: bigint('id', { mode: 'number' }).primaryKey().generatedAlwaysAsIdentity(),
  createdBy: varchar('created_by', { length: 30 }).notNull().default('system'),
  createdAt: timestamp('created_at').notNull().defaultNow(),
  updatedBy: varchar('updated_by', { length: 30 }).notNull().default('system'),
  updatedAt: timestamp('updated_at').notNull().defaultNow(),
  criteriaCodeName: varchar('criteria_code_name', { length: 30 }).notNull(),
  criteriaUiName: varchar('criteria_ui_name', { length: 30 }).notNull(),
  dataType: varchar('data_type', { length: 20 }),
  flightApplicable: smallint('flight_applicable').notNull(),
  pairingApplicable: smallint('pairing_applicable').notNull(),
  rosterApplicable: smallint('roster_applicable').notNull(),
  remark: varchar('remark', { length: 100 }),
  criteriaCodeEnum: varchar('criteria_code_enum', { length: 30 }),
})
