// ─── IATA airport → IANA timezone ────────────────────────────────────────────
// One table, three consumers: the alarm engine (wake up / leave home ring in the
// DEPARTURE airport's local time), the time-display formatter (airport-local mode)
// and the ground-duty cards (a day-off row covers the airport's calendar day).
//
// FIXED_OFFSET_MIN is the offline fallback for zones that never observe DST. The
// JS engine's Intl database is not guaranteed to carry every zone (Hermes builds
// have shipped without full IANA data), and this app must never silently fall
// back to UTC for a known airport — the original table only covered Bangkok, so
// every ET flight rendered in UTC.
//
// DST-observing zones (Europe/*, Asia/Beirut, Asia/Jerusalem, …) are listed in
// AIRPORT_TZ only: Intl resolves them correctly, and a fixed offset would be
// wrong for half the year.

export const AIRPORT_TZ: Record<string, string> = {
  // ── Asia / Oceania ──
  TPE: 'Asia/Taipei',
  BKK: 'Asia/Bangkok',
  NRT: 'Asia/Tokyo',
  HND: 'Asia/Tokyo',
  KIX: 'Asia/Tokyo',
  FUK: 'Asia/Tokyo',
  HKG: 'Asia/Hong_Kong',
  SIN: 'Asia/Singapore',
  ICN: 'Asia/Seoul',
  PEK: 'Asia/Shanghai',
  PVG: 'Asia/Shanghai',
  CAN: 'Asia/Shanghai',
  KMG: 'Asia/Shanghai',
  CTU: 'Asia/Shanghai',
  CGK: 'Asia/Jakarta',
  DPS: 'Asia/Makassar',
  KTM: 'Asia/Kathmandu',
  DEL: 'Asia/Kolkata',
  BOM: 'Asia/Kolkata',
  BLR: 'Asia/Kolkata',
  SYD: 'Australia/Sydney',
  MEL: 'Australia/Melbourne',
  // ── Middle East ──
  DXB: 'Asia/Dubai',
  AUH: 'Asia/Dubai',
  SHJ: 'Asia/Dubai',
  MCT: 'Asia/Muscat',
  DOH: 'Asia/Qatar',
  BAH: 'Asia/Bahrain',
  KWI: 'Asia/Kuwait',
  RUH: 'Asia/Riyadh',
  JED: 'Asia/Riyadh',
  DMM: 'Asia/Riyadh',
  MED: 'Asia/Riyadh',
  GIZ: 'Asia/Riyadh',
  AMM: 'Asia/Amman',
  BEY: 'Asia/Beirut',
  TLV: 'Asia/Jerusalem',
  // ── Europe ──
  ARN: 'Europe/Stockholm',
  LHR: 'Europe/London',
  CDG: 'Europe/Paris',
  FRA: 'Europe/Berlin',
  ZRH: 'Europe/Zurich',
  MXP: 'Europe/Rome',
  FCO: 'Europe/Rome',
  ATH: 'Europe/Athens',
  BRU: 'Europe/Brussels',
  CPH: 'Europe/Copenhagen',
  DME: 'Europe/Moscow',
  IST: 'Europe/Istanbul',
  // ── Africa (ET network) ──
  ADD: 'Africa/Addis_Ababa',
  ABV: 'Africa/Lagos',
  ACC: 'Africa/Accra',
  ASO: 'Africa/Addis_Ababa',
  AWA: 'Africa/Addis_Ababa',
  BEW: 'Africa/Maputo',
  BGF: 'Africa/Bangui',
  BJM: 'Africa/Bujumbura',
  BKO: 'Africa/Bamako',
  BLZ: 'Africa/Blantyre',
  BUQ: 'Africa/Harare',
  BZV: 'Africa/Brazzaville',
  CAI: 'Africa/Cairo',
  CKY: 'Africa/Conakry',
  COO: 'Africa/Porto-Novo',
  CPT: 'Africa/Johannesburg',
  DAR: 'Africa/Dar_es_Salaam',
  DIR: 'Africa/Addis_Ababa',
  DLA: 'Africa/Douala',
  DSS: 'Africa/Dakar',
  EBB: 'Africa/Kampala',
  ENU: 'Africa/Lagos',
  FBM: 'Africa/Lubumbashi',
  FIH: 'Africa/Kinshasa',
  FNA: 'Africa/Freetown',
  GBE: 'Africa/Gaborone',
  GDQ: 'Africa/Addis_Ababa',
  GGR: 'Africa/Addis_Ababa',
  HGA: 'Africa/Mogadishu',
  HRE: 'Africa/Harare',
  JIB: 'Africa/Djibouti',
  JNB: 'Africa/Johannesburg',
  KGL: 'Africa/Kigali',
  LFW: 'Africa/Lome',
  LLW: 'Africa/Blantyre',
  LOS: 'Africa/Lagos',
  MBA: 'Africa/Nairobi',
  MGQ: 'Africa/Mogadishu',
  MPM: 'Africa/Maputo',
  MUB: 'Africa/Gaborone',
  NBO: 'Africa/Nairobi',
  NDJ: 'Africa/Ndjamena',
  NLA: 'Africa/Lusaka',
  NOS: 'Indian/Antananarivo',
  PNR: 'Africa/Brazzaville',
  PZU: 'Africa/Khartoum',
  SEZ: 'Indian/Mahe',
  TNR: 'Indian/Antananarivo',
  ZNZ: 'Africa/Dar_es_Salaam',
  // ── Americas ──
  YVR: 'America/Vancouver',
  YYZ: 'America/Toronto',
  YOW: 'America/Toronto',
  YEG: 'America/Edmonton',
  LAX: 'America/Los_Angeles',
  SFO: 'America/Los_Angeles',
  JFK: 'America/New_York',
  EWR: 'America/New_York',
  BOS: 'America/New_York',
  ATL: 'America/New_York',
  CLT: 'America/New_York',
  FLL: 'America/New_York',
  AUS: 'America/Chicago',
  DEN: 'America/Denver',
  CUN: 'America/Cancun',
  GDL: 'America/Mexico_City',
  // ── South Asia / other ──
  DAC: 'Asia/Dhaka',
};

/** Zones in AIRPORT_TZ that never observe DST — safe to resolve without Intl. */
export const FIXED_OFFSET_MIN: Record<string, number> = {
  UTC: 0,
  'Asia/Bangkok': 420,
  'Asia/Taipei': 480,
  'Asia/Tokyo': 540,
  'Asia/Hong_Kong': 480,
  'Asia/Singapore': 480,
  'Asia/Seoul': 540,
  'Asia/Shanghai': 480,
  'Asia/Jakarta': 420,
  'Asia/Makassar': 480,
  'Asia/Kathmandu': 345,
  'Asia/Kolkata': 330,
  'Asia/Dubai': 240,
  'Asia/Muscat': 240,
  'Asia/Qatar': 180,
  'Asia/Bahrain': 180,
  'Asia/Kuwait': 180,
  'Asia/Riyadh': 180,
  'Europe/Istanbul': 180,
  'Europe/Moscow': 180,
  'Africa/Addis_Ababa': 180,
  'Africa/Lagos': 60,
  'Africa/Accra': 0,
  'Africa/Bangui': 60,
  'Africa/Bujumbura': 120,
  'Africa/Bamako': 0,
  'Africa/Blantyre': 120,
  'Africa/Harare': 120,
  'Africa/Brazzaville': 60,
  'Africa/Cairo': 120,
  'Africa/Conakry': 0,
  'Africa/Porto-Novo': 60,
  'Africa/Johannesburg': 120,
  'Africa/Dar_es_Salaam': 180,
  'Africa/Douala': 60,
  'Africa/Dakar': 0,
  'Africa/Kampala': 180,
  'Africa/Lubumbashi': 120,
  'Africa/Kinshasa': 60,
  'Africa/Freetown': 0,
  'Africa/Gaborone': 120,
  'Africa/Mogadishu': 180,
  'Africa/Djibouti': 180,
  'Africa/Kigali': 120,
  'Africa/Lome': 0,
  'Africa/Nairobi': 180,
  'Africa/Ndjamena': 60,
  'Africa/Lusaka': 120,
  'Indian/Antananarivo': 180,
  'Africa/Khartoum': 120,
  'Indian/Mahe': 240,
  'Asia/Dhaka': 360,
};

/** IANA zone for an IATA code; unknown airports fall back to UTC. */
export function airportZone(iata: string | null | undefined): string {
  return AIRPORT_TZ[(iata ?? '').trim().toUpperCase()] ?? 'UTC';
}
